<!--

/**
* includeNewDatabaseWorkflow.html, Suggestions for new database workflow.
*
* @package     Heurist academic knowledge management system
* @link        http://HeuristNetwork.org
* @copyright   (C) 2005-2016 University of Sydney
* @author      Artem Osmakov   <artem.osmakov@sydney.edu.au>
* @author      Ian Johnson     <ian.johnson@sydney.edu.au>
* @license     http://www.gnu.org/licenses/gpl-3.0.txt GNU License 3.0
* @version     4
*/

/*
* Licensed under the GNU License, Version 3.0 (the "License"); you may not use this file except in compliance
* with the License. You may obtain a copy of the License at http://www.gnu.org/licenses/gpl-3.0.txt
* Unless required by applicable law or agreed to in writing, software distributed under the License is
* distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied
* See the License for the specific language governing permissions and limitations under the License.
*/

-->

<p>After creating a new database, please use the links: </p>
<div class="detailRow">
    <div class="detailType" style="width: 180px !important;">Database &gt; <u>Manage structure</u></div>
    <div class="detail">Modify the record types and fields describing them, and add new record types, fields and terms</div>
</div>

<div class="detailRow">
    <div class="detailType" style="width: 180px !important;">Database &gt; <u>Acquire from templates</u></div>
    <div class="detail">Browse and download record type definitions documented on the Heurist network web site. <br />
        In addition to saving a great deal of time, the documentation helps you learn about the best ways of setting up Heurist structures.<br />
        The record type definitions downloaded can later be modified to your requirements.</div>
</div>
<div class="detailRow">
    <div class="detailType" style="width: 180px !important;">Database &gt; <u>Acquire from database</u></div>
    <div class="detail">Find and download common record type definitions from any registered Heurist database, including the specially
        curated databases set up by the Heurist developers. <br />The record type definitions downloaded can later be modified
        to your requirements.</div>
</div>

<div class="detailRow">
    <div class="detailType" style="width: 180px !important;">Database &gt;<u>Properties</u></div>
    <div class="detail">Set information about the database, including ownership and some general behaviours</div>
</div>

<div class="detailRow">
    <div class="detailType" style="width: 180px !important;">Database &gt; <u>Register</u></div>
    <div class="detail">Register the database with the central HeuristScholar.org index.<br />
        This will give your database a unique code and allow Heurist to check for new versions of
        the software and database formats. <br/>It also allows other databases to import structural elements
        (record types, field types and terms) but does NOT confer any form of access to data in this database</div>
</div>

