#!/usr/bin/env bash
set -euo pipefail

# Generated by ChatGPT 19/10/25, not checked.

# =======================
# Defaults / parameters
# =======================
DEST_USER=""
DEST_HOST=""
PORT="22"                       # current/initial ssh port to connect
KEY_PATH="${HOME}/.ssh/id_ed25519"
KEY_TYPE="ed25519"

DRY_RUN="0"
RSYNC_TEST_DIR=""

DISABLE_PASSWORD_AUTH="0"
ALLOW_USERS=""
ALLOW_GROUPS=""

SET_PORT=""                     # target SSH port on destination (two-phase)
FINALIZE_PORT_SWITCH="0"        # remove old port after successful test
INSTALL_FAIL2BAN="0"
BACKUP_AND_PRINT="0"

# =======================
# Helpers
# =======================
usage() {
  cat <<EOF
Usage: $0 --dest-user USER --dest-host HOST [options]

Required:
  --dest-user USER              Remote username
  --dest-host HOST              Remote hostname or IP

Common:
  --port N                      Current SSH port to reach remote (default: 22)
  --key-path PATH               Private key path (default: ~/.ssh/id_ed25519)
  --rsync-test DIR              After setup, test rsync of DIR -> HOST:DIR
  --dry-run                     Make the rsync a dry run (no changes)

Hardening:
  --disable-password-auth       Disable password logins on remote (key-only)
  --allow-users "LIST"          Set AllowUsers (space-separated; supports user@host)
  --allow-groups "LIST"         Set AllowGroups (space-separated)

Port change (safe two-phase):
  --set-port N                  Add/listen on new SSH port N (keeps old), open firewall/SELinux, reload sshd, test connectivity
  --finalize-port-switch        After success on new port, remove old port and close its firewall hole

Fail2ban:
  --install-fail2ban            Install & configure Fail2ban for the active SSH port

Audit:
  --backup-and-print            Extra backups of SSH config + print effective sshd config, ports, firewall, selinux, fail2ban

Examples:
  $0 --dest-user alice --dest-host example.org
  $0 --dest-user alice --dest-host example.org --disable-password-auth --allow-users "alice bob"
  $0 --dest-user alice --dest-host example.org --set-port 2222 --install-fail2ban --backup-and-print
EOF
}

err() { echo "ERROR: $*" >&2; }
info(){ echo "==> $*"; }

# =======================
# Arg parsing
# =======================
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dest-user) DEST_USER="${2:-}"; shift 2;;
    --dest-host) DEST_HOST="${2:-}"; shift 2;;
    --port) PORT="${2:-}"; shift 2;;
    --key-path) KEY_PATH="${2:-}"; shift 2;;
    --rsync-test) RSYNC_TEST_DIR="${2:-}"; shift 2;;
    --dry-run) DRY_RUN="1"; shift 1;;

    --disable-password-auth) DISABLE_PASSWORD_AUTH="1"; shift 1;;
    --allow-users) ALLOW_USERS="${2:-}"; shift 2;;
    --allow-groups) ALLOW_GROUPS="${2:-}"; shift 2;;

    --set-port) SET_PORT="${2:-}"; shift 2;;
    --finalize-port-switch) FINALIZE_PORT_SWITCH="1"; shift 1;;

    --install-fail2ban) INSTALL_FAIL2BAN="1"; shift 1;;
    --backup-and-print) BACKUP_AND_PRINT="1"; shift 1;;

    -h|--help) usage; exit 0;;
    *) err "Unknown option: $1"; usage; exit 1;;
  esac
done

[[ -n "$DEST_USER" && -n "$DEST_HOST" ]] || { err "--dest-user and --dest-host are required"; usage; exit 1; }

# =======================
# Prep local key
# =======================
mkdir -p "${HOME}/.ssh"
chmod 700 "${HOME}/.ssh"

if [[ ! -f "$KEY_PATH" ]]; then
  info "Generating ${KEY_TYPE} key at ${KEY_PATH} ..."
  ssh-keygen -t "${KEY_TYPE}" -f "${KEY_PATH}" -N "" -C "${USER:-user}@${HOSTNAME:-host}" </dev/tty
else
  info "Using existing key: ${KEY_PATH}"
fi

PUB_KEY="${KEY_PATH}.pub"
[[ -f "$PUB_KEY" ]] || { err "Public key missing: $PUB_KEY"; exit 1; }

SSH_BASE_OPTS=(-p "$PORT" -o StrictHostKeyChecking=accept-new)
SSH_TEST_OPTS=(-o BatchMode=yes)
SSH_ALL_OPTS=("${SSH_BASE_OPTS[@]}" "${SSH_TEST_OPTS[@]}")

# =======================
# Install key on remote
# =======================
info "Installing public key on ${DEST_USER}@${DEST_HOST} ..."
FALLBACK=0
if command -v ssh-copy-id >/dev/null 2>&1; then
  if ! ssh-copy-id -i "$PUB_KEY" -p "$PORT" -o StrictHostKeyChecking=accept-new "${DEST_USER}@${DEST_HOST}"; then
    echo "ssh-copy-id failed; attempting manual fallback."
    FALLBACK=1
  fi
else
  FALLBACK=1
fi

if [[ "$FALLBACK" -eq 1 ]]; then
  TMP_REMOTE="tmp_key_$$.pub"
  scp -P "$PORT" -o StrictHostKeyChecking=accept-new "$PUB_KEY" "${DEST_USER}@${DEST_HOST}:/tmp/${TMP_REMOTE}"
  ssh "${SSH_BASE_OPTS[@]}" "${DEST_USER}@${DEST_HOST}" "set -e
    mkdir -p ~/.ssh && chmod 700 ~/.ssh
    touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys
    if ! grep -qxF \"\$(cat /tmp/${TMP_REMOTE})\" ~/.ssh/authorized_keys; then
      cat /tmp/${TMP_REMOTE} >> ~/.ssh/authorized_keys
    fi
    rm -f /tmp/${TMP_REMOTE}
  "
fi

# =======================
# Test passwordless SSH
# =======================
info "Testing passwordless SSH on port ${PORT} ..."
if ssh -i "$KEY_PATH" "${SSH_ALL_OPTS[@]}" "${DEST_USER}@${DEST_HOST}" "printf 'OK from %s\n' \$(hostname)"; then
  info "Success: passwordless SSH works."
else
  err "Passwordless SSH test failed."
  echo "Hints: check remote perms: ~/.ssh (700), authorized_keys (600), ownership -> ${DEST_USER}:${DEST_USER}"
  exit 2
fi

# =======================
# Remote hardening & audit (assembled as a remote script)
# =======================
remote_script() {
  cat <<'REM'
set -euo pipefail
SUDO="sudo"
CFGDIR="/etc/ssh/sshd_config.d"
MAINCFG="/etc/ssh/sshd_config"
BAKDIR="/root/ssh-backups"
mkdir -p "$BAKDIR" || true

detect_os() {
  if command -v apt-get >/dev/null 2>&1; then echo "debian"; return; fi
  if command -v dnf >/dev/null 2>&1; then echo "rhel"; return; fi
  if command -v yum >/dev/null 2>&1; then echo "rhel"; return; fi
  if command -v zypper >/dev/null 2>&1; then echo "suse"; return; fi
  echo "unknown"
}

ts() { date +%F_%H%M%S; }

backup_cfg() {
  local t="$(ts)"
  if [ -f "$MAINCFG" ]; then $SUDO cp -a "$MAINCFG" "$BAKDIR/sshd_config.bak.$t"; fi
  if [ -d "$CFGDIR" ]; then
    $SUDO tar -C "$CFGDIR" -czf "$BAKDIR/sshd_config.d.bak.$t.tgz" . 2>/dev/null || true
  fi
}

open_firewall_port() {
  local p="$1"
  if command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active --quiet firewalld 2>/dev/null; then
    $SUDO firewall-cmd --permanent --add-port="${p}"/tcp || true
    $SUDO firewall-cmd --add-port="${p}"/tcp || true
    $SUDO firewall-cmd --reload || true
  elif command -v ufw >/dev/null 2>&1; then
    if $SUDO ufw status | grep -qi inactive; then
      echo "UFW inactive; skipping."
    else
      $SUDO ufw allow "${p}/tcp" || true
    fi
  else
    echo "No managed firewall detected; skipping firewall add ${p}."
  fi
}

close_firewall_port() {
  local p="$1"
  if command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active --quiet firewalld 2>/dev/null; then
    $SUDO firewall-cmd --permanent --remove-port="${p}"/tcp || true
    $SUDO firewall-cmd --remove-port="${p}"/tcp || true
    $SUDO firewall-cmd --reload || true
  elif command -v ufw >/dev/null 2>&1; then
    if $SUDO ufw status | grep -qi inactive; then
      echo "UFW inactive; skipping."
    else
      $SUDO ufw delete allow "${p}/tcp" || true
    fi
  fi
}

ensure_selinux_port() {
  local p="$1"
  if command -v getenforce >/dev/null 2>&1 && [ "$(getenforce || true)" != "Disabled" ]; then
    if ! command -v semanage >/dev/null 2>&1; then
      if command -v dnf >/dev/null 2>&1; then $SUDO dnf -y install policycoreutils-python-utils || $SUDO dnf -y install policycoreutils-python
      elif command -v yum >/dev/null 2>&1; then $SUDO yum -y install policycoreutils-python; fi
    fi
    if command -v semanage >/dev/null 2>&1; then
      if ! semanage port -l | grep -qE "ssh_port_t.*\\b${p}\\b"; then
        $SUDO semanage port -a -t ssh_port_t -p tcp "${p}" || $SUDO semanage port -m -t ssh_port_t -p tcp "${p}" || true
      fi
    fi
  fi
}

write_dropin() {
  local allow_users_line="$1"
  local allow_groups_line="$2"
  local extra_lines="$3"
  $SUDO mkdir -p "$CFGDIR"
  $SUDO bash -c "cat > \"$CFGDIR/99-key-only.conf\" <<CONF
# Managed by setup_ssh_key_auth.sh
PubkeyAuthentication yes
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
CONF"
  [ -n "$allow_users_line" ] && $SUDO bash -c "echo \"$allow_users_line\" >> \"$CFGDIR/99-key-only.conf\""
  [ -n "$allow_groups_line" ] && $SUDO bash -c "echo \"$allow_groups_line\" >> \"$CFGDIR/99-key-only.conf\""
  [ -n "$extra_lines" ] && $SUDO bash -c "printf '%s\n' \"$extra_lines\" >> \"$CFGDIR/99-key-only.conf\""
}

flip_in_maincfg() {
  local key="$1" val="$2"
  if grep -qiE "^[#[:space:]]*${key}[[:space:]]+" "$MAINCFG"; then
    $SUDO sed -i -E "s|^[#[:space:]]*${key}[[:space:]].*|${key} ${val}|I" "$MAINCFG"
  else
    $SUDO sh -c "echo '${key} ${val}' >> \"$MAINCFG\""
  fi
}

validate_reload_sshd() {
  if command -v sshd >/dev/null 2>&1; then $SUDO sshd -t; fi
  if systemctl is-active --quiet sshd 2>/dev/null; then
    $SUDO systemctl reload sshd
  elif systemctl is-active --quiet ssh 2>/dev/null; then
    $SUDO systemctl reload ssh
  else
    $SUDO service ssh reload || $SUDO service sshd reload || true
  fi
}

install_fail2ban() {
  local os_family="$(detect_os)"
  if command -v fail2ban-server >/dev/null 2>&1; then echo "Fail2ban already installed."; return; fi
  case "$os_family" in
    debian) $SUDO apt-get update -y; $SUDO DEBIAN_FRONTEND=noninteractive apt-get install -y fail2ban ;;
    rhel)
      if ! rpm -qa | grep -qi epel-release; then
        if command -v dnf >/dev/null 2>&1; then $SUDO dnf -y install epel-release || true
        else $SUDO yum -y install epel-release || true; fi
      fi
      if command -v dnf >/dev/null 2>&1; then $SUDO dnf -y install fail2ban
      else $SUDO yum -y install fail2ban; fi
      ;;
    suse) $SUDO zypper -n install fail2ban || true ;;
    *) echo "Unknown OS family; skipping Fail2ban install." ;;
  esac
}

configure_fail2ban_sshd() {
  local ssh_port="$1"
  $SUDO mkdir -p /etc/fail2ban/jail.d
  $SUDO bash -c "cat > /etc/fail2ban/jail.d/sshd-local.conf <<JAIL
[sshd]
enabled = true
port    = ${ssh_port}
backend = systemd
maxretry = 5
findtime = 10m
bantime  = 1h
JAIL"
  if command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active --quiet firewalld 2>/dev/null; then
    $SUDO sed -i -E 's/^#?banaction = .*/banaction = firewallcmd-ipset/' /etc/fail2ban/jail.conf 2>/dev/null || true
  elif command -v ufw >/dev/null 2>&1; then
    $SUDO sed -i -E 's/^#?banaction = .*/banaction = ufw/' /etc/fail2ban/jail.conf 2>/dev/null || true
  fi
  $SUDO systemctl enable --now fail2ban || $SUDO service fail2ban start || true
  $SUDO systemctl restart fail2ban || true
}

print_audit() {
  echo "===== SSH AUDIT ====="
  echo "--- sshd effective (filtered) ---"
  if command -v sshd >/dev/null 2>&1; then
    sshd -T 2>/dev/null | egrep -i '^(port|passwordauthentication|pubkeyauthentication|kbdinteractiveauthentication|challengeresponseauthentication|allowusers|allowgroups)\b' || true
  fi
  echo "--- listening ports ---"
  ss -tlpn 2>/dev/null | egrep '(:22|:2[0-9]{2,4}|ssh)' || true
  echo "--- firewall ---"
  if command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active --quiet firewalld 2>/dev/null; then
    firewall-cmd --list-ports || true
  elif command -v ufw >/dev/null 2>&1; then
    ufw status verbose || true
  else
    echo "No firewalld/ufw detected."
  fi
  echo "--- SELinux ssh ports ---"
  if command -v semanage >/dev/null 2>&1; then
    semanage port -l | grep ssh_port_t || true
  else
    echo "semanage not present or SELinux disabled."
  fi
  echo "--- fail2ban (sshd jail) ---"
  if command -v fail2ban-client >/dev/null 2>&1; then
    fail2ban-client status sshd || true
  else
    echo "fail2ban not installed."
  fi
  echo "======================="
}
REM
}

# Build and send remote script header
REMOTE_HEADER="$(remote_script)"

# Build remote tail that wires CLI vars and performs actions
read -r -d '' REMOTE_TAIL <<'EOF'
# ==== Caller-provided variables ====
: "${ALLOW_USERS:=}"
: "${ALLOW_GROUPS:=}"
: "${DISABLE_PASSWORD_AUTH:=0}"
: "${SET_PORT:=}"
: "${FINALIZE_PORT_SWITCH:=0}"
: "${PORT:=22}"
: "${INSTALL_FAIL2BAN:=0}"
: "${BACKUP_AND_PRINT:=0}"

# 0) Optional backup of current SSH config
if [ "$BACKUP_AND_PRINT" = "1" ]; then backup_cfg; fi

# 1) Drop-in or main config for base settings + AllowUsers/Groups
ALLOW_USERS_LINE=""
ALLOW_GROUPS_LINE=""
[ -n "$ALLOW_USERS" ]  && ALLOW_USERS_LINE="AllowUsers $ALLOW_USERS"
[ -n "$ALLOW_GROUPS" ] && ALLOW_GROUPS_LINE="AllowGroups $ALLOW_GROUPS"

if [ -d "$CFGDIR" ]; then
  write_dropin "$ALLOW_USERS_LINE" "$ALLOW_GROUPS_LINE" ""
else
  flip_in_maincfg "PubkeyAuthentication" "yes"
  flip_in_maincfg "KbdInteractiveAuthentication" "no"
  flip_in_maincfg "ChallengeResponseAuthentication" "no"
  [ -n "$ALLOW_USERS_LINE" ]  && flip_in_maincfg "AllowUsers"  "$ALLOW_USERS"
  [ -n "$ALLOW_GROUPS_LINE" ] && flip_in_maincfg "AllowGroups" "$ALLOW_GROUPS"
fi

# 2) Disable password auth if requested
if [ "$DISABLE_PASSWORD_AUTH" = "1" ]; then
  if [ -d "$CFGDIR" ]; then
    $SUDO bash -c 'echo "PasswordAuthentication no" >> "$CFGDIR/99-key-only.conf"'
  else
    flip_in_maincfg "PasswordAuthentication" "no"
  fi
fi

# 3) Two-phase port change
CURRENT_PORT="$PORT"
TARGET_PORT="$SET_PORT"
if [ -n "$TARGET_PORT" ]; then
  open_firewall_port "$TARGET_PORT"
  ensure_selinux_port "$TARGET_PORT"
  if [ -d "$CFGDIR" ]; then
    $SUDO bash -c 'cat > "$CFGDIR/98-ports.conf" <<CONF
# Managed by setup_ssh_key_auth.sh
Port '"$CURRENT_PORT"'
Port '"$TARGET_PORT"'
CONF'
  else
    if grep -qiE '^[#[:space:]]*Port[[:space:]]+' "$MAINCFG"; then
      $SUDO sed -i -E '/^[#[:space:]]*Port[[:space:]]+/d' "$MAINCFG"
    fi
    $SUDO bash -c 'printf "%s\n" "Port '"$CURRENT_PORT"'" "Port '"$TARGET_PORT"'" >> "$MAINCFG"'
  fi
  validate_reload_sshd
fi

# 4) Fail2ban
if [ "$INSTALL_FAIL2BAN" = "1" ]; then
  install_fail2ban
  F2B_PORT="$TARGET_PORT"; [ -z "$F2B_PORT" ] && F2B_PORT="$CURRENT_PORT"
  configure_fail2ban_sshd "$F2B_PORT"
fi

# 5) Finalize port switch: keep only TARGET_PORT, close old firewall
if [ "$FINALIZE_PORT_SWITCH" = "1" ] && [ -n "$TARGET_PORT" ]; then
  if [ -d "$CFGDIR" ]; then
    $SUDO bash -c 'cat > "$CFGDIR/98-ports.conf" <<CONF
# Managed by setup_ssh_key_auth.sh
Port '"$TARGET_PORT"'
CONF'
  else
    if grep -qiE '^[#[:space:]]*Port[[:space:]]+' "$MAINCFG"; then
      $SUDO sed -i -E '/^[#[:space:]]*Port[[:space:]]+/d' "$MAINCFG"
    fi
    flip_in_maincfg "Port" "$TARGET_PORT"
  fi
  if [ "$CURRENT_PORT" != "$TARGET_PORT" ]; then close_firewall_port "$CURRENT_PORT"; fi
  validate_reload_sshd
fi

# 6) Print audit if requested
if [ "$BACKUP_AND_PRINT" = "1" ]; then print_audit; fi
EOF

# Ship variables and run remote
ssh -i "$KEY_PATH" "${SSH_BASE_OPTS[@]}" "${DEST_USER}@${DEST_HOST}" \
  "$(printf '%s\n' "$REMOTE_HEADER"; printf '%s\n' "$REMOTE_TAIL")" \
  ALLOW_USERS="$ALLOW_USERS" \
  ALLOW_GROUPS="$ALLOW_GROUPS" \
  DISABLE_PASSWORD_AUTH="$DISABLE_PASSWORD_AUTH" \
  SET_PORT="${SET_PORT:-}" \
  FINALIZE_PORT_SWITCH="$FINALIZE_PORT_SWITCH" \
  PORT="$PORT" \
  INSTALL_FAIL2BAN="$INSTALL_FAIL2BAN" \
  BACKUP_AND_PRINT="$BACKUP_AND_PRINT"

# =======================
# If we added a new port, test connecting to it now
# =======================
if [[ -n "$SET_PORT" ]]; then
  info "Testing SSH on new port ${SET_PORT} ..."
  if ssh -i "$KEY_PATH" -p "$SET_PORT" -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
       "${DEST_USER}@${DEST_HOST}" "printf 'OK on new port %s\n' ${SET_PORT}"; then
    info "Success: new port ${SET_PORT} is reachable."
  else
    err "Could not connect to new port ${SET_PORT}. Old port ${PORT} remains active."
    exit 3
  fi
fi

# =======================
# Optional rsync test
# =======================
if [[ -n "$RSYNC_TEST_DIR" ]]; then
  if command -v rsync >/dev/null 2>&1; then
    USE_PORT="${SET_PORT:-$PORT}"
    info "rsync test of ${RSYNC_TEST_DIR} -> ${DEST_USER}@${DEST_HOST}:${RSYNC_TEST_DIR} (port ${USE_PORT})"
    RSYNC_FLAGS=(-a -v -z -e "ssh -i ${KEY_PATH} -p ${USE_PORT} -o StrictHostKeyChecking=accept-new")
    [[ "$DRY_RUN" == "1" ]] && RSYNC_FLAGS+=(--dry-run)
    rsync "${RSYNC_FLAGS[@]}" "${RSYNC_TEST_DIR%/}/" "${DEST_USER}@${DEST_HOST}:${RSYNC_TEST_DIR%/}/"
  else
    echo "Note: rsync not found locally; skipping rsync test."
  fi
fi

echo "All done."
