#!/usr/bin/env bash
set -euo pipefail

# Generated by ChatGPT 19/10/25, not checked.

# =======================
# Defaults / parameters
# =======================
DEST_USER=""
DEST_HOST=""
PORT="22"
KEY_PATH="${HOME}/.ssh/id_ed25519"
KEY_TYPE="ed25519"

DRY_RUN="0"
RSYNC_TEST_DIR=""

DISABLE_PASSWORD_AUTH="0"
ALLOW_USERS=""
ALLOW_GROUPS=""

# =======================
# Helpers
# =======================
usage() {
  cat <<EOF
Usage: $0 --dest-user USER --dest-host HOST [options]

Required:
  --dest-user USER            Remote username
  --dest-host HOST            Remote hostname or IP

Optional:
  --port N                    SSH port (default: 22)
  --key-path PATH             Private key path (default: ~/.ssh/id_ed25519)
  --rsync-test DIR            After setup, test rsync of DIR -> HOST:DIR
  --dry-run                   Make the rsync a dry run (no changes)
  --disable-password-auth     Harden remote: password login OFF (key-only)
  --allow-users "LIST"        Set AllowUsers (space-separated; supports user@host patterns)
  --allow-groups "LIST"       Set AllowGroups (space-separated)

Examples:
  $0 --dest-user alice --dest-host example.org
  $0 --dest-user alice --dest-host example.org --disable-password-auth --allow-users "alice bob@198.51.100.*"
EOF
}

err() { echo "ERROR: $*" >&2; }

# =======================
# Arg parsing
# =======================
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dest-user) DEST_USER="${2:-}"; shift 2;;
    --dest-host) DEST_HOST="${2:-}"; shift 2;;
    --port) PORT="${2:-}"; shift 2;;
    --key-path) KEY_PATH="${2:-}"; shift 2;;
    --rsync-test) RSYNC_TEST_DIR="${2:-}"; shift 2;;
    --dry-run) DRY_RUN="1"; shift 1;;
    --disable-password-auth) DISABLE_PASSWORD_AUTH="1"; shift 1;;
    --allow-users) ALLOW_USERS="${2:-}"; shift 2;;
    --allow-groups) ALLOW_GROUPS="${2:-}"; shift 2;;
    -h|--help) usage; exit 0;;
    *) err "Unknown option: $1"; usage; exit 1;;
  esac
done

[[ -n "$DEST_USER" && -n "$DEST_HOST" ]] || { err "--dest-user and --dest-host are required"; usage; exit 1; }

# =======================
# Prep local key
# =======================
mkdir -p "${HOME}/.ssh"
chmod 700 "${HOME}/.ssh"

if [[ ! -f "$KEY_PATH" ]]; then
  echo "==> Generating ${KEY_TYPE} key at ${KEY_PATH} ..."
  ssh-keygen -t "${KEY_TYPE}" -f "${KEY_PATH}" -N "" -C "${USER:-user}@${HOSTNAME:-host}" </dev/tty
else
  echo "==> Using existing key: ${KEY_PATH}"
fi

PUB_KEY="${KEY_PATH}.pub"
[[ -f "$PUB_KEY" ]] || { err "Public key missing: $PUB_KEY"; exit 1; }

SSH_BASE_OPTS=(-p "$PORT" -o StrictHostKeyChecking=accept-new)
SSH_TEST_OPTS=(-o BatchMode=yes)
SSH_ALL_OPTS=("${SSH_BASE_OPTS[@]}" "${SSH_TEST_OPTS[@]}")

# =======================
# Install key on remote
# =======================
echo "==> Installing public key on ${DEST_USER}@${DEST_HOST} ..."
FALLBACK=0
if command -v ssh-copy-id >/dev/null 2>&1; then
  if ! ssh-copy-id -i "$PUB_KEY" -p "$PORT" -o StrictHostKeyChecking=accept-new "${DEST_USER}@${DEST_HOST}"; then
    echo "==> ssh-copy-id failed; will try manual fallback."
    FALLBACK=1
  fi
else
  FALLBACK=1
fi

if [[ "$FALLBACK" -eq 1 ]]; then
  TMP_REMOTE="tmp_key_$$.pub"
  scp -P "$PORT" -o StrictHostKeyChecking=accept-new "$PUB_KEY" "${DEST_USER}@${DEST_HOST}:/tmp/${TMP_REMOTE}"
  ssh "${SSH_BASE_OPTS[@]}" "${DEST_USER}@${DEST_HOST}" "set -e
    mkdir -p ~/.ssh && chmod 700 ~/.ssh
    touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys
    if ! grep -qxF \"\$(cat /tmp/${TMP_REMOTE})\" ~/.ssh/authorized_keys; then
      cat /tmp/${TMP_REMOTE} >> ~/.ssh/authorized_keys
    fi
    rm -f /tmp/${TMP_REMOTE}
  "
fi

# =======================
# Test passwordless SSH
# =======================
echo "==> Testing passwordless SSH ..."
if ssh -i "$KEY_PATH" "${SSH_ALL_OPTS[@]}" "${DEST_USER}@${DEST_HOST}" "printf 'OK from %s\n' \$(hostname)"; then
  echo "==> Success: passwordless SSH works."
else
  err "Passwordless SSH test failed."
  echo "Hints: check remote perms: ~/.ssh (700), authorized_keys (600), ownership -> ${DEST_USER}:${DEST_USER}"
  exit 2
fi

# =======================
# Optional rsync test
# =======================
if [[ -n "$RSYNC_TEST_DIR" ]]; then
  if command -v rsync >/dev/null 2>&1; then
    echo "==> rsync test of ${RSYNC_TEST_DIR} -> ${DEST_USER}@${DEST_HOST}:${RSYNC_TEST_DIR}"
    RSYNC_FLAGS=(-a -v -z -e "ssh -i ${KEY_PATH} -p ${PORT} -o StrictHostKeyChecking=accept-new")
    [[ "$DRY_RUN" == "1" ]] && RSYNC_FLAGS+=(--dry-run)
    rsync "${RSYNC_FLAGS[@]}" "${RSYNC_TEST_DIR%/}/" "${DEST_USER}@${DEST_HOST}:${RSYNC_TEST_DIR%/}/"
  else
    echo "Note: rsync not found locally; skipping rsync test."
  fi
fi

# =======================
# Optional hardening on remote
# =======================
if [[ "$DISABLE_PASSWORD_AUTH" == "1" ]]; then
  echo "==> Hardening remote SSH: disabling password auth and applying AllowUsers/AllowGroups ..."
  # We send ALLOW_USERS/GROUPS inline; careful with quoting
  REMOTE_CMD=$'set -euo pipefail\n'\
$'SUDO="sudo"\n'\
$'CFGDIR="/etc/ssh/sshd_config.d"\n'\
$'AU='"$(printf %q "$ALLOW_USERS")"$'\n'\
$'AG='"$(printf %q "$ALLOW_GROUPS")"$'\n'\
$'write_dropin() {\n'\
$'  $SUDO bash -c '\''cat > "$CFGDIR/99-key-only.conf" <<CONF\n'\
$'# Enforced by setup_ssh_key_auth.sh\n'\
$'PasswordAuthentication no\n'\
$'KbdInteractiveAuthentication no\n'\
$'ChallengeResponseAuthentication no\n'\
$'PubkeyAuthentication yes\n'\
$'CONF\n'\''\n'\
$'  if [ -n "$AU" ]; then $SUDO bash -c '\''echo "AllowUsers '"$ALLOW_USERS"'" >> "$CFGDIR/99-key-only.conf"'\''; fi\n'\
$'  if [ -n "$AG" ]; then $SUDO bash -c '\''echo "AllowGroups '"$ALLOW_GROUPS"'" >> "$CFGDIR/99-key-only.conf"'\''; fi\n'\
$'}\n'\
$'if [ -d "$CFGDIR" ]; then\n'\
$'  write_dropin\n'\
$'else\n'\
$'  TS=$(date +%F_%H%M%S)\n'\
$'  $SUDO cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak.$TS\n'\
$'  # Flip core auth switches\n'\
$'  $SUDO sed -i -E \'s/^[#[:space:]]*PasswordAuthentication[[:space:]].*/PasswordAuthentication no/I\' /etc/ssh/sshd_config\n'\
$'  $SUDO sed -i -E \'s/^[#[:space:]]*ChallengeResponseAuthentication[[:space:]].*/ChallengeResponseAuthentication no/I\' /etc/ssh/sshd_config\n'\
$'  if grep -qiE \'^[#[:space:]]*KbdInteractiveAuthentication\' /etc/ssh/sshd_config 2>/dev/null; then\n'\
$'    $SUDO sed -i -E \'s/^[#[:space:]]*KbdInteractiveAuthentication[[:space:]].*/KbdInteractiveAuthentication no/I\' /etc/ssh/sshd_config\n'\
$'  else\n'\
$'    $SUDO sh -c '\''echo "KbdInteractiveAuthentication no" >> /etc/ssh/sshd_config'\''\n'\
$'  fi\n'\
$'  if grep -qiE \'^[#[:space:]]*PubkeyAuthentication\' /etc/ssh/sshd_config; then\n'\
$'    $SUDO sed -i -E \'s/^[#[:space:]]*PubkeyAuthentication[[:space:]].*/PubkeyAuthentication yes/I\' /etc/ssh/sshd_config\n'\
$'  else\n'\
$'    $SUDO sh -c '\''echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config'\''\n'\
$'  fi\n'\
$'  # Apply AllowUsers/Groups if provided\n'\
$'  if [ -n "$AU" ]; then\n'\
$'    if grep -qiE \'^[#[:space:]]*AllowUsers\' /etc/ssh/sshd_config; then\n'\
$'      $SUDO sed -i -E "s#^[#[:space:]]*AllowUsers.*#AllowUsers '"$ALLOW_USERS"'#I" /etc/ssh/sshd_config\n'\
$'    else\n'\
$'      $SUDO sh -c '\''echo "AllowUsers '"$ALLOW_USERS"'" >> /etc/ssh/sshd_config'\''\n'\
$'    fi\n'\
$'  fi\n'\
$'  if [ -n "$AG" ]; then\n'\
$'    if grep -qiE \'^[#[:space:]]*AllowGroups\' /etc/ssh/sshd_config; then\n'\
$'      $SUDO sed -i -E "s#^[#[:space:]]*AllowGroups.*#AllowGroups '"$ALLOW_GROUPS"'#I" /etc/ssh/sshd_config\n'\
$'    else\n'\
$'      $SUDO sh -c '\''echo "AllowGroups '"$ALLOW_GROUPS"'" >> /etc/ssh/sshd_config'\''\n'\
$'    fi\n'\
$'  fi\n'\
$'fi\n'\
$'# Validate and reload\n'\
$'if command -v sshd >/dev/null 2>&1; then $SUDO sshd -t; fi\n'\
$'if systemctl is-active --quiet sshd 2>/dev/null; then\n'\
$'  $SUDO systemctl reload sshd\n'\
$'elif systemctl is-active --quiet ssh 2>/dev/null; then\n'\
$'  $SUDO systemctl reload ssh\n'\
$'else\n'\
$'  $SUDO service ssh reload || $SUDO service sshd reload || true\n'\
$'fi\n'

  ssh -i "$KEY_PATH" "${SSH_BASE_OPTS[@]}" "${DEST_USER}@${DEST_HOST}" "$REMOTE_CMD"

  echo "==> Remote SSH hardened. Keep THIS session open and open a NEW terminal to confirm key access."
fi

echo "All done."
