<?php

function sendReminderEmail($reminder, $USERS_DATABASE, $HOST) {

	if (! $USERS_DATABASE) $USERS_DATABASE = USERS_DATABASE;
	if ($HOST === NULL) $HOST = HOST;

	$recipients = array();
	if (@$reminder['rem_email']) {
		array_push($recipients, array(
			"email" => $reminder['rem_email'],
			"e"		=> $reminder['rem_email'],
			"u"		=> null));
	}
	else if (@$reminder['rem_usr_id']) {
		$res = mysql_query('select firstname,lastname,EMail from '.$USERS_DATABASE.'.Users where Id = '.$reminder['rem_usr_id']);
		$row = mysql_fetch_assoc($res);
		if ($row) {
			array_push($recipients, array(
				"email" => $row['firstname'].' '.$row['lastname'].' <'.$row['EMail'].'>',
				"e"		=> null,
				"u"		=> $reminder['rem_usr_id']));
		}
	}
	else if (@$reminder['rem_cgr_id']) {
		$res = @$reminder['rem_id'] 
				? mysql_query('select firstname,lastname,EMail,Id
							   from coll_group_links left join '.$USERS_DATABASE.'.Users on cgl_usr_id=Id
							   left join reminders_blacklist on rbl_user_id=Id and rbl_rem_id = '.$reminder['rem_id'].'
							   where cgl_cgr_id = '.$reminder['rem_cgr_id'].' and isnull(rbl_id)')
				: mysql_query('select firstname,lastname,EMail,Id
							   from coll_group_links left join '.$USERS_DATABASE.'.Users on cgl_usr_id=Id
							   where cgl_cgr_id = '.$reminder['rem_cgr_id']);
			
		while ($row = mysql_fetch_assoc($res)) {
			array_push($recipients, array(
				"email" => $row['firstname'].' '.$row['lastname'].' <'.$row['EMail'].'>',
				"e"		=> null,
				"u"		=> $row['Id']));
		}
	}
	else if (@$reminder['rem_wg_id']) {
		$res = @$reminder['rem_id']
				? mysql_query('select firstname,lastname,EMail,Id
							   from '.$USERS_DATABASE.'.UserGroups left join '.$USERS_DATABASE.'.Users on ug_user_id=Id
							   left join reminders_blacklist on rbl_user_id=Id and rbl_rem_id = '.$reminder['rem_id'].'
							   where ug_group_id = '.$reminder['rem_wg_id'].' and isnull(rbl_id)')
				: mysql_query('select firstname,lastname,EMail,Id
							   from '.$USERS_DATABASE.'.UserGroups left join '.$USERS_DATABASE.'.Users on ug_user_id=Id
							   where ug_group_id = '.$reminder['rem_wg_id']);
		while ($row = mysql_fetch_assoc($res))
			array_push($recipients, array(
				"email" => $row['firstname'].' '.$row['lastname'].' <'.$row['EMail'].'>',
				"e"		=> null,
				"u"		=> $row['Id']));
	}

	$email_headers = 'From: Heurist reminder service <no-reply@'.$HOST.'>';

	$res = mysql_query('select firstname,lastname,EMail from '.$USERS_DATABASE.'.Users where Id = '.$reminder['rem_owner_id']);
	$owner = mysql_fetch_assoc($res);
	if ($owner) {
		if (@$reminder['rem_email']  || (@$reminder['rem_user_id']  &&  @$reminder['rem_usr_id'] != @$reminder['rem_owner_id']))
			$email_headers .= "\r\nCc: ".$owner['firstname'].' '.$owner['lastname'].' <'.$owner['EMail'].'>';
		$email_headers .= "\r\nReply-To: ".$owner['firstname'].' '.$owner['lastname'].' <'.$owner['EMail'].'>';
	}

	$res = mysql_query('select rec_title, rec_wg_id, rec_visibility, grp_name from records left join '.$USERS_DATABASE.'.Groups on grp_id=rec_wg_id where rec_id = '.$reminder['rem_rec_id']);
	$bib = mysql_fetch_assoc($res);

	$email_subject = '[Heurist] "'.$bib['rec_title'].'"';

	if (@$reminder['rem_usr_id'] != @$reminder['rem_owner_id'])
		$email_subject .= ' from ' . $owner['firstname'].' '.$owner['lastname'];

	foreach($recipients as $recipient) {
		$email_text = 'Reminder From: ' . ($reminder['rem_usr_id'] == $reminder['rem_owner_id'] ? 'you'
										   : $owner['firstname'].' '.$owner['lastname'].' <'.$owner['EMail'].'>') . "\n\n"
					. 'For: "'.$bib['rec_title'].'"' . "\n\n"
					. 'URL: http://'.$HOST.'/heurist/?w=all&q=ids:'.$reminder['rem_rec_id'] . "\n\n";
					
		if ($bib['rec_wg_id'] && $bib['rec_visibility'] == 'Hidden') {
			$email_text .= "Note: Resource belongs to workgroup ".$bib['grp_name'] . "\n"
         				.	"You must be logged in to Heurist and a member of this workgroup to view it". "\n\n";
		}
		
		$email_text .= 'Message: '.$reminder['rem_message'] . "\n\n";
		
		if (@$reminder['rem_id']  &&  $reminder['rem_freq'] != "once") {
			$email_text .= "-------------------------------------------\n\n"
						.  "You will receive this reminder " . $reminder['rem_freq'] . "\n"
						.  "Click below if you do not wish to receive this reminder again:\n\n"
						.  "http://".$HOST."/heurist/php/delete-reminder.php?r=".$reminder['rem_id']
						.  ($recipient['u'] ? "&u=".$recipient['u'] : "&e=".$recipient['e']) . "&h=".$reminder['rem_nonce'] . "\n\n";
		} else {
			$email_text .= "-------------------------------------------\n\n"
						.  "You will not receive this reminder again.\n\n";
		}
		$email_text .= "-------------------------------------------\n"
					.  "This email was generated by Heurist:\n"
					.  "http://".$HOST."\n";

		mail($recipient['email'], $email_subject, $email_text, $email_headers);
	}

	return true;
}

?>
