/* 
<!-- FILENAME.EXT  Brief description here, date of creation, by whom 

 Copyright 2005 - 2010 University of Sydney Digital Innovation Unit
 This file is part of the Heurist academic knowledge management system 
 (http://HeuristScholar.org,  mailto:info@heuristscholar.org)

 Concept and direction: Ian Johnson.
 Developers: Tom Murtagh, Kim Jackson, Steve White, Steven Hayes, Maria Shvedova, Artem Osmakov, Maxim Nikitin.
 Design and testing: Andrew Wilson, Ireneusz Golka, Martin King.
 
 Heurist is free software; you can redistribute it and/or modify it under the terms of the
 GNU General Public License as published by the Free Software Foundation; either version 3
 of the License, or (at your option) any later version.

 Heurist is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along with this software.
 If not, see <http://www.gnu.org/licenses/> or write to the Free Software Foundation,Inc., 
 675 Mass Ave, Cambridge, MA 02139, USA.

--> 
*/