<?php
/**
* utils_mail.php - main email sending function
*/

function sendEmail($email_to, $email_title, $email_text, $email_header, $is_utf8=false){

    $res = null;
    
    if(!$email_to){
        $res = "Mail send failed. Recipient email address is not defined.";
    }else if(!$email_text){
        $res = "Mail send failed. Message text is not defined.";
    }
    
    if(!$res){
    
        if(!$email_title){
            $email_title = "";
        }
        $email_title = "[HEURIST] ".$email_title;
        
        if(!$email_header){
            $email_header = "From: HEURIST";
            if(defined('HEURIST_SERVER_NAME')){
                $email_header = $email_header." (".HEURIST_DBNAME.") <no-reply@".HEURIST_SERVER_NAME.">";
            }
        }
        
        
        if($is_utf8){
            $email_header = $email_header."\r\nContent-Type: text/plain; charset=utf-8\r\n";
            $email_title = '=?utf-8?B?'.base64_encode($email_title).'?=';
        }
        
        $email_text = $email_text."\n\n"
        ."-------------------------------------------\n"
        ."This email was generated by Heurist"
        .(defined('HEURIST_BASE_URL') ?(":\n".HEURIST_BASE_URL) :"")."\n";
        

        $rv = mail($email_to, $email_title, $email_text, $email_header);
        if(!$rv){
            $res = "Can not send email. This may indicate that mail transport agent is not correctly configured on server. Please advise the system adminstrator";
        }
    }
    
    if($res){ //error
        error_log($res);
    }else{
        $res = "ok";        
    }
    
    return "ok";
}  
?>
