<?php
$flds = "  `dty_ID`, `dty_Name`, `dty_Documentation`,
            `dty_Type`, `dty_HelpText`, `dty_ExtendedDescription`, `dty_Status`,
            `dty_OriginatingDBID`, `dty_NameInOriginatingDB`, `dty_IDInOriginatingDB`,
            `dty_DetailTypeGroupID`, `dty_OrderInGroup`,
            `dty_JsonTermIDTree`, `dty_TermIDTreeNonSelectableIDs`, `dty_PtrTargetRectypeIDs`,
            `dty_FieldSetRecTypeID`, `dty_ShowInLists`, `dty_NonOwnerVisibility` ";
?>
