<?php
// Be sure to use this quote  `  not the upright quote, or you will jsut get field names in place of data
$flds = "`ont_ID`,`ont_ShortName`,`ont_FullName`,`ont_Description`,
        `ont_RefURI`,`ont_Status`,
        `ont_OriginatingDBID`,`ont_NameInOriginatingDB`,`ont_IDInOriginatingDB`,
        `ont_Order`,`ont_LocallyModified` ";
                    
            // Note: You must also add any new fields to the print format statement
            

?>
