<?php
// Be sure to use this quote  `  not the upright quote, or you will jsut get field names in place of data
$flds = "`rst_ID`, `rst_RecTypeID`,
            `rst_DetailTypeID`, `rst_DisplayName`, `rst_DisplayHelpText`,
            `rst_DisplayExtendedDescription`, `rst_DisplayOrder`, `rst_DisplayWidth`,
            `rst_DefaultValue`, `rst_RecordMatchOrder`, `rst_CalcFunctionID`,
            `rst_RequirementType`, `rst_NonOwnerVisibility`, `rst_Status`, `rst_MayModify`,
            `rst_OriginatingDBID`, `rst_IDInOriginatingDB`,
            `rst_MaxValues`, `rst_MinValues`, `rst_DisplayDetailTypeGroupID`,
            `rst_FilteredJsonTermIDTree`, `rst_PtrFilteredIDs`,
            `rst_OrderForThumbnailGeneration`, `rst_TermIDTreeNonSelectableIDs` ";
?>
