<?php
// Be sure to use this quote  `  not the upright quote, or you will jsut get field names in place of data
$flds = "`trm_ID`, `trm_Label`, `trm_InverseTermId`,
            `trm_Description`, `trm_Status`,
            `trm_OriginatingDBID`,`trm_NameInOriginatingDB`,`trm_IDInOriginatingDB`,
            `trm_AddedByImport`,`trm_IsLocalExtension`, `trm_Domain`, `trm_OntID`,
            `trm_ChildCount`, `trm_ParentTermID`, `trm_Depth`,`trm_LocallyModified` ";
?>
