{* generated by h3 *}
<table border="1">
{foreach $results as $record}
{strip}
<tr bgcolor="{cycle values="#ccaacc,#bbcccc"}">
<td>{$record.recID}</td><td>{$record.recRecTypeID}</td><td>{$record.recTitle}</td><td>{$record.recURL}</td><td>{$record.recScratchPad}</td><td>{$record.recOwnerUGrpID}</td><td>{$record.recNonOwnerVisibility}</td><td>{$record.recURLLastVerified}</td><td>{$record.recURLErrorMessage}</td><td>{$record.recAdded}</td><td>{$record.recModified}</td><td>{$record.recAddedByUGrpID}</td><td>{$record.recHash}</td>
</tr>

{if ($record.recRecTypeID==5)}
<tr><td colspan="13">
<div><label>Title:</label>{$record.title_name}</div>
<div><label>Edited?:</label>{$record.isedited}</div>
<div><label>Year:</label>{$record.year}</div>
<div><label>Number of Pages:</label>{$record.number_of_pages}</div>
<div><label>Number of Volumes:</label>{$record.volume}</div>
<div><label>Edition:</label>{$record.edition_version}</div>
<div><label>Abstract:</label>{$record.abstract}</div>
<div><label>Short Summary:</label>{$record.short_summary}</div>
<div><label>Extended Description:</label>{$record.extended_description}</div>
<div><label>ISBN:</label>{$record.isbn}</div>
<div><label>DOI:</label>{$record.doi}</div>
<div><label>Thumbnail Image:</label>{$record.thumbnail}</div>
<div><label>Other Files:</label>{$record.associatedfile}</div>
<div><label>Additional Web Links:</label>{$record.web_links}</div>
<div><label>Short Title:</label>{$record.title_short}</div>
<div><label>Alternate Title:</label>{$record.title_alternate}</div>
<div><label>Geographic Location:</label>{$record.geographic_object}</div></td></tr>
{/if}
{/strip}
{/foreach}
</table>