<html>
<head>
<title>This is a test Smarty template generated by Heurist</title>
</head>
<body>

Information:<p>

Name: {$name|capitalize}<br>
Date: {$smarty.now|date_format:"%Y-%m-%d"}<br>
hjghjgjhg

{* generated by h3 *}

<table border="1">
{foreach $results as $record}
{strip}
<tr bgcolor="{cycle values="#ccccaa,#bbcccc"}">
<td>{$record.recID}</td><td>{$record.recRecTypeID}</td><td>{$record.recTitle}</td><td>{$record.recURL}</td><td>{$record.recScratchPad}</td><td>{$record.recOwnerUGrpID}</td><td>{$record.recNonOwnerVisibility}</td><td>{$record.recURLLastVerified}</td><td>{$record.recURLErrorMessage}</td><td>{$record.recAdded}</td><td>{$record.recModified}</td><td>{$record.recAddedByUGrpID}</td><td>{$record.recHash}</td>
</tr>

{if ($record.recRecTypeID==58)}
<tr><td colspan="13">
<div><label>Method name:</label>{$record.title_name}</div>
<div><label>Start year:</label>{$record.start_date}</div>
<div><label>End year (if applic.):</label>{$record.end_date}</div>
<div><label>Thumbnail image:</label>{$record.thumbnail}</div>
<div><label>Additional images:</label>{$record.images}</div>
<div><label>Other files:</label>{$record.associatedfile}</div>
<div><label>Longitude (X):</label>{$record.x_longitude_do_not_use}</div>
<div><label>Latitude (Y):</label>{$record.y_latitude_do_not_use}</div>
<div><label>Geographic object:</label>{$record.geographic_object}</div>
<div><label>Short summary:</label>{$record.short_summary}</div></td></tr>
{/if}

{if ($record.recRecTypeID==53)}
<tr><td colspan="13">
<div><label>Name of organisation:</label>{$record.title_name}</div>
<div><label>Short name or acronym:</label>{$record.name}</div>
<div><label>Country:</label>{$record.country}</div>
<div><label>Location (city):</label>{$record.location}</div>
<div><label>Geographic location:</label>{$record.geographic_object}</div>
<div><label>Start year:</label>{$record.start_date}</div>
<div><label>End year:</label>{$record.end_date}</div>
<div><label>Logo image:</label>{$record.logo_image}</div>
<div><label>Short summary:</label>{$record.short_summary}</div>
<div><label>Organisation type:</label>{$record.organisation_type}</div>
<div><label>Organisation Role:</label>{$record.organisation_role}</div>
<div><label># of staff:</label>{$record.fte_staff}</div>
<div><label>Alternative names:</label>{$record.title_alternate}</div>
<div><label>Description:</label>{$record.extended_description}</div>
<div><label>Thumbnail:</label>{$record.thumbnail}</div>
<div><label>Other images:</label>{$record.images}</div>
<div><label>Other files:</label>{$record.associatedfile}</div>
<div><label>bib5:</label>{$record.bib5}</div>
<div><label>biblio 11:</label>{$record.biblio1_bib2}</div>
<div><label>bibilioo8:</label>{$record.bibilioo8}</div></td></tr>
{/if}

{if ($record.recRecTypeID==1)}
<tr><td colspan="13">
<div><label>Page Title:</label>{$record.title_name}</div>
<div><label>Short Summary:</label>{$record.short_summary}</div>
<div><label>Extended Description:</label>{$record.extended_description}</div>
<div><label>overview2:</label>{$record.overview2}</div>
<div><label>Start page:</label>{$record.start_page}</div>
<div><label>End page:</label>{$record.end_page}</div>
<div><label>Date accessed:</label>{$record.date}</div>
<div><label>Thumbnail Image:</label>{$record.thumbnail}</div>
<div><label>Geographic Location:</label>{$record.geographic_object}</div></td></tr>
{/if}

{if ($record.recRecTypeID==74)}
<tr><td colspan="13">
<div><label>Media file:</label>{$record.associatedfile}</div>
<div><label>Mime Type:</label>{$record.mime_type}</div>
<div><label>Full image url:</label>{$record.full_image_url}</div>
<div><label>Title:</label>{$record.title_name}</div>
<div><label>Abstract:</label>{$record.extended_description}</div>
<div><label>Rights statement/URL:</label>{$record.rights_statement_url}</div>
<div><label>Start Date:</label>{$record.start_date}</div>
<div><label>End Date:</label>{$record.end_date}</div>
<div><label>Technical notes:</label>{$record.notes}</div>
<div><label>Thumbnail image:</label>{$record.thumbnail}</div>
<div><label>Thumbnail image URL:</label>{$record.thumb_image_url}</div>
<div><label>Additional images:</label>{$record.images}</div>
<div><label>Geographic object:</label>{$record.geographic_object}</div>
<div><label>Short summary:</label>{$record.short_summary}</div>
<div><label>Publish permission:</label>{$record.publish_permission}</div>
<div><label>Index number:</label>{$record.call_number}</div></td></tr>
{/if}

{if ($record.recRecTypeID==63)}
<tr><td colspan="13">
<div><label>Project Title:</label>{$record.title_name}</div>
<div><label>Start year:</label>{$record.start_date}</div>
<div><label>End year (if applic.):</label>{$record.end_date}</div>
<div><label>Geographic region:</label>{$record.geographic_region}</div>
<div><label>Location (city, country):</label>{$record.location}</div>
<div><label>Geographic extent:</label>{$record.geographic_object}</div>
<div><label>100 word summary:</label>{$record.short_summary}</div>
<div><label>Extended abstract/description:</label>{$record.extended_description}</div>
<div><label>Thumbnail image for web:</label>{$record.thumbnail}</div>
<div><label>Funding Type:</label>{$record.funding_type}</div>
<div><label>Funding bracket:</label>{$record.funding_bracket}</div>
<div><label>Additional web links:</label>{$record.web_links}</div>
<div><label>Logo:</label>{$record.logo_image}</div>
<div><label>Images:</label>{$record.images}</div>
<div><label>Other files:</label>{$record.associatedfile}</div>
<div><label>DI Component:</label>{$record.di_component}</div>
<div><label>Research or professional field/Discipline:</label>{$record.research_or_professional_field_discipline}</div></td></tr>
{/if}

{if ($record.recRecTypeID==115)}
<tr><td colspan="13">
<div><label>Title:</label>{$record.title_name}</div>
<div><label>Short summary:</label>{$record.short_summary}</div>
<div><label>Citation protocol:</label>{$record.notes}</div></td></tr>
{/if}
{/strip}
{/foreach}
</table>

</body>
</html>