/**
* manageEntity.js - BASE widget
*
* @package     Heurist academic knowledge management system
* @link        http://HeuristNetwork.org
* @copyright   (C) 2005-2020 University of Sydney
* @author      Artem Osmakov   <artem.osmakov@sydney.edu.au>
* @license     http://www.gnu.org/licenses/gpl-3.0.txt GNU License 3.0
* @version     4.0
*/

/*  
* Licensed under the GNU License, Version 3.0 (the "License"); you may not use this file except in compliance
* with the License. You may obtain a copy of the License at http://www.gnu.org/licenses/gpl-3.0.txt
* Unless required by applicable law or agreed to in writing, software distributed under the License is
* distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied
* See the License for the specific language governing permissions and limitations under the License.
*/

//
// METHODS
//        
//_initControls - add panels and init ui elements
//_onActionListener - central listener for action events
//_defineActionButton
//_rendererActionButton  - renderer buttons on item for resultlist
//_recordListHeaderRenderer  - renderer of header for resultlist
//_recordListItemRenderer    - renderer of item for resultlist
//_recordListGetFullData     - callback function to retrieve full record info (in case we use 2 steps search: ids then list per page)  
// _getEditDialog
// _adjustEditDialogHeight - auto adjust dialog height
//_getEditDialogButtons  - return set of buttons fot edit popup it is placed on _toolbar
//_initDialog - init dialog widget 
// popupDialog
// closeDialog

//defaultBeforeClose

//_selectAndClose - event handler for select-and-close (select_multi) or for any selection event for select_single
// selectedRecords get and set selected records 
    
//updateRecordList - listener of onresult event generated by searchEtity
//selectRecordInRecordset - highlight in result list and call selectedRecords
//filterRecordList - listener of onfilter event generated by searchEtity. appicable for use_cache only       
//getRecordSet - get subset of current recordset by Ids
    

// EDIT 
// _getValidatedValues - returns values from edit form
// _afterSaveEventHandler
// _saveEditAndClose - send update request and close popup edit dialog

// _afterInitEditForm perform required after edit form init modifications (show/hide fields, assign even listener )
// addEditRecord - call _initEditForm_step1 and popup edit dialog

// _afterDeleteEvenHandler
//  _deleteAndClose

$.widget( "heurist.manageEntity", {

    // default options
    options: {
    
        //DIALOG section       
        isdialog: false,     // show as dialog @see  _initDialog(), popupDialog(), closeDialog
        height: 400,
        width:  760,
        modal:  true,
        title:  '',
        isFrontUI: false,  //special behaviour for front interface
        innerTitle: false, //show title as top panel 
        
        //LIST section 
        pagesize: 200,      // page size in resultList 
        list_header: false, // show header in list mode (@todo implement)
        list_mode:'default', // use standard resultList widget (for example in defTerms we use treeview)
        resultList:{}, //configuration for resultList widget
        
        //SEARCH/filter section
        use_cache: false,   // search performed once and then we apply local filter  @see updateRecordList, filterRecordList
        //initial search/filter values by title and subset of groups to search
        filter_title: null,
        filter_group_selected:null,
        filter_groups: null,

        in_popup_dialog: false, //rare case when it is opened in popup iframe
        coverall_on_save: true,
        
        //EDIT section
        // none - edit from and buttons are hiiden
        // popup - edit form is opened in as popup
        // inline - edit form next to list on the same screen
        // only  - list is hidden onle edit form is visible
        //  NOTE if select_mode is not manager edit mode is changed to popup forcefully
        edit_mode: 'popup', // none, popup, inline, editonly 
        edit_height:null,
        edit_width :null,
        edit_title :null,
        edit_need_load_fullrecord: false, //if for edit form we need to load full(all data) record
        
        edit_addrecordfirst: false, //special behaviour - show editor first
        
        layout_mode:'short', //short wide  or valid html snippet
    
        // manager - all selection ui (buttons, checkboxes, label with number of sel.records) is hidden
        //        highlight in list works as usual and selected records are used in actions
        // select_single - in list only one item can be highlighted, in dialog mode it will be closed
        // select_multi - several items can be highlighted, chekboxes are visible in list, onselect works only if button prerssed
        select_mode: 'manager', //'select_single','select_multi','manager'

        selectbutton_label: 'Select',  //label for select button
        
        select_return_mode: 'ids', //ids or recordset                              
        
        selection_on_init:null, //ids to be selected on init
        
        selectOnSave:false, //edit/save of record triggers onselect and close dialog, trigger onselect works always on close dialog
        
        //it either loaded from server side if _entityName defined or defined explicitely on client side
        entity: {},       //configuration
        
        //listeners
        onInitFinished:null,  //event listener when dialog is fully inited - use to perform initial search with specific parameters
        onInitEditForm:null,  //event listener when EDIT form is fully inited - used in manageRecords._afterInitEditForm only to open structure field formlet
        onSelect:null,
        beforeClose:null,
        onClose:null,  //
        
        keep_visible_on_selection: false, //for select_single it closes popup on selection
        
        no_bottom_button_bar: false,
        btn_array: null,   //bottom bar buttons
        
        add_to_begin: false,
        
        default_palette_class: null
    },
    
    //system name of entity  - define it to load entity config from server
    _entityName: '', 
    
    //selected records hRecordSet
    _selection:null,
    //cached records hRecordSet
    _cachedRecordset:null,
    //reference to edit form
    _editing:null,

    _currentEditID:null,
    _currentEditRecordset:null,
    
    _as_dialog:null, //reference to itself as dialog (see options.isdialog)
    _edit_dialog:null, //keep reference to popup dialog
    _toolbar:null,
    
    _resultOnSelection: {}, //object that will be sent in _selectAndClose, additiontal parameter "selection" will be added
    
    _innerTitle: null,
    
    // the widget's constructor
    _create: function() {
        // prevent double click to select text
        //it prevents inputs in FF this.element.disableSelection();
    }, //end _create
    
    //
    //  load configuration and call _initControls
    //
    _init: function() {

            
        if(this.options.isdialog){  //show this widget as popup dialog
            this._initDialog();
        }
        
        //init layout
        var layout = '';
        if(this.options.layout_mode=='basic'){  //common tooolbar on top, list on left, edit form on right side
            layout = 
                '<div class="ent_wrapper">'
                    +'<div class="ent_header editForm-toolbar"/>'
                    +'<div class="ent_content_full" style="width:250px">'
                        +    '<div class="ent_header searchForm"/>'     
                        +    '<div class="ent_content_full recordList"/>'
                    +'</div>'
                    +'<div class="ent_content_full editForm" style="left:251px"/>'
                +'</div>';
        }else if(this.options.layout_mode=='short'){ //the same as above, short toolbar above edit on right side
        
            layout = 
                '<div class="ent_wrapper">'
                        +'<div class="ent_wrapper" style="width:320px">'
                        +    '<div class="ent_header searchForm"/>'     
                        +    '<div class="ent_content_full recordList"/>'
                        +'</div>'
                        +'<div class="ent_wrapper editFormContainer" style="left:321px">'
                        //+    '<div class="ent_header editForm-toolbar"/>'
                        +    '<div class="ent_content_full editForm" style="top:0"/>'
                        +'</div>'
                +'</div>';
                
        }else if(this.options.layout_mode=='listonly'){

            layout = '<div class="ent_wrapper">'
                                +    '<div class="searchForm" style="display:none;"/>'     
                                +    '<div class="ent_content_full recordList" style="top:0"/>'
                            +'</div>'

        }else if(this.options.layout_mode=='tabbed'){ //for terms - REMOVE
        
            layout = 
                '<div class="ent_wrapper">'
                        +'<div class="ent_wrapper">'
                        +    '<div class="ent_header searchForm"/>'     
                        +    '<div class="ent_content_full" style="top:4.4em">'
                                +'<div class="ent_content_full recordList" style="width:320px"/>' //treeview
                                +'<div class="ent_wrapper" style="top:4em;left:321px">'
                                +    '<div class="ent_header editForm-toolbar"/>'
                                +    '<div class="ent_content_full editForm"/>'
                                +'</div>'
                                +'<div class="ent_content_full recordList2" style="display:none;left:321px"/>' //image list
                        +'</div>'
                +'</div>';
                
        }else if(this.options.layout_mode=='editonly'){

            layout = 
                '<div class="ent_wrapper">'
                        + '<div class="recordList" style="display:none;"/>'
                        + '<div class="ent_content editForm ui-widget" style="top:15px;bottom:0"/>'
                        //+ '<div class="ent_footer editForm-toolbar"/>'
                +'</div>';
        
        }else{ //custom layout - must contain valid html snippet
            layout = this.options.layout_mode;
        }
        try{
            $(layout).appendTo(this.element);
        }catch(e){
            this.element.html('Cannot init layout. Please contact developers')
            return;
        }
        
        //this.element.css({'font-size':'1em'});
        var fele = this.element.find('.ent_wrapper:first');
        
        if(this.options.innerTitle){ 
            
            fele.children(0).css('top', '38px'); //down manager div to 38
			
            if(this.options.innerTitle===true){
                this._innerTitle = $('<div>').addClass('ui-heurist-header')
                .html('<span class="title">'+this.options['title']+'</span>')
                .insertBefore($(fele.children()[0])); //insert before first wrapper
            }else{
                $(this.options.innerTitle).css({'max-height':'38px'}).insertBefore($(fele.children()[0]));
            }
            
        }
            
        if(!this.options.isdialog){
            if(this.options.layout_mode=='editonly'){
                    //add div at bottom for control buttons
                    $('<div>').addClass('ent_footer editForm-toolbar')
                        .css({'height':'36px','padding':'4px 20px 0px'}).appendTo(fele);
                        
                    this.element.find('.editForm').css({'bottom':'40px'});
                    
                    this._toolbar = this.element.find('.editForm-toolbar');
                    
            }else if(this.options['select_mode']=='select_multi' || this.options['select_mode']=='select_roles')
            {
                    var ele = $('<div>').addClass('ent_footer editForm-toolbar ui-heurist-header')
                        .css({'height':'36px','padding':'4px 20px 0px'}).insertAfter(fele);
                    fele.css('bottom','40px');
                    
                    var that = this;
                    this._defineActionButton2({text:window.hWin.HR( this.options['selectbutton_label'] ),
                            css:{'float':'right',margin:'.5em .4em .5em 0'},  
                            class: 'ui-button-action',
                            click: function() { that._selectAndClose(); }}, ele);
            }
        }
        
        //find 3 elements searchForm, recordList+recordList_toolbar, editForm+editForm_toolbar
        this.recordList = this.element.find('.recordList');
        //this.recordListToolbar = this.element.find('.recordList');
        this.searchForm      = this.element.find('.searchForm');
        this.editForm        = this.element.find('.editForm');
        this.editFormToolbar = this.element.find('.editForm-toolbar');

        //specific for records        
        this.editFormSummary = this.element.find('.editFormSummary');
        this.editFormPopup = this.element.find('.editFormDialog');
        
        //this.element.addClass('ui-heurist-bg-light');
        
        if(this.options.select_mode!='manager'){ //for select mode we allow only popup edit
            if(this.options.edit_mode!='none'){ 
                this.options.edit_mode='popup'; 
            };
        }

        if(this.options.edit_mode=='inline'){
            smsg = 'Select an entity in the list to edit';
        }else{
            smsg = 'loading...';
        }
        this.editForm.html('<div class="center-message">'+window.hWin.HR(smsg)+'</div>');
        
        if(this.options.layout_mode=='short' || this.options.layout_mode=='basic'){
        
            //for select and select mode - editor is always popup    
            if(this.options.edit_mode=='none' || this.options.edit_mode=='popup'){ //hide edit form
                this.recordList.parent().css('width','100%');
                //hide edit form 
                if(this.options.layout_mode=='short') this.editForm.parent().hide();
                else if(this.options.layout_mode=='basic') this.editForm.hide();
                
            }else if(this.options.edit_mode=='editonly'){  //hide list
                this.recordList.parent().hide();
                if(this.options.layout_mode=='short') this.editForm.parent().css('left',0);
                else if(this.options.layout_mode=='basic') this.editForm.css('left',0);
            }
        
        }
        
        var that = this;
        if(!window.hWin.HEURIST4.util.isempty(this._entityName)){
            //entity should be loaded from server
//this._time_debug = new Date().getTime() / 1000;
            window.hWin.HAPI4.EntityMgr.getEntityConfig(this._entityName, 
                    function(entity){
//console.log( 'getEntityConfig  ' + (new Date().getTime() / 1000 - this._time_debug));
//this._time_debug = new Date().getTime() / 1000;
                        
                        that.options.entity = entity;
                        if(that._initControls()){
                            if($.isFunction(that.options.onInitFinished)){
                                that.options.onInitFinished.call(that);
                            }        
                        }
                    });
            return;
        }else{
            //entity already defined or set via options
            this._entityName = this.options.entity['entityName'];
            if(that._initControls()){
                if($.isFunction(that.options.onInitFinished)){
                    that.options.onInitFinished.call( that );
                }        
            }
        }
    },

    //
    //
    //    
    setTitle: function(title){
        
        this.options['title'] = title;
        
        if(this._innerTitle){
            this._innerTitle.find('span.title').html( title );    
        }else if(this._as_dialog && this._as_dialog.dialog('instance')) {
            this._as_dialog.dialog('option', 'title', title);
        }
    },
      
    //  
    // invoked from _init after loading of entity configuration    
    // in base widget: init resultList, adds search and edit panels
    // in descendat: init ui listeners and init searchEntity
    //
    _initControls:function(){
        
        if(!this._entityName || $.isEmptyObject(this.options.entity)){
            return false;
        }
        
        //construct entity from config
        if(window.hWin.HEURIST4.util.isempty(this.options.title)){
                this.options.title = window.hWin.HR(this.options['select_mode']=='manager'?'Manage':'Select') + ' ' +
                    ((this.options['select_mode']!='select_single'
                                ?this.options.entity.entityTitlePlural
                                :this.options.entity.entityTitle));
        }
        this.setTitle(this.options.title);
        
        var that = this;
        
        if(this.options.list_mode=='default'){
            
                this.options.resultList = $.extend(this.options.resultList, 
                {
                       recordDivEvenClass: 'recordDiv_blue',
                       eventbased: false, //do not listent global events
                       multiselect: (this.options.select_mode!='select_single'), //@todo replace to select_mode

                       select_mode: this.options.select_mode,
                       selectbutton_label: this.options.selectbutton_label,
                       
                       entityName: this._entityName,
                       //view_mode: this.options.view_mode?this.options.view_mode:null,
                       supress_load_fullrecord: (this.options.edit_mode == 'editonly'),
                       
                       pagesize:(this.options.pagesize>0) ?this.options.pagesize: 9999999999999,
                       empty_remark: 
                            (this.options.select_mode!='manager' || this.options.entityName!='records')
                            ?this.options.entity.empty_remark  //'<div style="padding:1em 0 1em 0">'++'</div>'
                            :'',
                       searchfull: function(arr_ids, pageno, callback){
                           that._recordListGetFullData(arr_ids, pageno, callback);
                       },//this._recordListGetFullData,    //search function 
                       renderer: function(recordset, record){ 
                                return that._recordListItemRenderer(recordset, record);  //custom render for particular entity type
                            },
                       rendererHeader: this.options.list_header ?function(){
                                return that._recordListHeaderRenderer();  //custom header for list mode (table header)
                                }:null
                               
                });                

                //init record list
                this.recordList.resultList( this.options.resultList );     

                this._on( this.recordList, {        
                        "resultlistonselect": function(event, selected_recs){
                                    //if(!window.hWin.HEURIST4.util.isRecordSet(selected_recs) 
                                    //    || selected_recs.entityName==this._entityName)
                                    //{}
                                        this.selectedRecords(selected_recs); //assign
                                        
                                        if (this.options.edit_mode=='inline'){
                                                this._onActionListener(event, {action:'edit'}); //default action of selection
                                        }
                                    
                                },
                        "resultlistonaction": this._onActionListener        
                        });
                        
        }        
        
       //---------    EDITOR PANEL
       //if actions allowed - add div for edit form exists - it may be shown as right-hand panel or in modal popup
       if(this.options.edit_mode!='none'){
            if(this.options.edit_mode=='inline'){
/* @todo align toolbar in list and editor for wide layout mode
               if(this.recordList){
                   this.recordList.css('width','250px');
                   var list_container = this.recordList.find('.div-result-list-content');
                   
                   this.ent_editor_wrapper.css({'left':'250px'})
                   //align with recordList header
                   this.editForm.css({'border-top':'1px solid #cccccc',
                                        top:list_container.css('top')});

               }
               this.ent_editor_wrapper.show();
*/               
            }else{
               //this.ent_editor_wrapper.addClass('ui-heurist-bg-light').css({'overflow':'hidden'}).hide(); 
            }
       }

        //--------------------------------------------------------------------    

        //var ishelp_on = window.hWin.HAPI4.get_prefs('help_on')==1;
        //$('.heurist-helper1').css('display',ishelp_on?'block':'none');

        
        if(this.options.isdialog && !this.options.edit_addrecordfirst){
            this.popupDialog();
        }
        
        
        window.hWin.HEURIST4.ui.applyCompetencyLevel(-1, this.element); 
        
        return true;
        //place this code in extension ===========    
        /* init search header
        this.searchForm.searchSysGroups(this.options);
            
        this._on( this.searchForm, {
                "searchsysgroupsonresult": this.updateRecordList
                });
       */         
        //extend ===========    
    },

    //Called whenever the option() method is called
    //Overriding this is useful if you can defer processor-intensive changes for multiple option change
    _setOptions: function( ) {
        this._superApply( arguments );
    },

    /* 
    * private function 
    * show/hide buttons depends on current login status
    */
    _refresh: function(){

    },
    // 
    // custom, widget-specific, cleanup.
    _destroy: function() {
        // remove generated elements
        if(this.searchForm) this.searchForm.remove();
        if(this.recordList) this.recordList.remove();
        if(this.editFormSummary) this.editFormSummary.remove();
        if(this.editFormPopup) this.editFormPopup.remove();
        if(this.editForm) this.editForm.remove();
        if(this.editFormToolbar) this.editFormToolbar.remove();

        this._selection = null;
    },
    
    //----------------------
    //
    // listener of action button/menu clicks - central listener for action events
    //
    pre_action:null,
    pre_action_timer:null,
    
    _onActionListener: function(event, action){
        
        if(window.hWin.HAPI4.is_callserver_in_progress()) {
            return;
        }
        
        var recID = 0;
        
        if(action=='select-and-close'){
             this._selectAndClose();
             return true;
        } else {
             var keep_action = action;
             if(action && action.action){
                 recID =  action.recID;
                 action = action.action;
             }
             var that = this;
             
             if(this.pre_action && 
                this.pre_action.action==action){ // && this.pre_action.recID==recID
                 clearTimeout(this.pre_action_timer);
                 this.pre_action_timer = setTimeout(function(){that.pre_action=null},500);
                 return true; //prevent repeatable clicks
             }
             this.pre_action = {action:action, recID:recID};
             this.pre_action_timer = setTimeout(function(){that.pre_action=null},500);
             
             if(action=='add'){
                    this.addEditRecord(-1);
                    return true;
             }else if(action=='delete'){
                    if(recID>0) this._currentEditID = recID;
                    this._deleteAndClose();
                    return true; 
             }
            
             var s = 'User clicked action "'+action+'" for ';
             if(recID>0){
                 s = s + 'rec# '+recID;
                 
              //take records ID from selection   
             }else if(window.hWin.HEURIST4.util.isRecordSet(this._selection) && this._selection.length()>0){
                 s = s + this._selection.length() + ' selected record';
                 var recs = this._selection.getOrder();
                 recID = recs[recs.length-1];
             }else{
                 s = 'Nothing selected';
                 recID = null;
             }
             
             if(action=='edit'){
                    this.addEditRecord(recID);
                    return true;
             }else if(action=='save'){
                    this._saveEditAndClose();
                    return true;
             }else if(action=='cancel'){
                    this._initEditForm_step3(this._currentEditID)
                    return true;
             }else{
                    //window.hWin.HEURIST4.msg.showMsgFlash(s);  
                    this._trigger( "onaction", null, keep_action );
             }
        }
        return false;
    },
    
    //----------------------
    //
    // helper function that creates button for given action
    //
    // action = {key, label, title, icon}
    // mode - full|small|icon|icon_text - full is default mode
    _defineActionButton: function(action, container, mode, style){        
        
        
        if(!action.icon) action.icon = '';
        action.title = (!action.title)?'':window.hWin.HR(action.title);

        if(mode=='icon_text'){ //for resultList item - buttons will be inited after render complete
        
            var res = '<div title="'+(action.title?action.title:action.label)
            + '" class="logged-in-only'
            + (action.class?' '+action.class:'')+'"'
            + (style?' style="'+style+'"':'')
            + (action.recid>0?(' data-recid="'+action.recid>+'"'):'')
            +' role="button" aria-disabled="false" data-key="'+action.key+'">';

                    if(action.icon){
                        res = res + '<span class="ui-icon '+action.icon+'"></span>';    
                    }else{
                        res = res + window.hWin.HR(action.label);
                    }
            res = res + '</div>';
            
            return res;
        }else {
            if(!container) return;
            var btn;
            
            if(!style) style = {};
            
            if(mode=='icon'){
                
                    //class="item inlist logged-in-only" '
                    btn = $('<div>',{title:action.title, 'aria-disabled':false, 'data-key':action.key, 'data-recid':action.recid})
                            .css(style)
                            .appendTo(container);
                    if(action.icon){
                        btn.html('(<span class="ui-icon '+action.icon+'"></span>');    
                    }else{
                        btn.html(window.hWin.HR(action.label));
                    }
                
            }else{
                
                    btn = $('<div>',{'data-key':action.key,'data-recid':action.recid}).button(
                            {icons: {primary: action.icon}, 
                             text: (mode!='small'), 
                             title: action.title, 
                             label: window.hWin.HR(action.label) })
                    .css(style)         
                    .appendTo(container);
                    
                    if(mode=='small'){
                        btn.css('width','16px');
                    }
                    
            }        
            this._on(btn, {'click':function( event ) {
                        window.hWin.HEURIST4.util.stopEvent( event ); 
                        var ele = $(event.target);
                        var key = ele.attr('data-key') || ele.parent().attr('data-key');
                        var recid = ele.attr('data-recid') || ele.parent().attr('data-recid');

                        this._onActionListener(null, {action:key, recID:recid} );
                        //that._trigger( "onaction", null, key );
                    }});
                    
            return btn;
        }
        
    },
    
    //
    // define action buttons for edit toolbar
    //
    _defineActionButton2: function(options, container){        
        
        var btn_opts = {label:options.text, icons:options.icons, title:options.title, showLabel:options.showText!==false};
        
        var btn = $('<button>').button(btn_opts)
                    .click(options.click)
                    .appendTo(container);
        if(options.id){
            btn.attr('id', options.id);
        }
        if(options.css){
            btn.css(options.css);
        }
        if(options.class){
            btn.addClass(options.class);
        }
        if(options.title){
            btn.attr({'title':options.title})    
        }
    },
    
    // @todo  to remove
    _rendererActionButton: function(action, isheader){        
        if(window.hWin.HEURIST4.util.isArrayNotEmpty(this.options.action_select)){        
        //if(this.options.select_mode=='manager'){
            var idx = 0;
            for(idx in this.options.action_select){
                var act = this.options.action_select[idx];
                if(action == act.key)
                {
                    if(isheader==true){

                        return '<div title="' + (act.hint?act.hint:'')
                            +'" style="display:inline-block;border-right:1px solid;width:3em">'
                            +act.title+'</div>';
                        
                    }else{
                        
                        var icon = act.icon;
                        if(window.hWin.HEURIST4.util.isempty(act.icon)){
                            //by default only edit,delete buttons allowed - otherwise need specify icon 
                            //on entity configuration file
                            if(action=='edit'){
                                icon = 'ui-icon-pencil';
                            }else if(action=='delete'){
                                icon = 'ui-icon-circle-close';
                            }else{
                                return ''; 
                            }
                        }
                    
                        return '<div title="'
                            + (act.hint?act.hint:act.title)
                            +'" class="item inlist logged-in-only" '
                            +'style="width:3em" role="button" aria-disabled="false" data-key="'+act.key+'">'
                            +'<span class="ui-icon '+icon+'"></span>'
                            + '</div>';
                    }
                }
            }               
        }
        
        return '';
        
    },
        
    //
    // custom renderer for resultList header
    //
    _recordListHeaderRenderer:function(){
        //TO EXTEND        
        return '';
    },
    
    //
    //
    //
    _initEditorOnly: function( recset ){

            if( recset && recset.length()>0 ){
                    this.updateRecordList(null, {recordset:recset});
                    this.addEditRecord( this.options.rec_ID );
                    return;
            }
        
            //load user for given record id
            if(this.options.rec_ID>0){
                
                    var that = this;                                                
                    
                    var request = {};
                    request[this.options.entity.tablePrefix+'_ID']  = this.options.rec_ID;
                    request['a']          = 'search'; //action
                    request['entity']     = this.options.entity.entityName;
                    request['details']    = 'full';
                    request['request_id'] = window.hWin.HEURIST4.util.random();
                    
                    window.hWin.HAPI4.EntityMgr.doRequest(request, 
                        function(response){
                            if(response.status == window.hWin.ResponseStatus.OK){
                                var recset = new hRecordSet(response.data);
                                if(recset.length()>0){
                                    that.updateRecordList(null, {recordset:recset});
                                    that.addEditRecord( recset.getOrder()[0] );
                                }
                                else {
                                    //nothing found - add new bookmark
                                    that.addEditRecord(-1);
                                }                            
                            }else{
                                window.hWin.HEURIST4.msg.showMsgErr(response);
                                that.closeEditDialog();
                            }
                        });        
                        
            }else{
                this.addEditRecord(-1, true);
            }
    },
    
    //
    // renderer of item for resultlist
    //
    _recordListItemRenderer:function(recordset, record){
        //TO EXTEND        
        return 'implement _recordListItemRenderer';
    },

    //
    // callback function to retrieve full record info (in case we use 2 steps search: ids then list per page)  
    //
    _recordListGetFullData:function(arr_ids, pageno, callback){

        var request = {
                'a'          : 'search',
                'entity'     : this.options.entity.entityName,
                'details'    : 'list',
                'pageno'    : pageno
        };
        
        request[this.options.entity.keyField] = arr_ids;
        
        //request[this.options.entity] = arr_ids;
        
        window.hWin.HAPI4.EntityMgr.doRequest(request, callback);
    },
    
    //
    // dlg_instance if true it returns dialog widget else .ui-dialog element (or editForm parent)
    //
    _getEditDialog: function(dlg_instance){
            if(this.options.edit_mode=='popup' && this._edit_dialog){
                return dlg_instance?this._edit_dialog  :this._edit_dialog.parents('.ui-dialog'); 
            }else if(this.options.edit_mode=='editonly'){

                if(this._as_dialog){
                    return dlg_instance?this._as_dialog :this._as_dialog.parents('.ui-dialog'); 
                }else {
                    return dlg_instance?null :this.editForm.parent();// $(document).find('div.ui-widget')[0];
                }
            }
            return null;
    },

    _dialogresizeTimeout: 0,
    //
    //
    //
    _adjustEditDialogHeight: function(){
        
        var $dlg = this._getEditDialog(true);
        
        if(this._dialogresizeTimeout==0){
            if($dlg!=null){
                //init timeout
                var that = this;
                this._dialogresizeTimeout = setInterval(function(){that._adjustEditDialogHeight()}, 500);
            }else{
                return; //nothing to do 
            }
        }else{
            if($dlg==null || !$dlg.is(':visible')){
                clearTimeout(this._dialogresizeTimeout);
                this._dialogresizeTimeout = 0;   
                return; //dialog is closed
            }
        }
        //execute resize
        var wh = window.hWin.innerHeight;
        var dh = $dlg.dialog('option', 'height');
        //calculate content height
        var sh = 0;
        this.editForm.children().each(function(i,ele){
            if($(ele).is(':visible') && ($(ele).is('fieldset') || 
                $(ele).hasClass('ui-accordion') || 
                  $(ele).hasClass('heurist-helper1'))){
                sh = sh + $(ele).height();
            }
        });
        //description above edit form        
        var ele = $dlg.find('.entity-description')
        if(ele.length>0 && ele.is(':visible')){
            sh = sh + ele.height();
        }
        
        sh = sh+140
        
        if(sh!=dh && (dh<wh || sh<wh)){
            
            var is_oversize = sh>wh;
            
            if(is_oversize){
               sh = wh;  
            }
            
            $dlg.dialog('option','height', sh);
            
            var ele = $dlg.parents('.ui-dialog');
            if(is_oversize || ele.offset().top+sh>wh){
                ele.css({top:is_oversize?0:(wh-sh)});
            }

        }
        
            
    },
    
    //
    //
    //
    _getEditDialogButtons: function(){

        var that = this;        
        var btn_array = [
                 {text:window.hWin.HR((this.options.edit_mode=='popup' || this.options.isdialog)?'Close':'Drop Changes'), 
                    id:'btnRecCancel',
                    css:{'visibility':(this.options.edit_mode=='popup' || 
                                (that.options.edit_mode=='editonly' && that.options.isdialog) ?'visible':'hidden')
                        ,'float':'right',margin:'.5em .4em .5em 0'}, 
                    click: function() { 
                        if(that.options.edit_mode=='popup') {
                            that.editFormPopup.dialog('close'); 
                        }else if(that.options.edit_mode=='editonly' && that.options.isdialog) {
                            that.closeDialog();
                        }else{                                    
                            that._initEditForm_step3(that._currentEditID); //reload
                        }
                    }},
                 {text:window.hWin.HR('Save'),
                    id:'btnRecSave',
                    css:{'visibility':'hidden', 'float':'right',margin:'.5em .4em .5em 0'},  
                    class: 'ui-button-action',
                    click: function() { that._saveEditAndClose(); }}
                 /* IJ 2018-10-17 request   
                 {text:window.hWin.HR('Remove'), 
                    id:'btnRecRemove',
                    css:{'float':'left'},
                    click: function() { that._deleteAndClose(); },
                 } */
                 ];
                 
                 
        //dialog buttons SELECT and CLOSE
        if( this.options.edit_mode!='popup' &&
            (this.options['select_mode']=='select_multi' || this.options['select_mode']=='select_roles'))
        { 
                btn_array.push({text:window.hWin.HR( this.options['selectbutton_label'] ),
                        css:{'float':'right',margin:'.5em .4em .5em 0'},  
                        class: 'ui-button-action',
                        click: function() { that._selectAndClose(); }}); 
        }
		
		// Add extra save button to new base field for a record, replaces the original checkbox
		if(this.options.newFieldForRtyID > 0){
            btn_array.splice(1, 0, {
                text:window.hWin.HR('Create and customise new field'),
                id:'btnSaveExt',
                css:{'display':'none','float':'right',margin:'.5em .8em .5em .4em'},
                class:'ui-button-action',
                click: function() {
                    that._saveEditAndClose();
                }
            });
        }
		
        return btn_array;         
    },

    //
    // init dialog widget 
    //
    _initDialog: function(){
        
            var options = this.options,
                btn_array = [],
                position = options.position,
                    that = this;
                    
            if(this.options.btn_array){ 
                //some custom buttons besides select and close
                btn_array = this.options.btn_array; 
            }
                
        
            //dialog buttons SELECT and CLOSE
            if(options['select_mode']=='select_multi' || options['select_mode']=='select_roles'){ 
                btn_array.push({text:window.hWin.HR( options['selectbutton_label'] ),
                        class: 'ui-button-action',
                        click: function() { that._selectAndClose(); }}); 
            }

            if(options.edit_mode == 'editonly' || options.edit_mode == 'inline'){
                btn_array =  this._getEditDialogButtons();
                
                if(!options.beforeClose){
                    options.beforeClose = function(){
                        return that.defaultBeforeClose();  
                    } 
                }
                
                if ( window.hWin.HEURIST4.util.isnull(position) || $.isEmptyObject(position)){
                    position = this._getDialogPosition();                    
                }
                
                
            }else {
                //if(options.in_popup_dialog===false){ 
                var cancelbutton_label = (options['select_mode']=='select_multi' || options['select_mode']=='select_roles')
                    ?'Cancel':'Close';
                
                btn_array.push({id:'btn_close_cancel', text:window.hWin.HR(cancelbutton_label), 
                        click: function() { 
                            that.closeDialog(); }}); //use usual close dialog 
            }
            
            if(position==null) position = { my: "center", at: "center", of: window };
            var maxw = (window.hWin?window.hWin.innerWidth:window.innerWidth);
            if(options['width']>maxw) options['width'] = maxw*0.95;
            var maxh = (window.hWin?window.hWin.innerHeight:window.innerHeight);
            if(options['height']>maxh) options['height'] = maxh*0.95;
            
            //this.options.window = window.hWin;
            var $dlg = this.element.dialog({
                autoOpen: false ,
                //element: this.element[0],
                height: options['height'],
                width:  options['width'],
                modal:  (options['modal']!==false),
                title: window.hWin.HEURIST4.util.isempty(options['title'])?'':options['title'], //title will be set in  initControls as soon as entity config is loaded
                position: position,
                beforeClose: options.beforeClose,
                resizeStop: function( event, ui ) {//fix bug
                    //that.element.parent()
                    var pele = that.element.parents('div[role="dialog"]');
                    /*
                    var ptop = pele.find('.ui-dialog-titlebar');
                    var hr = ptop.is(':visible')?ptop.height():0;
                    var pbtm = pele.find('.ui-dialog-buttonpane');
                    hr = hr + ((pbtm.length>0 && pbtm.is(':visible'))?pbtm.height():0);
                    */
                    that.element.css({overflow: 'none !important',
                    //border: '1px red solid !important',
                    'width':pele.width()-24 });
                    //,'height':pele.height() - hr });
                },
                close:function(){
/*
                    if(that.options.selectOnSave==true){
                        
                        //var res = that._currentEditRecordset;
                        var res = that.selectedRecords();
                        
                        if(window.hWin.HEURIST4.util.isRecordSet(res)){
                            that._trigger( "onselect", null, 
                                {selection:  
                                    (this.options.select_return_mode=='recordset') ?res :res.getIds()});
                        }else{        
                            that._trigger( "onselect", null, null );
                        }
                    }
*/              
                    
                    if($.isFunction(that.options.onClose)){
                        //that.options.onClose(that._currentEditRecordset);  
                        that.options.onClose.call(that, that.contextOnClose());
                    } 
                    $dlg.remove();    
                    //???? $dlg.parent().remove();    
                        
                },
                buttons: this.options.no_bottom_button_bar?null:btn_array
            }); 
            this._as_dialog = $dlg; 
            
            if (options.edit_mode == 'editonly' || options.edit_mode == 'inline')
            {
                
                this._toolbar = this._as_dialog.parent().find('.ui-dialog-buttonpane');
                //assign unique identificator to get proper position of child edit dialogs
                this._toolbar.attr('posid','edit'+this._entityName+'-'+(new Date()).getTime());
                
            }else if(this.options.default_palette_class){
                this._as_dialog.parent().addClass(this.options.default_palette_class);
                //this.element.addClass(this.options.default_palette_class);
            }
                
            
    },
    
    //
    // show warning in case of modification
    //
    defaultBeforeClose: function(){
        
        var that = this;
        if(that._editing && that._editing.isModified() && that._currentEditID!=null){
            
            var sMsg,sBtnSave,sBtnCancel;
            
            if(this.options.edit_structure){
                //2020-12-06 that._currentEditID=null; that.closeDialog();
                //2020-12-06 return true;
                sMsg = 'Click "Save data" to save the data entered, "Drop data changes" to abandon modifications.'
                +'<br>Structure changes are saved automatically - they are not affecvted by your choice.';
                sBtnSave = 'Save data';
                sBtnCancel = 'Drop data changes';
            }else{
                sMsg = 'You have made changes to the data. Click "Save" otherwise all changes will be lost.';
                sBtnSave = 'Save';
                sBtnCancel = 'Ignore and close';
            }
            
            var $dlg, buttons = {};
            buttons[sBtnSave] = function(){ that._saveEditAndClose(null, 'close'); $dlg.dialog('close'); }; 
            buttons[sBtnCancel] = function(){ that._currentEditID=null; that.closeDialog(); $dlg.dialog('close'); };
            
            $dlg = window.hWin.HEURIST4.msg.showMsgDlg(
                    sMsg,
                    buttons,
                    {title:'Confirm',yes:sBtnSave,no:sBtnCancel});
            return false;   
        }
        if($.isFunction(that.saveUiPreferences))that.saveUiPreferences();
        return true;
    },
    
    //
    // show itself as popup dialog
    //
    popupDialog: function(){
        if(this.options.isdialog){

            //was this.element.dialog("open");
            
            //init hint and help buttons on dialog titlebar
            this.setTitle(this.options.title);                                     
             
            this._as_dialog.dialog("open");
            
            if(this.options.entity.entityName=='records'){ //special case for help
                this._as_dialog.addClass('manageRecords');
            }
            
            if(false){
                var helpURL = window.hWin.HAPI4.baseURL+'context_help/'+this.options.entity.helpContent+' #content';
                window.hWin.HEURIST4.ui.initDialogHintButtons(this._as_dialog,
                    null, //'prefs_'+this._entityName,
                    helpURL, false);
            }
        }
    },

    getDialog: function(){
        return (this.options.isdialog) ?this._as_dialog :null;
    },
    
    //
    // close dialog
    //
    closeDialog: function(is_force){
        if(this.options.isdialog){
            
            if(this._as_dialog.dialog('instance')){
                if(is_force===true){ //disable warning
                    this._as_dialog.dialog('option','beforeClose',null);
                }
                
                this._as_dialog.dialog("close");
            }

        }else if( this.options.keep_visible_on_selection!==true &&
                    this.element.hasClass('ui-menu6-container')){
            this.element.hide();
        }
        
        if(!this.options.isdialog && $.isFunction(this.options.onClose)){
            this.options.onClose.call(this, this.contextOnClose());
        } 
        
    },
    
    //
    // returns context value that is passed as parameter to function options.onClose
    //
    contextOnClose: function(){
        return null;  
    },
    
    //
    //
    //
    _getDialogPosition: function(){
        
            var position = null;
            var tm = 0;

            //detect position
            $('div.ui-dialog[posid^="edit'+this._entityName+'"]')
            //get the latest
            .each(function(i, dlg){
                tm = Math.max(tm, $(dlg).attr('posid').split('-')[1]);
            });
            var dlg = $('div.ui-dialog[posid="edit'+this._entityName+'-'+tm+'"]');
            
            if(dlg.length>0){
                
                /* it does not work properly
                var offset = $(dlg).offset();
                var stop = offset.top+h> $(document).height()?'0':offset.top+20; 
                var sleft = offset.left+w> $(document).width()?'0':offset.left+20; 
                position = { my: "left top", at: sleft+' '+stop, within:window};
                */
                position = { my: "left top", at:'left+20 top+60', of:dlg};
            }else{
                
                var prefs = this.getUiPreferences();
                if(prefs && prefs.top>=0 && prefs.left>=0){
                    position = { my: "left top", at:'left+'+prefs.left+' top+'+prefs.top}; //relative to window    
                }
            }
            
            
            return position;
    },
    
    
    getUiPreferences:function(){
        return null;
    },
    
    saveUiPreferences:function(){
        
    },

    //
    // event handler for select-and-close (select_multi)
    // or for any selection event for select_single
    // triger onselect event
    //
    _selectAndClose: function(){

        if(this.options.isdialog && this.options.edit_mode!='editonly'){
            window.hWin.HAPI4.save_pref('select_dialog_'+this._entityName, 
                            {width: this._as_dialog.dialog('option', 'width'), 
                             height: this._as_dialog.dialog('option', 'height')});
        }
        
        var res = this.selectedRecords();
        
        if(window.hWin.HEURIST4.util.isRecordSet(res)){
            //window.hWin.HAPI4.save_pref('recent_Users', this._selection.getIds(25), 25);      
            
            if(!this._resultOnSelection) this._resultOnSelection = {};
            this._resultOnSelection.selection = (this.options.select_return_mode=='recordset') ?res :res.getIds();
            
            this._trigger( "onselect", null, this._resultOnSelection);
            
        }else{        
            this._trigger( "onselect", null, null );
        }
        this.closeDialog( true ); //force without warning
    },

    //
    // get and set selected records - RecordSet
    //    
    selectedRecords: function(value){
        
        if(window.hWin.HEURIST4.util.isnull(value)){
            //getter
            return this._selection;
        }else{
            
            if($.isArray(value)){
                if(this._cachedRecordset){
                    value = this._cachedRecordset.getSubSetByIds(value);
                }else{
                    //var recset = this.recordList.resultList('getRecordSet', value);
                    //value = recset.getSubSetByIds(value);
                    value = null;               
                }
                //this.recordList.resultList('setSelected', value); //highlight
            }
            //setter
            this._selection = value;
            
            if(this.options.select_mode=='select_single'){
                this._selectAndClose(); //it triggers onselect and closes dialog
            }else{
                //todo? use this._trigger( "onselect", null, this._selection);
                if($.isFunction(this.options.onSelect)){
                    this.options.onSelect.call( this, this._selection );
                }
                
            }
        }
/*        
            if(this._editing.isModified()){
                window.hWin.HEURIST4.msg.showMsgDlg('Data were modified. Ignore and load data for selected record',
                function(){ that._initEditForm_step3(recID); },
                'Confirm');
*/        
        
    },
    
    //
    // highlight selection in recordList and call selectedRecords
    // with given id of first one
    //
    selectRecordInRecordset:function(selval){
        
        var rec_ID, recset;
        
        if(window.hWin.HEURIST4.util.isRecordSet(selval)){
            recset = selval;
        }else if(window.hWin.HEURIST4.util.isNumber(selval) && selval>0){
            rec_ID = selval;
        }else{
            recset = this.getRecordSet();
        }
    
        //select first    
        if(!rec_ID && recset && recset.length()>0){
            rec_ID = recset.getOrder()[0];
        }
        
        if(rec_ID && this.recordList.resultList('instance'))
        {
            this.recordList.resultList('setSelected', [rec_ID]);
            this.selectedRecords([rec_ID]);  //it trigger this.option.onSelect
            
            //default action of selection for inline editor
            if(this.options.edit_mode=='inline') this._onActionListener(null, {action:'edit'}); 
        }
    },
    
    
    //--------------- WORK WITH LIST
    //
    // listener of onresult event generated by searchEtity
    //
    updateRecordList: function( event, data ){
        if (data){
            if(this.options.use_cache){
                this._cachedRecordset = data.recordset;
            }
            
            if(this.recordList.resultList('instance')){ //for editonly recordList is not inited

                //
                // define selection
                //
                if(this.options.selection_on_init && this.options['select_mode']=='select_multi'){
                    this.recordList.resultList('setMultiSelection', this.options.selection_on_init);
                    //this.selectedRecords( this.options.selection_on_init );
                    this.options.selection_on_init = null;
                }
            
                if(this.options.list_mode=='default'){
                    this.recordList.resultList('updateResultSet', data.recordset, data.request);
                }
                
            }
        }
    },
    
    refreshRecordList: function(){
        if(this.recordList && this.recordList.resultList('instance')){
            this.recordList.resultList('refreshPage');  
        }
    },

    //
    // listener of onfilter event generated by searchEtity. appicable for use_cache only       
    //
    filterRecordList: function(event, request){
        
        window.hWin.HEURIST4.msg.sendCoverallToBack();

        var subset = null;
        if(this.options.use_cache && this._cachedRecordset){
            subset = this._cachedRecordset.getSubSetByRequest(request, this.options.entity.fields);
            if(this.options.list_mode=='default'){
                this.recordList.resultList('updateResultSet', subset, request);   
            }
            if(this.options.selection_on_init && this.options['select_mode']=='select_multi'){
                this.recordList.resultList('setMultiSelection', this.options.selection_on_init);
                this.options.selection_on_init = null;
            }
        }
        return subset;
    },

    //
    // get subset of current recordset by Ids
    //
    getRecordSet: function(recIDs){
        if(this.options.use_cache){
            if(window.hWin.HEURIST4.util.isnull(recIDs)){
                return this._cachedRecordset;
            }else{
                return this._cachedRecordset.getSubSetByIds(recIDs);    
            }
        }else if(this.options.list_mode=='default'){
            if(window.hWin.HEURIST4.util.isnull(recIDs)){
                return this.recordList.resultList('getRecordSet')
            }else{
                return this.recordList.resultList('getRecordsById', recIDs);
            }
        }
    },

    //  -----------------------------------------------------
    //
    //  1. returns values from edit form
    // 2. performs special action for virtual and hidden fields 
    // fill them with constructed and/or predefined values
    // EXTEND this method to set values for hidden fields (for example parent term_id or group/domain)
    //
    _getValidatedValues: function(){
        
        if(this._editing.validate()){
            return this._editing.getValues(false);    
        }else{
            var eles = this.editForm.find('.text.ui-state-error');
            
            window.hWin.HEURIST4.msg.showMsgFlash('Missing or invalid data entered'
                +((eles.length>1)?(' for '+eles.length+' fields.'):'')
                ,1500);
                
            var ele = $(eles[0]);
                
            var accrd = ele.parents('div.ui-tabs');
            if(accrd.length>0 && accrd.tabs('instance')){
                var idx = ele.parents('fieldset.ui-tabs-panel').attr('data-tabindex');        
                accrd.tabs('option','active', idx);
            }
            ele.focus();
            
            return null;
        }
    },
    

    //  -----------------------------------------------------
    //
    //  after save event handlers
    //
    
    // this handler is always executed
    _afterSaveEventHandler2: function( recID, fieldvalues ){
    
    },
    
    //this handler optionally executed (not executed if afterAction in saveEditAndClose is specified)
    _afterSaveEventHandler: function( recID, fieldvalues ){
            
            window.hWin.HEURIST4.msg.showMsgFlash(this.options.entity.entityTitle+' '+window.hWin.HR('has been saved'));
            if(this.options.edit_mode=='popup'){
                                                      
                this._currentEditID = null;
                this.editFormPopup.dialog('close');
                
            }else if (this.options.edit_mode=='editonly' && this.options.isdialog){
                
                this._currentEditID = null;
                this._getEditDialog(true).dialog('close'); //_as_dialog
                
            }else if(this.options.edit_mode=='inline'){
                    //reload
                    this._currentEditID = recID;
                    this._initEditForm_step3(this._currentEditID); //reload 
            }
            
            if(this.options.use_cache){
                //refresh item in list
                if(this.options.list_mode=='default'){
                    this.refreshRecordList(); //recordList.resultList('refreshPage');  
                }
            }
            
    },
    
//    
    _time_debug:0,
    
    //-----------------------------------------------------
    //
    // send update request and close popup if edit is in dialog
    // afteraction is used in overriden version of this method
    //
    _saveEditAndClose: function( fields, afterAction, onErrorAction ){

            if(window.hWin.HAPI4.is_callserver_in_progress()) {
//console.log('prevent repeatative call')
                return;   
            }
            
            //2020-12-06 if(this.options.edit_structure){ return; }            
            
            var is_full = 0;
        
            if(!fields){
                fields = this._getValidatedValues(); 
                is_full = 1;
            }

            
            if(fields==null) return; //validation failed
        
            var request = {
                'a'          : 'save',
                'entity'     : this.options.entity.entityName,
                'request_id' : window.hWin.HEURIST4.util.random(),
                'fields'     : fields,
                'isfull'     : is_full  //partial or full update (from edit form)
                };
				
                if(this.options.coverall_on_save) {
                    if(this.options.edit_mode=='popup' && this._edit_dialog || this.options.edit_mode=='editonly'){  
                        //window.hWin.HEURIST4.msg.bringCoverallToFront(this._edit_dialog.parents('.ui-dialog'));   
                        window.hWin.HEURIST4.msg.bringCoverallToFront(this._getEditDialog());   
                    }else {
                        window.hWin.HEURIST4.msg.bringCoverallToFront(this.editForm);   
                    }
                }
                
                //if(this._toolbar) this._toolbar.css('visibility','hidden'); //hide();               
                
                var that = this;                                                
                //that.loadanimation(true);
                window.hWin.HAPI4.EntityMgr.doRequest(request, 
                    function(response){

                        //if(that._toolbar) that._toolbar.css('visibility','visible');//.show();               
                        
/*                        
var fin_time = new Date().getTime() / 1000;
console.log('save '+(  fin_time - this._time_debug));
this._time_debug = fin_time;
*/
                        
                        window.hWin.HEURIST4.msg.sendCoverallToBack();
                        
                        if(response.status == window.hWin.ResponseStatus.OK){

                            var recID = response.data[0];
                            if(recID>0)
                                fields[ that.options.entity.keyField ] = (''+recID);
                            
                            //update record in cache
                            if(that.options.use_cache && that._cachedRecordset){
                                //add or update record in cache
                                that._cachedRecordset.addRecord(recID, fields, that.options.add_to_begin); 
                            }else{
                                //add/update record in recordset in _afterSaveEventHandler depends on entity
                            }
                            
                            if((that.options.edit_mode=='inline' || that.options.edit_mode=='editonly')){
                                if(that._editing) that._editing.setModified(0);
                                that.onEditFormChange(); //update buttons
                            }
                            
                            that.it_was_insert = (that._currentEditID<0);
                            
                            that._afterSaveEventHandler2( recID, fields );        
                            
                            if($.isFunction(afterAction)){
                                afterAction.call(that, recID, fields);
                            }else{
                                that._afterSaveEventHandler( recID, fields );        
                            }
                            
                        }else{
                            if($.isFunction(onErrorAction)){
                                onErrorAction.call(that, response);
                            }else{
                                window.hWin.HEURIST4.msg.showMsgErr(response);    
                            }
                        }
                    });
    },      

    //  -----------------------------------------------------
    //
    //  after save event handler
    //
    _afterDeleteEvenHandler: function( recID ){
        
            this._currentEditID = null;
            window.hWin.HEURIST4.msg.showMsgFlash(this.options.entity.entityTitle+' '+window.hWin.HR('has been deleted'), 2000);
            if(this.options.edit_mode=='popup'){
                //hide popup edit form 
                if(this._edit_dialog){
                    try{
                        isOpenAready = this._edit_dialog.dialog('isOpen');
                        if(isOpenAready){
                            this._edit_dialog.dialog('close');
                        }
                    }catch(e){}
                }
            }else if(this.options.edit_mode=='editonly'){
                //close itself
                this.closeDialog();
                return;
            }
            
            if(this.options.list_mode=='default'){
                //refresh list
                var recset = this.recordList.resultList('getRecordSet');
                recset.removeRecord(recID);
                this.refreshRecordList();//this.recordList.resultList('refreshPage');  
            }
            
            if(this.options.edit_mode=='inline'){
                //for inline - reload edit page with first item in list
                var new_recID = this._getField2(this.options.entity.keyField); 
                if(!(new_recID>0)) new_recID = null;
                new_recID = null;
                this.addEditRecord(new_recID); //null - hide inline edit form 
            }
    },
    
    //  -----------------------------------------------------
    //
    //  delete entity and close popup if edit is dialog
    //
    _deleteAndClose: function(){
        
            if(this._currentEditID==null || this._currentEditID<1) return;

            var request = {
                'a'          : 'delete',
                'entity'     : this.options.entity.entityName,
                'request_id' : window.hWin.HEURIST4.util.random(),
                'recID'      : this._currentEditID                     
                };
                
                var that = this;                                                
                
                window.hWin.HAPI4.EntityMgr.doRequest(request, 
                    function(response){
                        if(response.status == window.hWin.ResponseStatus.OK){

                            var recID = that._currentEditID;
                            if(that.options.use_cache){
                                that._cachedRecordset.removeRecord( recID );
                            }
                            that._afterDeleteEvenHandler( recID );
                            
                        }else{
                            window.hWin.HEURIST4.msg.showMsgErr(response);
                        }
                    });
    },    

    //
    // to override
    //
    onEditFormChange: function( changed_element ){
        
        var force_hide = (changed_element===true);
        
        var mode = 'hidden';
        if(force_hide!==true){
            var isChanged = this._editing.isModified();
            mode = isChanged?'visible':'hidden';
        }

        //show/hide save,cancel,remove buttons
        var ele = this._toolbar;
        if(ele){
            var btn = ele.find('#btnRecCancel');
            if( this.options.edit_mode!='popup' && !(this.options.edit_mode=='editonly' && this.options.isdialog)
                 && !btn.hasClass('alwaysvisible')) { //for popup and editonly always visible
                    btn.css('visibility', mode);
            }
            ele.find('#btnRecSave').css('visibility', mode);
            /* IJ 2018-10-17 request   
            if(this._currentEditRecordset==null){            
                ele.find('#btnRecRemove').css('visibility', 'hidden');
            }else{
                ele.find('#btnRecRemove').css('visibility', 'visible');    
            }*/
        }
    },
    
    //
    //
    //
    _allowActionIfModified: function( callback ){
        
            if(this._editing && this._currentEditID!=null && this._editing.isModified()){
                
                var that = this;
                
                var $mdlg = window.hWin.HEURIST4.msg.showMsgDlg(
                    'New '+this.options.entity.entityTitle+' requested with unsaved modifications in current '+this.options.entity.entityTitle+'.',
                    //'You are about opening new edit form without saving data in current one. Save changes and start new edit?',
                    //'Data were modified in edit form. Ignore modifications and start edit the new data',
                        {
                         'Save changes':function(){ 
                            //save changes and go to next step
                            that._saveEditAndClose( null, callback );
                            $mdlg.dialog('close');
                         },
                         'Drop changes':function(){ 
                            //drop changes load another record
                            callback.call(that);
                            //that._initEditForm_step2(recID);
                            $mdlg.dialog('close');
                         },   
                         'Cancel':function(){
                            $mdlg.dialog('close');
                         }   
                        }
                        ,{title:'Confirm'}); //,yes:'Save changes', no:'Cancel'
            }else{
                callback.call(this);
                //this._initEditForm_step2(recID);            
            }
            
    },
    
    /*
    addEditRecord
    _initEditForm_step1  - it creates hEditing object and warns about save previous data
    _initEditForm_step2  - init buttons for toolbar for inline or open edit form in popup 
    _initEditForm_step3 -  search for full record data (if required)
    _initEditForm_step4 -  prepare record data and initEditForm and fill summary panel (for RECORDS only) for edit form 
    _afterInitEditForm
    */
    
    
    //  -----------------------------------------------------
    //
    //  it creates hEditing object and warns about save previous data
    //
    _initEditForm_step1: function(recID){
        
        if(!this.editForm || this.editForm.length==0) return;

        var that = this;
        
        if(!this._editing){
            this._editing = new hEditing({entity:this.options.entity, container:this.editForm, 
                className: this.options.editClassName,
                onchange:function(){
                that.onEditFormChange(this); //"this" is changed_element
            }}); //pass container
            this._initEditForm_step2(recID);
            
        }else{
            this._allowActionIfModified( function(){ that._initEditForm_step2(recID); } );
        }
    },
    
//define delete on right side
//this._defineActionButton({key:'delete',label:'Remove', title:'', icon:'ui-icon-minus'},
//this.editFormToolbar,'full',{float:'right'});
                
    
    //
    // open popup edit dialog if we need it
    //
    _initEditForm_step2: function(recID){
    
        this._keepPos = 0; 
        this._keepTabsStatus = {};            
        
        if(!(recID==null || this.options.edit_mode=='none')){
        
        var isOpenAready = false;
        if(this.options.edit_mode=='popup'){
            if(this._edit_dialog){
                try{
                    isOpenAready = this._edit_dialog.dialog('isOpen');
                }catch(e){}
            }
        } else if(this.options.edit_mode=='inline') { //inline 
            isOpenAready = this._toolbar && !this._toolbar.is(':empty');
        }
        
        if(!isOpenAready){            
    
            var that = this; 
            this._currentEditID = recID;

            this.editFormPopup = this.editForm;
            
            if(this.options.edit_mode=='popup'){
                
                this.showEditFormDialog( true );
                    
                //help and tips buttons on dialog header
                var helpURL = window.hWin.HAPI4.baseURL+'context_help/'+this.options.entity.helpContent+' #content';
                    window.hWin.HEURIST4.ui.initDialogHintButtons(this.editFormPopup,
                     null,  //  'prefs_'+this._entityName,
                     helpURL, false);
                     
                this._toolbar = this._edit_dialog.parent().find('.ui-dialog-buttonpane');
                     
            }else if(this.editFormToolbar.length>0){ //initialize action buttons
                
                    this._toolbar = this.editFormToolbar;
                    this.editFormToolbar.empty();
                    var btns = this._getEditDialogButtons();
                    for(var idx in btns){
                        this._defineActionButton2(btns[idx], this.editFormToolbar);
                    }
            }
            
        }
        }
        this._initEditForm_step3(recID); 
    },        
    
    //
    // popup edit form in dialog
    //
    showEditFormDialog: function(init_buttons){
                
            var that = this;    
            //hide header toolbar    
            this.editForm.css({'top': 0, overflow:'auto'});
                 
            this._edit_dialog = this.editForm.dialog({
                    autoOpen: true,
                    height: this.options['edit_height']?this.options['edit_height']:400,
                    width:  this.options['edit_width']?this.options['edit_width']:740,
                    modal:  true,
                    title: this.options['edit_title']
                                ?this.options['edit_title']
                                :window.hWin.HR(this._currentEditID<0?'Add':'Edit') + ' ' + this.options.entity.entityTitle,
                    resizeStop: function( event, ui ) {//fix bug
                        //that.element.css({overflow: 'none !important','width':that.element.parent().width()-24 });
                    },
                    beforeClose: function(){
                        //show warning in case of modification
                        if(that._editing.isModified() && that._currentEditID!=null){
                            var $dlg, buttons = {};
                            buttons['Save'] = function(){ 
                                that._saveEditAndClose(null, 'close'); 
                                $dlg.dialog('close'); 
                            }; 
                            buttons['Ignore and close'] = function(){ 
                                    that._currentEditID = null; 
                                    //that.closeDialog(); 
                                    that._edit_dialog.dialog('close'); 
                                    $dlg.dialog('close'); 
                            };
                            
                            $dlg = window.hWin.HEURIST4.msg.showMsgDlg(
                                    'You have made changes to the data. Click "Save" otherwise all changes will be lost.',
                                    buttons,
                                    {title:'Confirm',yes:'Save',no:'Ignore and close'});
                            return false;   
                        }
                        that.saveUiPreferences();
                        return true;
                    },
                    buttons: init_buttons?this._getEditDialogButtons():null
                });        
    },
    
    //
    //
    //
    setDisabledEditForm: function( mode ){
        this._editing.setDisabled(mode);  
    },

    //
    //
    //
    reloadEditForm: function( hard_reload ){
        //this._initEditForm_step3(this._currentEditID);
            
        this._keepPos = 0; 
        this._keepTabsStatus = {};            
        if(this._editing){
            this._keepPos = this.editForm.scrollTop();
            
            //keepTabsStatus
            var that = this;
            this.editForm.find('div[data-group-dtid]').each(function(i,ele){
                ele = $(ele);
                that._keepTabsStatus[ ele.attr('data-group-dtid') ] = ele.tabs('instance')
                    ? ele.tabs('instance').options.active //ele.tabs('option','active')
                    : ele.accordion('option','active');
            });
        }
        
        if(hard_reload===true){
            this._editing.initEditForm(null, null); //clear edit form
            this._initEditForm_step3(this._currentEditID);        
        }else{
            this._initEditForm_step4(null);
        }
        
    },

    //
    // load full data record (if required)
    //
    _initEditForm_step3: function(recID){
        //fill with values
        this._currentEditID = recID;
        
        if(recID==null){
            this._editing.initEditForm(null, null); //clear and hide
        }else{

            if(recID!=null && recID!=-1){ //edit existing record
                if(this.options.edit_need_load_fullrecord){
                    
                    //get primary key field
                    if(!this.options.entity.keyField) return alert('Developer! Define fieldname for ID in entity configuration file!!!');
                    
                    var request = {'a': 'search',
                        'entity': this.options.entity.entityName,  //'defDetailTypes'
                        'details': 'full',
                        'request_id': window.hWin.HEURIST4.util.random()
                    }
                    request[this.options.entity.keyField] = recID;
                    
                    var that = this;                                                
                    
                    window.hWin.HAPI4.EntityMgr.doRequest(request, 
                        function(response){
                            if(response.status == window.hWin.ResponseStatus.OK){
                                var recordset = new hRecordSet(response.data);
                                that._initEditForm_step4(recordset);
                            }else{
                                window.hWin.HEURIST4.msg.showMsgErr(response);
                            }
                        });
                        
                    return;    
                
                }else{
                    var recordset = this.getRecordSet([recID]);
                    this._initEditForm_step4(recordset);
                }
            }else if(recID<0){
                // add new record
                this._initEditForm_step4(null);
            }
            
            
        
        }
        
        return;
    },
    
    //
    // finally initialize editing widget
    //
    _initEditForm_step4: function(recordset){
        this._currentEditRecordset = recordset; 
        
        var is_insert_mode = (recordset==null);
        //pass structure and record details
        if(this._editing){
            this._editing.initEditForm(this.options.entity.fields, recordset, is_insert_mode );
            this._afterInitEditForm();
        }
    },
    
    //
    // get field for currently editing record
    //
    _getField: function(fname){
        
        if(this._currentEditRecordset){
            var record = this._currentEditRecordset.getFirstRecord();
            var value  = this._currentEditRecordset.fld(record, fname);
            return value;
        }else{
            return '';
        }
    },
    
    //
    //
    //
    _getField2: function(fname, record){
        var value = '';
        var recset = this.recordList.resultList('getRecordSet');
        if(recset){
            if(!record){
                record = recset.getFirstRecord();
            }
            if(record){
                value = recset.fld(record, fname);    
            }
        }
        return value;
    },

    
    //-----
    // perform required after edit form init modifications (show/hide fields, assign event listener )
    // for example hide/show some fields based on value of field
    //
    _afterInitEditForm: function(){

        if(this.options.edit_mode=='inline'){ //make labels in edit form narrower
            //@todo reduce it in css                 
            this.editForm.find('.header').css({'min-width':'100px','width':'100px'});
/*            
            //add save button at the end of edit form
            this._defineActionButton({key:'save',label:'Save', title:'', icon:'ui-icon-check'},
                        this.editForm,'full',{display:'inline-block', margin:'0 4px 0 35%'});
            //add save button at the end of edit form
            this._defineActionButton({key:'cancel',label:'Cancel', title:'', icon:'ui-icon-cross'},
                       this.editForm,'full',{display:'inline-block', margin:'0 35% 0 0'});
*/                       
        }
        
        this.onEditFormChange();
        // to EXTEND         
        
        //old way window.hWin.HEURIST4.ui.switchHintState('prefs_'+this._entityName, this.element, false);
        window.hWin.HEURIST4.ui.applyCompetencyLevel(-1, this.editForm); 
        
        this._afterInitEditForm_restoreGroupStatus();
        
        
        if(this.options.default_palette_class){
            var $dlg = this._getEditDialog(true);
            if($dlg){
                $dlg.parent().addClass(this.options.default_palette_class);
            }else{
                //this.element.addClass(this.options.default_palette_class);
            }
        }
    },
    
    //
    //restore status for accordions and tabs
    //
    _afterInitEditForm_restoreGroupStatus: function(){
        for (var dtID in this._keepTabsStatus) if(dtID>0) {
            var ele = this.editForm.find('div[data-group-dtid="'+dtID+'"]');
            if(ele.length>0){
                if(ele.tabs('instance')){
                    ele.tabs('option','active',this._keepTabsStatus[dtID]);
                }else if(ele.accordion('instance')){
                    ele.accordion('option','active',this._keepTabsStatus[dtID]);
                }
            }   
        }
        if(this._keepPos>0){
//console.log('scroll '+this._keepPos);            
            this.editForm.scrollTop(this._keepPos);  
        } 
    },

    //
    // show edit form in popup dialog or rigth-hand panel
    //
    addEditRecord: function(recID, is_proceed){
        
        if(this.options.edit_mode == 'none') return;
        
        this._initEditForm_step1(recID);
        
    },
    
    //
    // helper to get field from    this.options.entity.fields  
    //
    getEntityFieldIdx: function(dtID){
        if(this.options.entity && this.options.entity.fields){
                for(var idx in this.options.entity.fields){
                    if(this.options.entity.fields[idx]['dtID']==dtID){
                         return idx;       
                    }
                }
        }
        return -1;
    },
    
    //
    //
    //
    _triggerRefresh: function( type, recID ){
//console.log($(this.document).find('body').text().trim().substring(1,20));        
//$(this.document).trigger(window.hWin.HAPI4.Event.ON_STRUCTURE_CHANGE, { source:this.uuid, type:type, recID: recID });
//console.log('refresh '+type+'  '+recID);                
        window.hWin.HAPI4.triggerEvent(window.hWin.HAPI4.Event.ON_STRUCTURE_CHANGE, 
            { source:this.uuid, type:type, recID: recID });    
           
    }
});

