<?php
/**
* miradorViewer.php - Initialises and handles the Heurist Mirador viewer.
*
* It uses the Mirador v4 + MAE bundle from external/mirador4 when available.
* If the v4 bundle is missing, it can fall back to the older customised
* external/mirador3 viewer, and finally to the public Mirador distribution.
*
* For annotations, the Heurist database must define RT_IIIF_ANNOTATION.
* The viewer creates window.heuristMiradorConfig for the Mirador v4 bundle.
*
* Allowed public request parameters
* ---------------------------------
*
* db
*   Required. Heurist database name.
*
* manifest
*     Explicit IIIF Manifest identifier: either a managed RT_IIIF_MANIFEST
*     record ID or a registered Manifest file obfuscated ID.
* 
*     miradorViewer.php always opens this through the Heurist IIIF API:
*         /api/{db}/iiif/manifest/{manifest}?omit_annotation_pages=1
* 
*     For managed RT_IIIF_MANIFEST records, this returns the fully managed
*     Heurist Manifest.
* 
*     For registered Manifest files without a managed RT_IIIF_MANIFEST record,
*     DbIiifManifest::getManifestFileJson() controls the behaviour:
*         - v2 source Manifests are returned as original source Manifests;
*         - v3 source Manifests are returned as Heurist annotation-overlay
*           Manifests, with original annotation pages stripped/suppressed.
* 
*     To view the untouched original uploaded Manifest file, use the Heurist
*     file URL directly:
*         ?db={db}&file={manifestFileID} 
* 
*
* id
*   Record ID or registered file/url obfuscated ID.
*
*   If id is a positive integer, it is treated as a Heurist record ID.
*   The dynamic manifest is generated by record_output.php:
*       /hserv/controller/record_output.php?db={db}&format=iiif&q=ids:{id}
*
*   Exception: if the record is RT_IIIF_ANNOTATION, the viewer resolves the
*   annotation's parent media/manifest record and Canvas URI first. This special
*   behaviour is intentionally kept here, because a dynamic export of the
*   annotation record itself produces an empty manifest.
*
*   If id is not a positive integer, it is treated as an uploaded file
*   obfuscated ID. The dynamic manifest is generated by record_output.php:
*       /hserv/controller/record_output.php?db={db}&format=iiif&iiif_image={id}
*
* q
*   Heurist query used to generate a dynamic manifest through record_output.php:
*       /hserv/controller/record_output.php?db={db}&format=iiif&q={q}
*
* url
*   Direct Manifest URL. This is passed to Mirador unchanged, except for HTML
*   escaping at output time. It is useful for external manifests or diagnostics.
*
* preparedID
*   Short reference to prepared export/feed parameters created by exportMenu.js
*   for long queries or large ID lists. The parameters are restored and passed
*   to record_output.php with format=iiif.
*
* canvasUri
*   Optional Canvas URI to select when Mirador opens. This is viewer-only and is
*   not forwarded to record_output.php.
*
* annotation_scope / anno_scope
*   Optional annotation lookup scope for the internal Mirador viewer:
*       canvas   - show annotations targeting the same Canvas URL; default.
*       manifest - show annotations linked to the current managed Manifest
*                  context, when a Manifest record ID is known.
*
* Deprecated public parameters
* ----------------------------
* recID, iiif and iiif_image are intentionally no longer part of the public
* miradorViewer.php interface. Use id or manifest instead. iiif_image remains
* an internal parameter passed from this viewer to record_output.php.
*
* @project     Heurist academic knowledge management system
* @package     hclient\widgets\viewers
* @link        https://HeuristNetwork.org
* @copyright   (C) 2005-2023 University of Sydney, (C) 2024 onwards Heurist Network
* @license     https://www.gnu.org/licenses/gpl-3.0.txt GNU License 3.0
* @author      Artem Osmakov <osmakov@gmail.com>
* @author      Ian Johnson <ian.johnson.heurist@gmail.com>
* @since       6.0
*/

$dbname = @$_REQUEST['db'];
$idParam = trim((string)($_REQUEST['id'] ?? ''));
$manifestParam = trim((string)($_REQUEST['manifest'] ?? ''));
$directManifestUrl = trim((string)($_REQUEST['url'] ?? ''));
$readonly = filter_var($_REQUEST['readonly'] ?? $_REQUEST['ro'] ?? false, FILTER_VALIDATE_BOOLEAN);

$manifestRecID = 0;        // Known only for managed Manifest record context.
$sourceRecordId = 0;       // Passed to the annotation client as window.sourceRecordId.
$canvasUri = null;         // Initial Canvas selection for Mirador.
$baseUrl = null;
$system = null;
$preparedParams = null;
$resolvedIiifImageID = null; // Internal record_output.php iiif_image parameter.
$hideThumbs = false;

// Annotation lookup scope for the internal Mirador viewer.
// canvas   - show all annotations that target the same Canvas URL.
// manifest - show only annotations imported/created in the current Manifest context.
$annotationScope = strtolower(trim((string)(@$_REQUEST['annotation_scope'] ?: @$_REQUEST['anno_scope'] ?: 'canvas')));
if(!in_array($annotationScope, array('canvas', 'manifest'), true)){
    $annotationScope = 'canvas';
}

$validDatabaseName = is_string($dbname) && $dbname!=='' && !preg_match('[\W]', $dbname);
$idIsRecordID = preg_match('/^[1-9][0-9]*$/', $idParam) === 1;

// System initialisation is needed only for prepared parameters and numeric id
// resolution. Non-numeric id, manifest, q and url can be converted to a manifest
// URL without touching the database here.
$needsSystem = $validDatabaseName && (
    array_key_exists('preparedID', $_REQUEST) ||
    $idIsRecordID
);

if($needsSystem){

    require_once dirname(__FILE__).'/../../../autoload.php';

    $system = new hserv\System();
    if( ! $system->init($dbname, true, false) ){
        $system->errorExitApi(); // exits
    }

    $baseUrl = defined('HEURIST_BASE_URL') ? HEURIST_BASE_URL : null;

    if(array_key_exists('preparedID', $_REQUEST)){

        // preparedID is produced by exportMenu.js when q/rules/ids are too long
        // for a normal URL. Restore the prepared export-feed/export parameters
        // and later send them to record_output.php as a dynamic IIIF manifest.
        $params = $_REQUEST;
        $preferredType = array_key_exists('file', $params) ? 'export' : 'export-feed';
        $fallbackType = $preferredType === 'export' ? 'export-feed' : 'export';

        if(!\hserv\utilities\USystem::getPreparedParameters($system, $preferredType, $params)){
            $params = $_REQUEST;
            if(!\hserv\utilities\USystem::getPreparedParameters($system, $fallbackType, $params)){
                $system->errorExitApi(null, null, false);
            }
        }

        unset($params['preparedID'], $params['preparedMode'], $params['preparedType']);
        $params['db'] = $dbname;
        $_REQUEST = array_merge($_REQUEST, $params);
        $preparedParams = $params;
    }
}

if($system!=null && $idIsRecordID){

    // Numeric id normally means a record whose media should be exported by
    // record_output.php. However, annotation records need special handling:
    // exporting the annotation record itself produces an empty manifest, so the
    // viewer resolves the parent media/manifest record and target Canvas here.
    $sourceRecordId = intval($idParam);

    if($system->defineConstant('RT_IIIF_ANNOTATION')){
        $system->defineConstant('RT_IIIF_MANIFEST');
        $system->defineConstant('DT_URL');

        $res = recordSearchByID($system, $sourceRecordId, false, 'rec_ID,rec_RecTypeID');
        $mysqli = $system->getMysqli();

        if(is_array($res) && intval(@$res['rec_RecTypeID']) === RT_IIIF_ANNOTATION){

            // Annotation record case:
            //   1. Find the parent record that carries the registered IIIF
            //      media/manifest file.
            //   2. Read DT_URL from the annotation as the Canvas URI.
            //   3. Generate the Mirador manifest from the parent file rather
            //      than from the annotation record itself.
            $query = 'SELECT dtl_RecID, ulf_ObfuscatedFileID '
                .' FROM recLinks, recDetails, recUploadedFiles '
                .' WHERE rl_SourceID='.$sourceRecordId
                .' AND dtl_RecID=rl_TargetID '
                .' AND dtl_UploadedFileID=ulf_ID '
                .' AND (ulf_PreferredSource="iiif" OR ulf_OrigFileName="'.ULF_IIIF.'")';

            $row = mysql__select_row($mysqli, $query);

            if($row!=null && defined('DT_URL')){

                $query = 'SELECT dtl_Value FROM recDetails WHERE '
                    .' dtl_RecID='.$sourceRecordId.' AND dtl_DetailTypeID='.DT_URL;
                $canvasUri = mysql__select_value($mysqli, $query);

                $sourceRecordId = intval($row[0]);
                $resolvedIiifImageID = (string)$row[1];

            }else{
                exit('Unable to resolve parent IIIF media or manifest for annotation record id='.$idParam);
            }

        }else{

            // Normal record case:
            // Keep the record ID as the dynamic manifest source. If annotations
            // already target one of its canvases, select the most frequently used
            // Canvas URI when Mirador opens.
            if(defined('RT_IIIF_MANIFEST') && is_array($res)
                && intval(@$res['rec_RecTypeID']) === RT_IIIF_MANIFEST){
                $manifestRecID = $sourceRecordId;
            }

            if(defined('DT_URL')){
                $query = 'SELECT dtl_Value, count(*) as cnt FROM recDetails, recLinks, Records '
                    .' WHERE rl_TargetID='.$sourceRecordId
                    .' AND rec_ID=rl_SourceID AND rec_RecTypeID='.RT_IIIF_ANNOTATION
                    .' AND dtl_RecID=rec_ID '
                    .' AND dtl_DetailTypeID='.DT_URL
                    .' GROUP BY dtl_Value ORDER BY cnt DESC';

                $row = mysql__select_row($mysqli, $query);
                if(is_array($row) && @$row[0]!=null){
                    $canvasUri = $row[0];
                }
            }
        }
    }
}

if($baseUrl==null){

    $https = (isset($_SERVER['HTTPS']) &&
                    ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1) ||
                    isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &&
                    $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https');

    $baseUrl = ($https ? 'https://' : 'http://').
            (!empty($_SERVER['REMOTE_USER']) ? $_SERVER['REMOTE_USER'].'@' : '').
            (isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : ($_SERVER['SERVER_NAME'].
            ($https && $_SERVER['SERVER_PORT'] === 443 ||
            $_SERVER['SERVER_PORT'] === 80 ? '' : ':'.$_SERVER['SERVER_PORT'])));

    $path = trim($_SERVER['SCRIPT_NAME']);
    $path = trim($path, '/');
    $parts = explode('/', $path);
    $version = $parts[0] ?? '';
    if(!($version === 'heurist'
            || preg_match('/^h7-[A-Za-z0-9_-]+$/', $version) === 1)){
        $version = 'h7-alpha';
    }

    $baseUrl = $baseUrl.'/'.$version.'/';
}

function appendQueryParam($url, $name, $value){
    if($name==='' || strpos($url, $name.'=')!==false){
        return $url;
    }
    $sep = (strpos($url, '?')===false) ? '?' : '&';
    return $url.$sep.rawurlencode($name).'='.rawurlencode((string)$value);
}

function buildRecordOutputIiifUrl($baseUrl, $params){
    $params['format'] = 'iiif';
    return $baseUrl.'hserv/controller/record_output.php?'.http_build_query($params);
}

function findMirador4DistAsset($distPath, $extension){
    //$assetsDir = rtrim($distPath, DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.'assets';
    //if(!is_dir($assetsDir)){
    //    return null;
    //}
    
    if(!is_dir($distPath)){
        return null;    
    }

    $files = glob($distPath.DIRECTORY_SEPARATOR.'*.'.$extension);
    if(!is_array($files) || count($files)===0){
        return null;
    }

    usort($files, function($a, $b){
        $aBase = basename($a);
        $bBase = basename($b);
        $aIsIndex = strpos($aBase, 'index') === 0 ? 0 : 1;
        $bIsIndex = strpos($bBase, 'index') === 0 ? 0 : 1;
        if($aIsIndex !== $bIsIndex){
            return $aIsIndex <=> $bIsIndex;
        }
        return strcmp($aBase, $bBase);
    });

    return basename($files[0]); // 'assets/'.
}

function jsonForScript($value){
    return json_encode(
        $value,
        JSON_UNESCAPED_SLASHES
        | JSON_UNESCAPED_UNICODE
        | JSON_HEX_TAG
        | JSON_HEX_AMP
        | JSON_HEX_APOS
        | JSON_HEX_QUOT
    );
}

if($directManifestUrl !== ''){

    // Direct manifest URL case:
    // Use the caller-supplied manifest URL unchanged. This supports external
    // manifests and diagnostic URLs that should not be normalised by Heurist.
    $url = $directManifestUrl;

}elseif($manifestParam !== ''){

    // Explicit manifest case:
    // The caller is asking for a known IIIF Manifest identity. Use the canonical
    // Heurist IIIF API route instead of the dynamic recordset exporter.
    $url = $baseUrl.'api/'.rawurlencode($dbname)
        .'/iiif/manifest/'.rawurlencode($manifestParam)
        .'?omit_annotation_pages=1';
        

    if(preg_match('/^[1-9][0-9]*$/', $manifestParam)){
        $manifestRecID = intval($manifestParam);
        $sourceRecordId = $manifestRecID;
    }

}elseif(is_array($preparedParams)){

    // Prepared query/resultset case:
    // exportMenu.js stores large q/rules/ids values under preparedID. Restore
    // those parameters and pass them to record_output.php, which knows how to
    // generate a dynamic IIIF manifest from a resultset.
    unset($preparedParams['canvasUri'], $preparedParams['annotation_scope'], $preparedParams['anno_scope']);
    unset($preparedParams['id'], $preparedParams['manifest'], $preparedParams['url']);
    unset($preparedParams['recID'], $preparedParams['iiif'], $preparedParams['iiif_image']);

    $preparedParams['db'] = $dbname;
    $url = buildRecordOutputIiifUrl($baseUrl, $preparedParams);

}elseif($resolvedIiifImageID !== null && $resolvedIiifImageID !== ''){

    // Annotation record resolution case:
    // id was an RT_IIIF_ANNOTATION record. Generate the manifest from the
    // resolved parent media/manifest file and open the annotation's Canvas URI.
    $url = buildRecordOutputIiifUrl($baseUrl, array(
        'db' => $dbname,
        'iiif_image' => $resolvedIiifImageID
    ));

}elseif($idParam !== ''){

    if($idIsRecordID){

        // Numeric id case:
        // Treat id as a normal Heurist record ID and ask record_output.php to
        // generate a dynamic manifest from q=ids:{recordID}.
        $url = buildRecordOutputIiifUrl($baseUrl, array(
            'db' => $dbname,
            'q' => 'ids:'.$idParam
        ));

    }else{

        // Non-numeric id case:
        // Treat id as an uploaded file obfuscated ID. iiif_image is not a public
        // miradorViewer.php parameter anymore, but it remains the internal
        // record_output.php parameter for single-file dynamic manifests.
        $url = buildRecordOutputIiifUrl($baseUrl, array(
            'db' => $dbname,
            'iiif_image' => $idParam
        ));
        $hideThumbs = true;
    }

}elseif(@$_REQUEST['q']){

    // Query case:
    // Pass the Heurist query directly to record_output.php. This is the normal
    // dynamic manifest path for a resultset.
    $url = buildRecordOutputIiifUrl($baseUrl, array(
        'db' => $dbname,
        'q' => $_REQUEST['q']
    ));

}else{
    exit('Need to define manifest, id, q, url or preparedID');
}

if(@$_REQUEST['canvasUri']){
    // Viewer-only override. It selects the initial Canvas in Mirador and is not
    // forwarded to record_output.php.
    $canvasUri = $_REQUEST['canvasUri'];
}

if(strpos($url, 'hserv/controller/record_output.php')!==false){
    // Dynamic manifests should normally omit embedded AnnotationPage links.
    // The custom Mirador integration asks the Heurist annotation endpoint
    // directly, avoiding duplicate annotation loading paths.
    $url = appendQueryParam($url, 'omit_annotation_pages', '1');
}

$manifest_url = str_replace('&amp;','&',htmlspecialchars($url));

$mirador4DistPath = dirname(__FILE__).'/../../../external/mirador4/dist';
$mirador4DistUrl = '../../../external/mirador4/dist/';
$mirador4JsAsset = findMirador4DistAsset($mirador4DistPath, 'js');
$mirador4CssAsset = findMirador4DistAsset($mirador4DistPath, 'css');
$use_mirador4_bundle = $mirador4JsAsset !== null;

$use_custom_mirador3 = !$use_mirador4_bundle
    && file_exists(dirname(__FILE__).'/../../../external/mirador3/dist/main.js');
?>
<!DOCTYPE html>
<html lang="en">
<head>

<meta name="robots" content="noindex,nofollow">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Lang" content="en">
<meta name="author" content="">
<meta name="description" content="">
<meta name="keywords" content="">
<title>Heurist Mirador Viewer</title>
<?php
if($use_mirador4_bundle){
    if($mirador4CssAsset !== null){
        print '<link rel="stylesheet" href="'.$mirador4DistUrl.htmlspecialchars($mirador4CssAsset).'">'."\n";
    }
}elseif($use_custom_mirador3){
    print '<base href="../../../external/mirador3/"/>';
}else{
?>
<script src="https://unpkg.com/mirador@latest/dist/mirador.min.js"></script>
<!-- By default uses Roboto font. Be sure to load this or change the font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
<?php
}
?>
<style>
html,
body {
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
  min-width: 100%;
  min-height: 100%;
  overflow: hidden;
}

body {
  position: relative;
}

#demo {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  min-width: 100%;
  min-height: 100%;
}
</style>
</head>
<body>
<div id="demo"></div>
<script>
<?php
$annotationEndpoint = null;
if (!preg_match('[\W]', $dbname)){
    $annotationEndpoint = $baseUrl.'api/'.$dbname.'/annotations';
?>
    window.annotationScope = <?php echo jsonForScript($annotationScope);?>;
    window.endpointURL = <?php echo jsonForScript($annotationEndpoint);?>;
    window.manifestUrl = <?php echo jsonForScript(str_replace('&amp;', '&', $manifest_url));?>;
    window.heuristMiradorConfig = {
        id: 'demo',
        manifestUrl: window.manifestUrl,

        db: <?php echo jsonForScript($dbname);?>,
        recID: <?php echo intval($manifestRecID ?: $sourceRecordId);?>,
        q: <?php echo jsonForScript((string)($_REQUEST['q'] ?? ''));?>,
        iiifImage: <?php echo jsonForScript((string)($resolvedIiifImageID ?? (!$idIsRecordID ? $idParam : '')));?>,

        endpointUrl: window.endpointURL,
        annotationServerUrl: window.endpointURL,
        annotationMode: 'heurist',

        readonly: <?php echo $readonly ? 'true' : 'false';?>,
        userLabel: 'Heurist user',

        canvasId: <?php echo jsonForScript((string)($canvasUri ?? ''));?>,
        sourceRecordId: <?php echo intval($sourceRecordId);?>,
        hideThumbs: <?php echo $hideThumbs?'true':'false';?>,
        annotationScope: window.annotationScope,

        rewriteLocalIiifUrls: false,
        heuristCanonicalBaseUrl: null
    };
<?php
}
?>
    window.hideThumbs = <?php echo $hideThumbs?'true':'false';?>;
    window.sourceRecordId = <?php echo intval($sourceRecordId);?>;
    window.runManually = true;
</script>
<?php
if($use_mirador4_bundle){
?>
<script type="module" src="<?php echo $mirador4DistUrl.htmlspecialchars($mirador4JsAsset);?>"></script>
<?php
}elseif($use_custom_mirador3){
      if($canvasUri==null){
          $canvasUri = '';
      }
//see https://github.com/ProjectMirador/mirador/blob/master/src/config/settings.js
?>
<script src="dist/main.js"></script>
<script type="text/javascript">
    function renderMiradorWhenReady(config) {
        const el = document.getElementById('demo');

        function hasSize() {
            return el && el.clientWidth > 50 && el.clientHeight > 50;
        }

        function render() {
            if (typeof window.renderMirador === 'function') {
                window.renderMirador(config);
            }
        }

        if (hasSize()) {
            render();
        } else {
            requestAnimationFrame(function retry() {
                if (hasSize()) {
                    render();
                } else {
                    requestAnimationFrame(retry);
                }
            });
        }
    }

    var config = {
        id: 'demo',
        windows: [{
            canvasId: '<?php echo htmlspecialchars($canvasUri);?>',
            imageToolsEnabled: true,
            imageToolsOpen: false,
            manifestId: window.manifestUrl,
            sideBarOpen: true,
            highlightAllAnnotations: true,
            sideBarPanel: 'annotations'
        }],
        theme: {
            palette: {
                primary: {
                    main: '#1967d2',
                },
            },
        },
    };

    if(window.hideThumbs !==true){
        config['windows'][0]['thumbnailNavigationPosition'] = 'far-bottom';
    }

    renderMiradorWhenReady(config);

</script>
<?php
}else{
?>
<script type="text/javascript">
var mirador = Mirador.viewer({
  "id": "demo",
  "windows": [
    {
      "id": "uniqueid",
      //"canvasIndex": "1",
      "manifestId": "<?php echo $manifest_url;?>"
      <?php echo $hideThumbs?'':',"thumbnailNavigationPosition": "far-bottom"';?>
    }
  ]
});

</script>
<?php
}
?>
</body>
</html>