/**
* @package     Heurist academic knowledge management system
* @link        http://HeuristNetwork.org
* @copyright   (C) 2005_2020 University of Sydney
* @author      Artem Osmakov   <artem.osmakov@sydney.edu.au>
* @license     http://www.gnu.org/licenses/gpl_3.0.txt GNU License 3.0
* @version     4.0
*/

/*
* Licensed under the GNU License, Version 3.0 (the "License"); you may not use this file except in compliance
* with the License. You may obtain a copy of the License at http://www.gnu.org/licenses/gpl_3.0.txt
* Unless required by applicable law or agreed to in writing, software distributed under the License is
* distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied
* See the License for the specific language governing permissions and limitations under the License.
*/

regional['ru'] = {
    language: 'Русский',
    'Databases': 'Базы данных',
    'Design database': 'Настройка БД',
    'Import data': 'Импорт данных',
    'Files in situ': 'Из директории на сервере',
    'Report bug': 'Отчет об ошибке',
    'About': 'О системе...',
    'Confirmation':'Подтверждение',
    'Info':'Информация',

    'Register': 'Регистрация',
    'Registration': 'Регистрация',
    'Heurist Login': 'Войти',
    'Please log in': 'Зарегистрируйтесь, чтобы использовать все возможности Heurist',
    'Please contact to register':'Для получения регистрации свяжитесь с администратором',
    'Log out' : 'Выйти',
    'Manage': 'Управление',
    'Sort': 'Порядок',
    'Search': 'Поиск',
    'Search result': 'Результаты поиска',
    'Merge': 'Объеденить',
    'Rate': 'Оценить',
    'Relate to': 'Связать с',
    'Access': 'Доступ',
    'Notify': 'Сообщить',
    'Embed / link': 'Код ссылки',
    'Export': 'Экспорт',
    'Import': 'Импорт',


    'Username': 'Имя пользователя',
    'Password': 'Пароль',
    'Remember me': 'Запомнить меня',
    'Forgotten your password?': 'Забыли пароль?',
    'Click here to reset it': 'Нажмите тут чтобы восстановить',
    'Enter your username OR email address below and a new password will be emailed to you.':'Введите имя пользователя или адрес эл.почты и новый пароль будет послан Вам',
    'Reset password': 'Восстановить пароль',
    'Email to':'Контакт',
    'User information has been saved successfully':'Информация о пользователе сохранена',

    'Database': 'База Данных',
    'Select database': 'Выберите базу данных',
    'My User Info' : 'Мои данные',
    'My Groups' : 'Мои группы',
    'Manage Tags' : 'Ярлыки',
    'Tags' : 'Ярлыки',
    'Manage Files': 'Файлы',
    'Manage Reminders' : 'Напоминания',
    'Set Ratings' : 'Присвоить оценку',
    'No Rating': 'Нет оценки',

    'Name': 'Название',
    'Description': 'Описание',
    'Size': 'Размер',
    'Type': 'Тип',

    'search': 'искать',
    'all records': 'среди всех записей',
    'my bookmarks': 'среди закладок',
    'in current': 'в текущем',
    'search option': 'варианты поиска',
    'search assistant': 'помощник',
    'Any record type': 'Любой тип записи',
    'Any field type': 'Любое тип поля',
    'Record type': 'Тип записи',
    'Field': 'Поле',
    'Contains': 'Содержит',
    'Is': 'Значение',
    'Sort By': 'Сорт',
    'Sort Ascending': 'По убыванию',
    'fields':'поля',

    'add': 'добавить',
    'Add New Record' : 'Добавить запись',
    'tags': 'ярлыки',
    'share': 'доступ',
    'more': 'ещё',
    'edit': 'править',
    'options': 'опции',

    'by name': 'по имени',
    'by usage': 'по использованию',
    'by date': 'по дате',
    'by size': 'по размеру',
    'by type': 'по типу',
    'marked': 'отмеченные',

    'list':'список',
    'icons':'иконки',
    'thumbs':'миниатюры',
    'thumbs3':'превью',

    'first':'первая',
    'previous':'предыдущая',
    'next':'следующая',
    'last':'последняя',
    'records per request':'записей в запросе',

    'Manage tags': 'Управление ярлыками',
    'Create new tag': 'Создать ярлык',
    'Add Tag': 'Создать ярлык',
    'Edit Tag': 'Редактировать ярлык',
    'Define new tag that replaces old ones': 'Определите новый ярлык который заменит старые',
    'Length of tag must be more than 2.': 'Ярлык должен быть больше чем два символа',
    'Assign selected tags': 'Присвоить отмеченные ярлыки',
    'Personal Tags':'Личные ярлыки',
    'Delete selected tags': 'Удалить отмеченные ярлыки',



    'Preferences' : 'Настройки',
    'Layout configuration file': 'Файл конфигурации интерфейса',
    'Language':'Язык',
    'Theme':'Тема/стили',
    'Open edit in new window':'Редактировать в новом окне',
    'When exiting record edit, prompt for tags if no tags have been set':'Перед сохранением предлагать определить ярлыки',
    'Reload page to apply new settings?':'Перезагрузить страницу чтобы увидеть изменения?',

    'Click to save current search':'Сохранить поиск как ссылку',
    'My Bookmarks': 'Мои закладки',
    'My Searches': 'Мои запросы',
    'Predefined searches': 'Рекомендуемые запросы',
    'Recent changes': 'Свежие записи',
    'All records': 'Все записи',
    'All (date order)': 'Все (сорт по дате)',
    'Edit saved search': 'Редактировать поиск',
    'Delete saved search': 'Удалить сохраненный поиск',
    'Manage Saved Searches': 'Управление сохр.поисками',
    'Create new saved search': 'Создать поиск',

    'Database Summary': 'Сводка базы данных',
    'RuleSets': 'Зависимости',


    'Delete? Please confirm': 'Удалить? Подвтердите',

    'select record': 'выберите запись',

    'Leave blank for no change': 'Оставьте пустым чтобы не менять пароль',
    'Passwords are different': 'Пароли различны',
    'Wrong email format': 'Неправильный формат адреса почты',
    'Wrong user name format': 'Недопустимы формат для имени пользовтеля',
    'Wrong password format': 'Недопустимый формат для пароля',
    'Missing required fields': 'Не опрделены обязательные поля',
    'length must be between': 'длина должна быть между',
    'required field': 'обязательное поле',
    
    //========================  2021_07_08 =======================

    //common words
    'Close': 'Закрыть',
    'Settings': 'Настройки',
    'Help': 'Помощь',
    'Error': 'Ошибка',
    'records': 'записей',
    'loading': 'загрузка',
    'preparing': 'подготовка',
    'explanations': 'объяснения',
    'Show data': 'Показать данные',
    'Actions': 'Операции',
    'Embed': 'Внедрить',
    'Clear': 'Очистить',
    'Warning': 'Внимание',    
    'Cancel': 'Отмена',
    'Record Info': 'Данные записи',
    'Add': 'Добавить',
    'Assign': 'Присвоить',
    'Apply': 'Применить',
    'Abort': 'Прервать',
    'Define': 'Определить',
    'Edit': 'Править',
    'Delete': 'Удалить',
    'Create': 'Создать',
    'Confirm': 'Подтверждение',
    'Proceed': 'Продолжить',
    'Continue': 'Продолжить',
    'Go': 'Начать',
    'Yes': 'Да',
    'OK': 'OK',
    'No': 'Нет',
    'Save': 'Сохранить',
    'Save data': 'Сохранить данные',
    'Ignore and close': 'Игнорировать и закрыть',
    'Drop data changes': 'Отменить изменения',
    'Manage': 'Управление',
    'Select': 'Выбор',
    'Configure': 'Конфигурация',
    
    'Show context help': 'Контекстная помощь',
    'Heurist context help': 'Контекстная помощь',
    'Sorry context help was not found': 'Помощь не найдена',
    
    //main menu 
    'Admin': 'Админ',
    'Design': 'Дизайн',
    'Populate': 'Наполнение',
    'Explore': 'Искать',
    'Publish': 'Публикация',
    'Profile': 'Профиль',
        
    add_new_record: 'Новая запись', //header for New record
    add_new_record2: 'Ввод', // prefix before rectype name
    
    //explore menu
    'Filters': 'Фильтры',
    'Recent': 'Недавние',
    'All': 'Все',
    'Entities': 'Типы записей',
    'Saved filters': 'Каталог фильтров',
    'Build': 'Создать',
    'Filter builder': 'Условия поиска',
    'Facets builder': 'Многогранный поиск',
    'Save filter': 'Добавить фильтр',
    'Advanced': 'Дополнительно',
    'Rules': 'Каскадный поиск',
    'Favourites': '',
    
    //admin menu
    'Database': 'База данных',
        menu_database_browse: 'Открыть',
        menu_database_create: 'Новая',
        menu_database_clone: 'Клонировать',
        menu_database_delete: 'Удалить',
        menu_database_clear: 'Очистить',
        menu_database_rollback: 'Восстановить',
        menu_database_register: 'Зарегистрировать',
        menu_database_properties: 'Свойства',
        
        menu_database_browse_hint:'Найти и открыть другую базу Heurist в новом окне',
        menu_database_create_hint:'Созадть новую базу данных _ все основные элементы структуры будут добавлены автоматически',
        menu_database_clone_hint:'Создать копию текущей базы со всеми данными, загружеными файлами, шаблонами итп',
        menu_database_delete_hint:'Удалить текущую базу полностью _ не может быть отменено, хотя данные будут скопированы в дамп и могут быть восстановлены сисадмином',
        menu_database_clear_hint:'Clear all data (records, values, attached files) from the current database. Database structure _ record types, fields, terms, constraints _ is unaffected',
        menu_database_rollback_hint:'Selectively roll back the data in the database to a specific date and time',
        menu_database_register_hint:'Зарегистировать эту базу в Heurist Reference Index _ это сделает доступным импорт элементов структуры (но не данных) в других базах',
        menu_database_properties_hint:'Редактировать описание базы данных и определить некторые глобальные установить . Recommended to provide a self_documenting database',
        
    'Manage Users': 'Пользователи',
        menu_profile_groups: 'Группы',
        menu_profile_users: 'Пользователи',
        menu_profile_import: 'Импорт профиля',
        menu_profile_groups_hint: 'List of groups you are member of',
        menu_profile_users_hint: 'Add and edit database users, including authorization of new users. Use Manage Workgroups to allocate users to workgroups and define roles within workgroups',
        menu_profile_import_hint: 'Import users one at a time from another database on the system, including user name, password and email address _ users are NOT assigned to workgroups',
    'Utilities': 'Утилиты',
        menu_profile_files: 'Управление файлами',
        menu_profile_preferences: 'Настройки профиля',
        menu_structure_verify: 'Проверка целостности данных',
        menu_structure_duplicates: 'Найти повторения',
        menu_manage_rectitles: 'Обновить заголовки',
        menu_manage_calcfields: 'Обновить вычисляемые поля',
        menu_interact_log: 'Interaction log',
        menu_profile_files_hint: 'Управление загружеными файлами и удаленными медиа ресурсами',
        menu_profile_preferences_hint: 'Показать и редактировать настройки профиля',
        menu_structure_verify_hint: 'Найти ошибки в структуре базы (неправильные типы записей, полей и словарей) и записи с неправильной структурой и ошибными данными (ссылки, пропущеные данные итп)',
        menu_structure_duplicates_hint: 'Нечеткий поиск для определения записей которые могут содержать идентичные данные',
        menu_manage_rectitles_hint: 'Обновить заголовки для всех записей',
        menu_interact_log_hint: 'Download the interaction log',
    'Server Manager': 'Управление сервером',
        menu_admin_server: 'Базы данных',
        menu_admin_server_hint: 'Операции для всех баз данных на этом сервере',
        
    //design menu
    'Modify': 'Изменить структуру',
        menu_structure_rectypes: 'Типы записей',
        menu_structure_vocabterms: 'Словари',
        menu_structure_fieldtypes: 'Базовые поля',
        menu_structure_import: 'Импорт шаблонов',
        menu_structure_workflowstages: 'Стадии работы',
        menu_lookup_config: 'External lookups', // needs replacing
        menu_structure_summary: 'Визуализация',
        menu_structure_refresh: 'Перегрузить структуру',
    
        menu_structure_rectypes_hint: 'Добавить или модифицировать типы записей',
        menu_structure_vocabterms_hint: 'Добавить или модифицировать словари',
        menu_structure_fieldtypes_hint: 'Редактировать определения базовых полей используемых в типах записей (часто одновременно в нескольких типах)',
        menu_structure_import_hint: 'Выборочно импортировать типы записей, базовые поля и словари из других баз Heurist',
        menu_structure_summary_hint: 'Визуализация внутренних связей между типами записей в базе (указателей и отношений)',
        menu_structure_refresh_hint: 'Очистить и перегрузить структру базы Heurist в вашем браузере. Используйтк чтобы обновить списки и селекторы в случае если изменени не отображаются',
    
    'Setup': 'Настройки',
        menu_manage_dashboards: 'Панель ярлыков',
        menu_manage_archive: 'Архивировать базу',
        menu_manage_dashboards_hint: 'Определить ярлыки для быстрого доступа к функциям',
        menu_manage_archive_hint: 'Архивировать все данные как SQL дамп и XML файлы, а также загруженые файлы, шаблоны и документы, в ZIP архив который моэет быть скачен по ссылке',

    'Download': 'Скачать',
        menu_manage_structure_asxml: 'Структуру как XML',
        menu_manage_structure_assql: 'Структуру как Text',
        menu_manage_structure_asxml_hint: 'Список определений типов записи и полей в XML формате (HML - Heurist Markup Language)',
        menu_manage_structure_assql_hint: 'Список определений типов записи и полей в форме для использования SQL выражениях',
        
    //populate menu
    'Upload Files': 'Загрузить файлы',
        menu_import_csv: 'Текст / CSV',
        menu_import_zotero: 'Zotero библиография',
        menu_import_xml: 'Heurist XML/JSon',
        menu_import_kml: 'KML',
        menu_import_get_template: 'Скачать шаблон (XML)',
        menu_import_csv_hint: 'Import data from delimited text file. Supports matching, record creation, record update.',
        menu_import_zotero_hint: 'Synchronise with a Zotero web library _ new records are added to Heurist, existing records updated',
        menu_import_xml_hint: 'Import records from another database',
        menu_import_kml_hint: 'Import KML files (geographic data in WKT can be imported from CSV &amp; tab delimited files)',
        menu_import_get_template_hint: 'Get XML template that describes database structure', 
    'Media Files': 'Медиа файлы',
        menu_files_upload: 'Загрузить медиа файлы',
        menu_files_index: 'Проиндексировать',
        menu_files_upload_hint: 'Upload multiple files and/or large files to scratch space or image directories, delete and rename uploaded files',
        menu_files_index_hint: 'Index files on the server and create multimedia records for them (reads and creates FieldHelper manifests)',
    
    //publish menu
    'Website': 'Веб сайт',
        menu_cms_create: 'Создать',
        menu_cms_edit: 'Править',
        menu_cms_view: 'Просмотр',
        menu_cms_embed: 'Отдельная веб страница',
        menu_cms_create_hint: 'Create a new CMS website, stored in this database, with widgets to access data in the database',
        menu_cms_edit_hint: 'Edit a CMS website defined in this database',
        menu_cms_view_hint: 'View a CMS website defined in this database',
        menu_cms_embed_hint: 'Create or edit a standalone web page in this database. May contain Heurist widgets. Provides code to embed page in an external iframe.',
        
        'Website Editor': 'Редактор вебсайта',
        'Sitewide Settings': 'Настройки сайта',
        'Current Page': 'Текущая страница',
       'Page Editor': 'Редактор страницы',
       
    'Standalone web page': 'Отдельная веб страница',
        menu_cms_create_page: 'Создать',
        menu_cms_edit_page: 'Править',
        menu_cms_view_page: 'Просмотр',
        
    'Export': 'Экспорт',
        menu_export_csv: 'CSV',
        menu_export_hml_resultset: 'XML',
        menu_export_json: 'JSON',
        menu_export_geojson: 'GeoJSON',
        menu_export_kml: 'KML',
        menu_export_gephi: 'GEPHI',
        menu_export_csv_hint: 'Export records as delimited text (comma/tab), applying record type',
        menu_export_hml_resultset_hint: 'Generate HML (Heurist XML format) for current set of search results (current query + expansion)',
        menu_export_json_hint: 'Generate JSON for current set of search results (current query)',
        menu_export_geojson_hint: 'Generate GeoJSON_T for current set of search results (current query)',
        menu_export_kml_hint: 'Generate KML for current set of search results (current query + expansion)',
        menu_export_gephi_hint: 'Generate GEPHI for current set of search results (current query + expansion)',
    
    'Safeguard': 'Резервная копия',
        
    //My profile menu
    menu_profile_tags: 'Управления тегами',
    menu_profile_reminders: 'Управление напоминаниями',
    menu_profile_info: 'Мой профиль',
    menu_profile_logout: 'Выход',
    menu_profile_tags_hint: 'Удаление, модификация, переименование ваших личных и групповых тегов (ярлыков)',
    menu_profile_reminders_hint: 'Просмотр и удаления автоматических сообщений/ссылок на ваши записи',
    menu_profile_info_hint: 'Информация о вашем пользовательском профиле',
    menu_profile_logout_hint: '',
        
    //HELP menu
    HELP: 'ПОМОЩЬ',
        menu_help_online: 'Документация',
        menu_help_website: 'Heurist Network вебсайт',
        menu_help_online_hint: 'Исчерпывающая помощь и документация по Heurist',
        menu_help_website_hint: 'Heurist Network вебсайт - основной источник  информации, услуг и контактов', 
    CONTACT: 'КОНТАКТЫ',
        menu_help_bugreport: 'Отчет об ошибке / запрос новых функций',
        menu_help_emailteam: 'Команда Heurist',
        menu_help_emailadmin: 'Системны администратор',
        menu_help_acknowledgements: 'Признательности',
        menu_help_about: 'О приложении',
        menu_help_bugreport_hint: 'Послать email to the Heurist team such as additional bug information, comments or new feature requests',
        menu_help_emailteam_hint: '',
        menu_help_emailadmin_hint: 'Послать email to the System Adminstrator for this installaton of Heurist - typically for probelms with this installation',
        menu_help_acknowledgements_hint: '',
        menu_help_about_hint: 'Версия, Авторы, Права, Лицензия',
    
    menu_subset_set: 'Подмножество',
    menu_subset_set_hint: 'Сделать текущий поиск активным - все последующие поиски будут проходить в этом подмножестве записей',
    'Click to revert to whole database': 'Нажмите чтобы сбросить подмножество и искать по всей базе',
    'SUBSET ACTIVE': 'ПОДМНОЖЕСТВО',
    'Current subset': 'Активно',
    
    //END main menu
    
    //resultList --------------------
    
    'Selected': 'Отмечено',
        menu_selected_select_all: 'Отметить все',
        menu_selected_select_all_hint: 'Отметить все записи на странице',
        menu_selected_select_none: 'Снять отметки',
        menu_selected_select_none_hint: '',
        menu_selected_select_show: 'Открыть как поиск',
        menu_selected_select_show_hint: 'Открыть отмеченые записи в новом окне',
        menu_selected_tag: 'Тег (ярлык)',
        menu_selected_tag_hint: 'Присвоить или удалить теги для отмеченых записей',
        menu_selected_rate: 'Оценить',
        menu_selected_rate_hint: 'Присвоить оценку (рейтинг)для отмеченых записей',
        menu_selected_bookmark: 'Избранные',
        menu_selected_bookmark_hint: 'Добавить отмеченые записи в "Избранное"',
        menu_selected_unbookmark: 'Отменить избранность',
        menu_selected_unbookmark_hint: 'Удалить отмеченые записи из "Избранное"',
        menu_selected_merge: 'Объеденить',
        menu_selected_merge_hint: 'Определить повторение данных и объеденить записи',
        menu_selected_delete: 'Удалить',
        menu_selected_delete_hint: 'Удалить отмеченые записи',
    'Collected': 'Выбрано',
    'Collect': 'Выбрано',
        menu_collected_add: 'Добавить',
        menu_collected_add_hint: 'Отметь записи и добавь в выбранные (коллекцию)',
        menu_collected_del: 'Убрать',
        menu_collected_del_hint: 'Отметьте записи и удалите из выбранных (коллекции)',
        menu_collected_clear: 'Очистить все',
        menu_collected_clear_hint: 'Убрать все записи из выбранных. Очистить коллекцию',
        menu_collected_save: 'Сохранить',
        menu_collected_save_hint: 'Сохранить коллекцию как фильтр',
        menu_collected_show: 'Как поиск',
        menu_collected_show_hint: 'Показать коллекцию как результат поиска',
            collection_limit: 'The number of selected records is above the limit in ',
            collection_select_hint:  'Отметьте по крайней одну запись для добавления в коллекцию',
            collection_select_hint2: 'Отметьте по крайней одну запись для удаления из коллекции',
            collection_url_hint: 'Collections are saved as a list of record IDs. The URL generated by this collection would exceed the maximum allowable URL length by of 2083 characters. Please save the current collection as a saved search (which allows a much larger number of records), or add fewer records.',
    
    'Recode': 'Изменить',
        menu_selected_value_add: 'Добавить поле',
        menu_selected_value_add_hint: 'Добавить значение поля во все отобранные записи (отмеченные или по типу данных)',
        menu_selected_value_replace: 'Заменить поле',
        menu_selected_value_replace_hint: 'Заменить значение поля в отобранных записях',
        menu_selected_value_delete: 'Удалить поле',
        menu_selected_value_delete_hint: 'Удалить поле в отобранных записях',
        menu_selected_add_link: 'Связь или отношение',
        menu_selected_add_link_hint: 'Добавить связь или создать новое отношение между записями',
        menu_selected_rectype_change: 'Изменить тип данных',
        menu_selected_rectype_change_hint: 'Изменить тип данных для отобранных записей',
        menu_selected_extract_pdf: 'Текст из PDF',
        menu_selected_extract_pdf_hint: 'Извлечь текст из PDF файла (эксперемент)',
    'Shared': 'Доступ',
        menu_selected_notify: 'Ссылки',
        menu_selected_notify_hint: 'Отправить ссылки по email на отмеченые записи',
        menu_selected_email: 'Рассылка',
        menu_selected_email_hint: 'Отправка почты по реквизитам взятым из записи',
        menu_selected_ownership: 'Владелец / Видимость',
        menu_selected_ownership_hint: 'Установить владельца (группу или профиль который может редактировать записи) и параметры видимости (доступа) к записям',
    'Reorder': 'Сортировка',
    menu_reorder_hint: 'Вручную отсортируйте текущий результат и сохраните как фильтр',
    menu_reorder_title: 'Перетаскивайте записи вверх-вниз, затем сохраните этот сортированый набор записей как фильтр',
    menu_reorder_save: 'Сохранить набор как фильтр',
    
    //
    resultList_select_record: 'Чтобы произвести операцию, отметьте по крайней мере одну запись',
    resultList_select_record2: 'Чтобы произвести операцию, отметьте по крайней мере две записи',
    resultList_select_limit: 'Количество отмеченых записей превышает предел в ',
    resultList_noresult: 'Список записей пуст. Произведите поиск возвращающий по крайней мере одну запись',
    resultList_empty_remark: 'Не найдено записей удовлетворяющих условиям поиска (записи могут существовать, но не видимы публично или для вашего профиля)',
    resultList_private_record: 'Эта запись не опубликована - только залогиненые пользователи будут видеть её',
    'private - hidden from non-owners': 'личная - видна только владельцам',
    'visible to any logged-in user': 'видна для всех пользователй',
    'pending (viewable by anyone, changes pending)': 'готова к публикации - видима для всех',
    'public (viewable by anyone)': 'опубликована - видима для всех',
    'show selected only': 'только выбранные',
    'Single lines': 'Списком',
    'Single lines with icon': 'Список со значками',
    'Small images': 'Маленькие изображения',
    'Large image': 'Большие  изображения',
    'Record contents': 'Содержимое записи',
    resultList_view_content_hint1: 'This warning is triggered if there are more than 10 records',
    resultList_view_content_hint2: 'You have selected',
    resultList_view_content_hint3: 'records. This display mode loads complete information for each record and will take a long time to load and display all of these data.',
    resultList_action_edit: 'Нажмите для редактирования записи',
    resultList_action_edit2: 'Нажмите для редактирования записи в новом окне',
    resultList_action_view: 'Нажмите для просмотра записи',
    resultList_action_view2: 'Нажмите для просмотра записи в новом окне',
    resultList_action_map: 'Нажмите чтобы скрыть показать на карте',
    resultList_action_dataset: 'Скачать набор данных',
    resultList_action_embded: 'Нажать для получения кода публикации',
    resultList_action_delete: 'Нажать для удаления',
   
    resultList_action_delete_hint: 'Delete map document. Associated map layers and data sources retain',
    'Password reminder': 'Пароль',
    resultList_reorder_list_changed: 'Список был изменен',
    //END resultList

    //search - filters
    'Filter': 'Поиск',
    'Filtered Result': 'Результаты поиска',
    'Save Filter': 'Сохранить фильтр',
    save_filter_hint: 'Сохранить текущий поиск как фильтр доступный для постоянного использования через меню',

    //edit 
    Warn_Lost_Data: 'Вы изменили данные. Нажмите "Сохранить", иначе потеряете все изменения.',     
    Warn_Lost_Data_On_Structure_Edit: 'Нажмите "Сохранить данные" чтобы сохранить запись, "Отменить изменения" чтобы отказаться.<br>Изменения в структуре типа данных будут сохраняться автоматически - это не зависит от Вышего выбора.',
    
    //manage db definitions    
    manageDefRectypes_edit_fields: 'Редактировать поля',
    manageDefRectypes_edit_fields_hint: 'Откроется редкатор пустой записи этого типа в режиме редактрирования структуры<br>Чтобы мгновенно изменить тип данных, Вы можете переключиться в режим редактирования<br> структуры в любое момент при правке ваших записей',            
    manageDefRectypes_new_hint: 'Прежде чем определять новы тип данных, мы предлагаем найти подходяший тип среди шаблонов '+
                    '(Базы Heurist которые зарегистрированы в центральном хранилище). '+
                    'Базы с индексом менее 1000 верифицируются командой Heurist. '
                    +'<br><br>'
    +'Это особенно важно для Библиографических типов данных (см. Шаблон #6 "Bibliographic definitions"), ' 
    +'которые оптимизированы и совместимы с библиографическими данными такими как Zotero, Harvard формат, а также поддерживают обмен данными между базами Heurist.'                
                    +'<br><br>В главном меню:  Дизайн > Импорт шаблонов',
    manageDefRectypes_delete_stop: '<p>Тип данных <b>[rtyName]</b> используется в следующих полях:</p>'
                + '[FieldList]'
                +'<p>Или удалите эти поля или нажмите на ссылке в списке <br>для правки базового поля (это повлияет на все типы данных которые используют это поле).</p>',    
    manageDefRectypes_delete_warn: 'Вы уверены что хотите удалить этот тип данных?',
    manageDefRectypes_duplicate_warn: 'Вы уверены что хотите дублировать тип данных ',
    'Click to add new': 'Добавить новую запись типа ',
    'Click to launch search for': 'Искать записи типа ',
    'Click to edit record type': 'Редактировать тип данных',
    'Click to hide in lists': 'Скрыть в списках',
    'Click to show in lists': 'Показать в списках',
    'Duplicate record type': 'Дублировать тип данных',
    'List of fields': 'Список полей',
    manageDefRectypes_reserved: 'Этот тип данных зарезервирован во всех базах Heurist. Он не может быть удален.',
    manageDefRectypes_hasrecs: 'Прежде чем удалить, нужно удалить записи этого типа. Искать > Типы записей чтобы найти и удалить все записи',
    manageDefRectypes_delete: 'Удалить этот тип данных',
    manageDefRectypes_referenced: 'Этот тип данных используется в базовых полях. Нажмите чтобы посмотреть эти поля',
    manageDefRectypes_longrequest: 'This is taking a long time, it is possible the database is not reachable at <url>, will keep trying for another <timeout - 5> seconds',
    'Filter by Group': 'Группа',
    'Show All': 'Все группы',
    'Sort by': 'Сорт',
    'All Find': 'Искать',
    'Not finding the record type you require?': 'Не найден нужный тип данных?',
    'Define new record type': 'Определить новый тип данных',
    'Find by name, ID or concept code': 'Искать по имени, ID или коду',
    'Show record types for all groups': 'Показать типы данных из всех групп',
    'All Groups': 'Все Группы',
    'All record type groups': 'Типы данных из все групп',
    'Edit Title Mask': 'Редактировать шаблон заголовка',
    
    //my preferences
    'Define Symbology': 'Определить стиль отрисовки',                
    'Define Heurist Theme': 'Определить темы',
    'Configure Interface': 'Настроить интерфейс',
    'Mark columns to be visible. Drag to re-order': 'Отметьте видимые поля. Установить порядок перетаскивая',
    
    //record add dialog    
    'Add Record': 'Добавить запись',
    'Record addition settings': 'Настройки для новой записи',
    'Permission settings': 'Настройки для записи',
    'Save Settings': 'Сохранить настройки',
    'Add Record in New Window': 'Добавить запись в новом окне',
    'Type of record to add': 'Тип данных для новой записи',
    'Get Parameters': 'Загрузить параметры',
    'Select record type for record to be added': 'Выберите тип данных для новой записи',
    'select record type': 'выберите тип данных',
    add_record_settings_hint: 'Эти настройки будут применяться для новых записей',
        
    //record actions dialogs
    'Processed records': 'Обработано записей',
    recordAction_select_lbl: 'Диапазон записей:',
    recordAction_select_hint: 'выберите записи для операции …',    
        'All records': 'Все записи',
        'Selected results set (count=': 'Отмеченные записи (кол-во=',
        'Current results set (count=': 'Текущий результат поиска (кол-во=',
        'only:': 'только:',
    'Add or Remove Tags for Records': 'Добавить или удалить теги для записей',
        'Add tags': 'Присвоить теги',
        'Remove tags': 'Удалить теги',
        'Bookmark': 'Добавить в избранные',
        recordTag_hint0: 'Определите теги с которыми выбранные URL будут добавлены в избранные<br>',
        recordTag_hint1: 'Определите теги с которыми выбранные записи будут добавлены в избранное<br>',
        recordTag_hint2: 'Определите теги чтобы добавить или убрать для выбранных записей<br>',
        recordTag_hint3: 'Matching tags are shown as you type. Click on a listed tag to add it.<br>Unrecognised tags are added automatically as user-specific tags <br>(group tags must be added explicitly by a group administrator). Tags may contain spaces.',
        'No tags were affected': 'Ни один тег не был изменен',
        'Bookmarks added': 'Добавлено в избранные',
        'Tags added': 'Присвоено тегов',
        'Tags removed': 'Убрано тегов',
    'Unbookmark selected records': 'Удалить выбранные записи из избранных',    
        recordUnbookmark_hint: 'Выберите записи которые будут удалены из избранных.<br>'
            +'Любые персональные теги будут убраны из этих записей<br>'
            +'Эта операция удаляет только метку "избранности" и убирает теги из записей, <br>'
            +'собственно записи не удаляются<br>',
        'Remove Bookmarks': 'Отменить избранность',
        'Bookmarks removed': 'Удалено из избранных',
    'Set Record Rating': 'Рейтинг для избранных записей',
        'Set Rating': 'Установить рейтинг',
        'Please specify rating value': 'Пожалуйста определите значение рейтинга',
        'Rating updated': 'Рейтинг изменен',
        'No Rating': 'без рейтинга',
    'Delete Records': 'Удаление записей',        
        
    //SERVER SIDE MESSAGES
    'Record type not defined or wrong': 'Тип данных не определен или неверен',        
            
            
    //Client side error message
    Error_Title: 'Heurist',
    Error_Empty_Message: 'Сервер не предоставил текст сообщения об ошибке, пожалуйста сообщите об этом команде раработчиков Heurist.',
    Error_Report_Code: 'Cообщите код ошибки команде раработчиков',
    Error_Report_Team: 'Если эта ошибка случается регулярно, пожалуйста сообщите Вашему сисадмину или свяжитесь с нами (support at HeuristNetwork dot org) и опишите обстаятельства при которых появляется эта ошибка.',
    Error_Wrong_Request: 'Значения и/или количество параметров запроса неверны.',
    Error_System_Config: 'May result from a network outage, or because the system is not properly configured. If the problem persists, please report to your system administrator',
    Error_Json_Parse: 'Невозможно разобрать ответ сервера',

//---------------------- END OF TRANSLATION 2021-10-19


            'Upload/register new file': 'Загрузить или зарегистрировать файл',
            'Add File': 'Добавить файл',
            'Edit File': 'Редактировать файл',
            'Personal Files':'Личные файлы',
            'Delete selected files': 'Удалить отмеченные файлы',
    
    
};


