#!/usr/bin/env php
<?php
declare(strict_types=1);

// NOTE: THIS IS AN UNTESTED FILE GENERATED BY CHATGPT 7/12/2025
//       BASED ON ALL THE SHELLSCRIPTS IN zzz_delete_deprecated_bash_scriots

/**
 * nightly_procedures.php
 *
 * Combined nightly maintenance script for Heurist servers.
 *
 * Categories:
 *   1. Backups      - create bz2 SQL backups, archive changes, purge old archives
 *   2. Verifications- check required MySQL tables exist
 *   3. Reporting    - lists of DBs, rectypes, fields, users, filestore sizes, websites
 *
 * Behaviour:
 *   - Run once per night from cron.
 *   - Runs tasks sequentially in a fixed order (see bottom of file).
 *   - Writes outputs into /srv/scripts/RESULTS.
 *   - Sends ONE summary email with subject starting:
 *       OK - ...
 *       WARNING - ...
 *       ERROR - ...
 *     and attaches key TSV/HTML reports.
 *
 * NOTE: Server name, filestore and DB credentials are loaded from
 *   /var/www/html/HEURIST/heuristConfigIni.php
 * via $serverName, $defaultRootFileUploadPath, $dbHost, $dbAdminUsername,
 * $dbAdminPassword, $sysAdminEmail.
 */

// -----------------------------------------------------------------------------
// Environment & timezone
// -----------------------------------------------------------------------------

if (php_sapi_name() !== 'cli') {
    fwrite(STDERR, "This script must be run from the command line.\n");
    exit(1);
}

if (function_exists('date_default_timezone_set')) {
    date_default_timezone_set('Europe/Paris');
}

error_reporting(E_ALL);

// -----------------------------------------------------------------------------
// Locate Heurist root and load heuristConfigIni.php
// -----------------------------------------------------------------------------

$scriptDir  = __DIR__;                 // .../HEURIST/heurist/server_management
$heuristDir = dirname($scriptDir);     // .../HEURIST/heurist
$rootDir    = dirname($heuristDir);    // .../HEURIST

$cfgFile = $rootDir . '/heuristConfigIni.php';
if (!is_readable($cfgFile)) {
    fwrite(STDERR, "ERROR: cannot read Heurist config file $cfgFile\n");
    exit(1);
}

// This file defines things like $serverName, $dbHost, $dbAdminUsername,
// $dbAdminPassword, $defaultRootFileUploadPath, $sysAdminEmail, etc.
require $cfgFile;

// -----------------------------------------------------------------------------
// Configuration (values derived from heuristConfigIni.php where possible)
// -----------------------------------------------------------------------------

// Heurist config variables we care about:
global $serverName, $defaultRootFileUploadPath,
       $dbHost, $dbAdminUsername, $dbAdminPassword,
       $sysAdminEmail;

$config = [
    // Server name from heuristConfigIni (falls back to hostname)
    'serverName' => isset($serverName) && $serverName
        ? $serverName
        : (gethostname() ?: 'unknown-server'),

    // Backup directories (not defined in heuristConfigIni.php)
    'backupDir'        => '/srv/BACKUP',            // fresh nightly dumps
    'backupArchiveDir' => '/srv/BACKUP/ARCHIVE',    // archive of backups (purged by rules)

    // Directory where report TSV / logs will be stored
    'resultsDir'       => '/srv/scripts/RESULTS',

    // Email configuration
    // To: system admin email from Heurist config
    'emailTo'            => isset($sysAdminEmail) && $sysAdminEmail
        ? $sysAdminEmail
        : 'root@localhost',
    // From: default to same as To (you can change this if your MTA wants a specific sender)
    'emailFrom'          => isset($sysAdminEmail) && $sysAdminEmail
        ? $sysAdminEmail
        : 'root@localhost',
    'emailSubjectPrefix' => 'Heurist nightly procedures',

    // MySQL / MariaDB admin connection from heuristConfigIni.php
    'mysql' => [
        'host' => (isset($dbHost) && $dbHost !== '')
            ? $dbHost
            : 'localhost',
        'port' => 3306,
        'user' => isset($dbAdminUsername) && $dbAdminUsername
            ? $dbAdminUsername
            : 'root',
        'pass' => isset($dbAdminPassword) ? $dbAdminPassword : '',
    ],

    // Filestore root: from defaultRootFileUploadPath in heuristConfigIni.php
    // e.g. "/var/www/html/HEURIST/HEURIST_FILESTORE/"
    'filestoreDir' => isset($defaultRootFileUploadPath) && $defaultRootFileUploadPath
        ? rtrim($defaultRootFileUploadPath, "/")
        : ($rootDir . '/HEURIST_FILESTORE'),

    // HEURIST web root (for writing list_of_websites_on_all_dbs.html)
    'webRootDir' => $rootDir,

    // Minimum size (bytes) to consider a backup dump "valid"
    'minBackupSize' => 100,

    // Minimum size (bytes) to keep bz2 files (small ones treated as faulty)
    'minBzipSize' => 10 * 1024, // 10KB (similar to archive_bzip_dbs.sh behaviour)

    // Top-level run log
    'logFile' => '/srv/scripts/RESULTS/nightly_procedures_run.log',
];

// -----------------------------------------------------------------------------
// Helper classes & functions
// -----------------------------------------------------------------------------

class TaskResult
{
    public string $name;
    public string $status = 'OK'; // OK, WARNING, ERROR
    /** @var string[] */
    public array $messages = [];
    /** @var string[] */
    public array $warnings = [];
    /** @var string[] */
    public array $errors = [];
    public float $startTime;
    public float $endTime;

    public function __construct(string $name)
    {
        $this->name = $name;
        $this->startTime = microtime(true);
        $this->endTime = $this->startTime;
    }

    public function finish(): void
    {
        $this->endTime = microtime(true);
    }

    public function addMessage(string $msg): void
    {
        $this->messages[] = $msg;
    }

    public function addWarning(string $msg): void
    {
        $this->warnings[] = $msg;
        if ($this->status === 'OK') {
            $this->status = 'WARNING';
        }
    }

    public function addError(string $msg): void
    {
        $this->errors[] = $msg;
        $this->status = 'ERROR';
    }

    public function durationSeconds(): float
    {
        return $this->endTime - $this->startTime;
    }
}

function ensureDir(string $path): void
{
    if (!is_dir($path)) {
        if (!mkdir($path, 0775, true) && !is_dir($path)) {
            throw new RuntimeException("Unable to create directory: $path");
        }
    }
}

function logLine(array $config, string $line): void
{
    if (empty($config['logFile'])) {
        return;
    }
    $ts = date('Y-m-d H:i:s');
    @file_put_contents($config['logFile'], "[$ts] $line\n", FILE_APPEND);
}

/**
 * Get PDO connection to MySQL.
 */
function getPdo(array $config, string $dbName = 'information_schema'): PDO
{
    $dsn = sprintf(
        'mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',
        $config['mysql']['host'],
        $config['mysql']['port'],
        $dbName
    );

    $pdo = new PDO($dsn, $config['mysql']['user'], $config['mysql']['pass'], [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);

    return $pdo;
}

/**
 * Return list of Heurist DB names (schema_name like 'hdb_%').
 */
function getHeuristDatabases(array $config): array
{
    $pdo = getPdo($config, 'information_schema');
    $stmt = $pdo->query(
        "SELECT schema_name 
           FROM information_schema.schemata 
          WHERE schema_name LIKE 'hdb\_%'
          ORDER BY schema_name"
    );
    $dbs = [];
    while ($row = $stmt->fetch()) {
        $dbs[] = $row['schema_name'];
    }
    return $dbs;
}

/**
 * Execute a shell command safely, capturing stdout/stderr and exit code.
 */
function runShellCommand(string $cmd, TaskResult $res, ?string $cwd = null): int
{
    $descriptorSpec = [
        1 => ['pipe', 'w'], // stdout
        2 => ['pipe', 'w'], // stderr
    ];

    $process = proc_open($cmd, $descriptorSpec, $pipes, $cwd ?: null);

    if (!is_resource($process)) {
        $res->addError("Failed to start command: $cmd");
        return 1;
    }

    $stdout = stream_get_contents($pipes[1]);
    fclose($pipes[1]);

    $stderr = stream_get_contents($pipes[2]);
    fclose($pipes[2]);

    $exitCode = proc_close($process);

    if ($stdout !== '') {
        $res->addMessage("Command stdout for '$cmd':\n$stdout");
    }
    if ($stderr !== '') {
        $res->addWarning("Command stderr for '$cmd':\n$stderr");
    }
    if ($exitCode !== 0) {
        $res->addError("Command exited with code $exitCode: $cmd");
    }

    return $exitCode;
}

/**
 * Write TSV file from rows (array of array of scalar values).
 */
function writeTsv(string $path, array $header, array $rows): void
{
    $fh = fopen($path, 'w');
    if (!$fh) {
        throw new RuntimeException("Cannot open $path for writing");
    }
    if ($header) {
        fputcsv($fh, $header, "\t");
    }
    foreach ($rows as $row) {
        fputcsv($fh, $row, "\t");
    }
    fclose($fh);
}

// -----------------------------------------------------------------------------
// 1. BACKUPS
// -----------------------------------------------------------------------------

function task_backupAllDatabases(array $config): TaskResult
{
    $res = new TaskResult('backup_all_dbs');

    $backupDir = $config['backupDir'];
    $minSize   = (int)$config['minBackupSize'];

    try {
        ensureDir($backupDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure backup directory $backupDir: " . $e->getMessage());
        $res->finish();
        return $res;
    }

    // Clear previous backups.
    foreach (glob($backupDir . '/*.sql') ?: [] as $file) {
        @unlink($file);
    }
    foreach (glob($backupDir . '/*.sql.bz2') ?: [] as $file) {
        @unlink($file);
    }

    $cnt      = 0;
    $success  = 0;
    $failure  = 0;
    $empty    = 0;
    $totSize  = 0;

    $dbs = getHeuristDatabases($config);
    $res->addMessage("Found " . count($dbs) . " Heurist databases to back up.");

    foreach ($dbs as $dbName) {
        $cnt++;
        $res->addMessage("$dbName : backing up ...");

        $sqlFile = $backupDir . '/' . $dbName . '.sql';
        $bz2File = $sqlFile . '.bz2';

        // mysqldump command     --databases vs --no-create-db 
        $cmd = sprintf(
'mysqldump -h%s -P%d -u%s -p%s --single-transaction --skip-triggers --skip-routines --add-drop-table --quick --skip-dump-date %s > %s',
            escapeshellarg($config['mysql']['host']),
            (int)$config['mysql']['port'],
            escapeshellarg($config['mysql']['user']),
            escapeshellarg($config['mysql']['pass']),
            escapeshellarg($dbName),
            escapeshellarg($sqlFile)
        );
        
        

        $exitDump = runShellCommand($cmd, $res, $backupDir);
        if ($exitDump !== 0) {
            $failure++;
            $res->addError("$dbName : mysqldump failed with exit code $exitDump");
            continue;
        }

        $filesize = is_file($sqlFile) ? filesize($sqlFile) : 0;

        if ($filesize <= $minSize) {
            $empty++;
            $failure++;
            $res->addWarning("$dbName : dump filesize $filesize bytes <= min $minSize – EMPTY/FAILURE; deleting.");
            @unlink($sqlFile);
            continue;
        }

        // Compress with bzip2
        $cmdBzip = sprintf('bzip2 %s', escapeshellarg($sqlFile));
        $exitBzip = runShellCommand($cmdBzip, $res, $backupDir);

        if ($exitBzip !== 0) {
            $failure++;
            $res->addError("$dbName : bzip2 failed for $sqlFile");
            @unlink($sqlFile);
            continue;
        }

        if (!is_file($bz2File)) {
            $failure++;
            $res->addError("$dbName : expected compressed file not found: $bz2File");
            continue;
        }

        $bzSize = filesize($bz2File) ?: 0;
        $totSize += $bzSize;
        $success++;
        $res->addMessage("$dbName : backup success – compressed size $bzSize bytes.");
    }

    $res->addMessage(sprintf(
        'Backup completed %s. Databases: %d. Archived successfully: %d (total size %d). Empty: %d. Failures: %d.',
        date('Y-m-d H:i:s'),
        $cnt,
        $success,
        $totSize,
        $empty,
        $failure
    ));

    if ($failure > 0 || $empty > 0) {
        $res->addWarning("Some backups failed or were empty (see details above).");
    }

    $res->finish();
    return $res;
}

function task_archiveBzipDbs(array $config): TaskResult
{
    $res = new TaskResult('archive_bzip_dbs');

    $backupDir  = $config['backupDir'];
    $archiveDir = $config['backupArchiveDir'];
    $minSize    = (int)$config['minBzipSize'];

    try {
        ensureDir($backupDir);
        ensureDir($archiveDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure backup/archive directories: " . $e->getMessage());
        $res->finish();
        return $res;
    }

    // Remove tiny files.
    foreach (glob($archiveDir . '/hdb_*.sql.bz2*') ?: [] as $file) {
        if (filesize($file) < $minSize) {
            @unlink($file);
        }
    }
    foreach (glob($backupDir . '/hdb_*.sql.bz2') ?: [] as $file) {
        if (filesize($file) < $minSize) {
            @unlink($file);
        }
    }

    $nowDate = date('Y-m-d');
    $countNew = 0;
    $countChanged = 0;

    foreach (glob($backupDir . '/hdb_*.sql.bz2') ?: [] as $file) {
        $base = basename($file);
        $archiveFile = $archiveDir . '/' . $base;

        if (!file_exists($archiveFile)) {
            if (!copy($file, $archiveFile)) {
                $res->addError("Failed to copy new backup $file to $archiveFile");
            } else {
                $countNew++;
                $res->addMessage("File is new: $base");
            }
            continue;
        }

        $same = (filesize($file) === filesize($archiveFile));
        if ($same) {
            $same = (sha1_file($file) === sha1_file($archiveFile));
        }

        if ($same) {
            continue;
        }

        $dated = $archiveDir . '/' . $base . '.' . $nowDate;
        @rename($archiveFile, $dated);
        if (!copy($file, $archiveFile)) {
            $res->addError("Failed to archive changed backup $file -> $archiveFile");
        } else {
            $countChanged++;
            $res->addMessage("File changed – archived previous $base to $dated");
        }
    }

    $res->addMessage("Archive step completed: new={$countNew}, changed={$countChanged}");
    $res->finish();
    return $res;
}

function task_purgeArchive(array $config): TaskResult
{
    $res = new TaskResult('purge_ARCHIVE');

    $archiveDir = $config['backupArchiveDir'];
    try {
        ensureDir($archiveDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure archive directory $archiveDir: " . $e->getMessage());
        $res->finish();
        return $res;
    }

    $files = glob($archiveDir . '/hdb_*.sql.bz2*') ?: [];
    if (!$files) {
        $res->addMessage("No hdb_*.sql.bz2 files found in $archiveDir.");
        $res->finish();
        return $res;
    }

    $now = time();
    $keep = []; // file path => true
    $latestPerMonth = []; // [dbBase][YYYY-MM] => [file, mtime]

    foreach ($files as $file) {
        $mtime = @filemtime($file);
        if (!$mtime) {
            continue;
        }
        if ($now - $mtime <= 10 * 24 * 3600) {
            $keep[$file] = true;
        }

        $baseName = basename($file);
        $pos = strpos($baseName, '.sql.bz2');
        if ($pos === false) {
            $keep[$file] = true;
            continue;
        }
        $dbBase = substr($baseName, 0, $pos);
        $ym = date('Y-m', $mtime);

        if (!isset($latestPerMonth[$dbBase][$ym]) || $mtime > $latestPerMonth[$dbBase][$ym]['mtime']) {
            $latestPerMonth[$dbBase][$ym] = ['file' => $file, 'mtime' => $mtime];
        }
    }

    foreach ($latestPerMonth as $dbBase => $months) {
        foreach ($months as $info) {
            $keep[$info['file']] = true;
        }
    }

    $deleted = 0;
    foreach ($files as $file) {
        if (isset($keep[$file])) {
            continue;
        }
        $mtime = @filemtime($file);
        if ($mtime && ($now - $mtime > 10 * 24 * 3600)) {
            if (@unlink($file)) {
                $deleted++;
                $res->addMessage("Deleting old archive file: $file");
            }
        }
    }

    $res->addMessage("Purge completed in $archiveDir – deleted $deleted file(s).");
    $res->finish();
    return $res;
}

// -----------------------------------------------------------------------------
// 2. VERIFICATIONS
// -----------------------------------------------------------------------------

function task_checkRequiredTables(array $config): TaskResult
{
    $res = new TaskResult('check_for_required_tables');

    $requiredTables = [
        'sysIdentification',
        'sysUGrps',
        'Records',
        'defRecTypes',
        'defRecStructure',
        'defDetailTypes',
        'defTerms',
        'defLanguages',
        'defCalcFunctions',
    ];

    $dbs = getHeuristDatabases($config);
    $rows = [];
    $pdoInfo = getPdo($config, 'information_schema');

    foreach ($dbs as $db) {
        try {
            $placeholders = implode(',', array_fill(0, count($requiredTables), '?'));
            $sql = "SELECT table_name 
                      FROM information_schema.tables 
                     WHERE table_schema = ? 
                       AND table_name IN ($placeholders)";
            $params = array_merge([$db], $requiredTables);
            $stmt = $pdoInfo->prepare($sql);
            $stmt->execute($params);
            $present = [];
            while ($row = $stmt->fetch()) {
                $present[] = $row['table_name'];
            }
            $missing = array_values(array_diff($requiredTables, $present));

            if ($missing) {
                $res->addWarning("$db missing tables: " . implode(', ', $missing));
                $rows[] = [$db, 'MISSING', implode(',', $missing)];
            } else {
                $rows[] = [$db, 'OK', ''];
            }
        } catch (Throwable $e) {
            $res->addError("Error checking tables in $db: " . $e->getMessage());
            $rows[] = [$db, 'ERROR', $e->getMessage()];
        }
    }

    $resultsDir = $config['resultsDir'];
    try {
        ensureDir($resultsDir);
        $path = $resultsDir . '/required_tables_check.tsv';
        writeTsv($path, ['database', 'status', 'missing_tables'], $rows);
        $res->addMessage("Wrote required-tables report to $path");
    } catch (Throwable $e) {
        $res->addError("Failed to write required tables TSV: " . $e->getMessage());
    }

    $res->finish();
    return $res;
}

// -----------------------------------------------------------------------------
// 3. REPORTING TASKS
// -----------------------------------------------------------------------------

function task_listAllDbs(array $config): TaskResult
{
    $res = new TaskResult('list_all_dbs');

    $resultsDir = $config['resultsDir'];
    try {
        ensureDir($resultsDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure results directory: " . $e->getMessage());
        $res->finish();
        return $res;
    }
    $outPath = $resultsDir . '/list_of_dbs.tsv';

    $dbs = getHeuristDatabases($config);
    $rows = [];

    foreach ($dbs as $db) {
        try {
            $pdo = getPdo($config, $db);

            $p = preg_replace('/^hdb_/', '', $db);
            $deleteCmd = "/srv/scripts/delete_database_to_archive.sh $p";

            $sql = "
                SELECT
                    :dbname AS db_name,
                    u.ugr_eMail      AS admin_email,
                    u.ugr_LastName   AS admin_last,
                    u.ugr_FirstName  AS admin_first,
                    COUNT(r.rec_ID)  AS record_count,
                    MAX(r.rec_Modified) AS last_modified,
                    YEAR(MAX(r.rec_Modified)) AS last_modified_year,
                    MONTH(MAX(r.rec_Modified)) AS last_modified_month,
                    :delete_cmd AS delete_command,
                    s.sys_dbRegisteredID,
                    s.sys_dbVersion,
                    s.sys_dbSubVersion
                FROM sysIdentification s
                JOIN sysUGrps u
                JOIN Records r
                WHERE u.ugr_ID = 2
            ";
            $stmt = $pdo->prepare($sql);
            $stmt->execute([
                ':dbname'     => $db,
                ':delete_cmd' => $deleteCmd,
            ]);
            $row = $stmt->fetch();

            if ($row) {
                $rows[] = [
                    $row['db_name'],
                    $row['admin_email'],
                    $row['admin_last'],
                    $row['admin_first'],
                    $row['record_count'],
                    $row['last_modified'],
                    $row['last_modified_year'],
                    $row['last_modified_month'],
                    $row['delete_command'],
                    $row['sys_dbRegisteredID'],
                    $row['sys_dbVersion'],
                    $row['sys_dbSubVersion'],
                ];
            } else {
                $res->addWarning("No summary row returned for $db (sysIdentification/sysUGrps/Records may be empty)");
            }
        } catch (Throwable $e) {
            $res->addError("Error listing db $db: " . $e->getMessage());
        }
    }

    usort($rows, static function ($a, $b) {
        return strcmp((string)$a[0], (string)$b[0]);
    });

    try {
        writeTsv($outPath, [
            'db_name', 'admin_email', 'admin_last', 'admin_first',
            'record_count', 'last_modified', 'last_modified_year', 'last_modified_month',
            'delete_command', 'sys_dbRegisteredID', 'sys_dbVersion', 'sys_dbSubVersion',
        ], $rows);
        $res->addMessage("Wrote DB list to $outPath");
    } catch (Throwable $e) {
        $res->addError("Failed to write DB list TSV: " . $e->getMessage());
    }

    $res->finish();
    return $res;
}

function task_listFilestoreSizes(array $config): TaskResult
{
    $res = new TaskResult('list_filestore_sizes');

    $resultsDir = $config['resultsDir'];
    try {
        ensureDir($resultsDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure results directory: " . $e->getMessage());
        $res->finish();
        return $res;
    }

    $outPath = $resultsDir . '/filestore_sizes.txt';

    $filestoreDir = $config['filestoreDir'];

    $cmd = sprintf(
        'du -s %s/* 2>/dev/null | sort -rn > %s',
        escapeshellarg($filestoreDir),
        escapeshellarg($outPath)
    );
    $exit = runShellCommand($cmd, $res);
    if ($exit === 0) {
        $res->addMessage("Wrote filestore sizes to $outPath");
    }

    $res->finish();
    return $res;
}

function task_listAllWebsites(array $config): TaskResult
{
    $res = new TaskResult('list_all_websites');

    $resultsDir = $config['resultsDir'];
    try {
        ensureDir($resultsDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure results directory: " . $e->getMessage());
        $res->finish();
        return $res;
    }

    $tsvPath  = $resultsDir . '/list_of_websites_on_all_dbs.tsv';
    $htmlPath = $config['webRootDir'] . '/list_of_websites_on_all_dbs.html';

    $dbs = getHeuristDatabases($config);
    $rowsHtmlLines = [];

    foreach ($dbs as $db) {
        try {
            $pdo = getPdo($config, $db);

            $sql = "
                SELECT r.rec_ID, r.rec_Title
                  FROM Records r
                 WHERE r.rec_RecTypeID IN (
                        SELECT rt.rty_ID
                          FROM defRecTypes rt
                         WHERE rt.rty_OriginatingDBID = 99
                           AND rt.rty_IDInOriginatingDB = 51
                 )
                   AND NOT r.rec_FlagTemporary
                   AND r.rec_Title NOT LIKE '%Enter a website name here%'
                   AND r.rec_Title NOT LIKE '%UNCONFIGURED SITE TITLE%'
            ";
            $stmt = $pdo->query($sql);
            while ($row = $stmt->fetch()) {
                $recId = (int)$row['rec_ID'];
                $title = (string)$row['rec_Title'];
                $server = $config['serverName'];
                $dbNameEsc = htmlspecialchars($db, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
                $titleEsc  = htmlspecialchars($title, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
                $link = sprintf(
                    '<h3><a href="https://%s/heurist/?db=%s&website&id=%d" target="_blank">%s</a></h3>',
                    $server,
                    $dbNameEsc,
                    $recId,
                    $dbNameEsc
                );
                $desc = sprintf(
                    '<pre style="font-size: 10px;margin-left:30px;">%s</pre>',
                    $titleEsc
                );
                $rowsHtmlLines[] = $link . "\n" . $desc;
            }
        } catch (Throwable $e) {
            $res->addError("Error listing websites in $db: " . $e->getMessage());
        }
    }

    sort($rowsHtmlLines, SORT_STRING);

    $rowsTsv = [];
    foreach ($rowsHtmlLines as $line) {
        $rowsTsv[] = [$line];
    }

    try {
        writeTsv($tsvPath, [], $rowsTsv);
        $res->addMessage("Wrote websites TSV (HTML snippets) to $tsvPath");
    } catch (Throwable $e) {
        $res->addError("Failed to write websites TSV: " . $e->getMessage());
    }

    try {
        ensureDir(dirname($htmlPath));
        $html = "<html><body>\n";
        $html .= sprintf(
            "<h1>Heurist websites on %s at %s</h1>\n",
            htmlspecialchars($config['serverName'], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'),
            date('Y-m-d H:i:s')
        );
        foreach ($rowsHtmlLines as $block) {
            $html .= $block . "\n";
        }
        $html .= "</body></html>\n";
        file_put_contents($htmlPath, $html);
        $res->addMessage("Wrote websites HTML page to $htmlPath");
    } catch (Throwable $e) {
        $res->addError("Failed to write websites HTML page: " . $e->getMessage());
    }

    $res->finish();
    return $res;
}

function task_listAllRectypes(array $config): TaskResult
{
    $res = new TaskResult('list_all_rectypes');

    $resultsDir = $config['resultsDir'];
    try {
        ensureDir($resultsDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure results directory: " . $e->getMessage());
        $res->finish();
        return $res;
    }

    $outPath = $resultsDir . '/list_of_rectypes_on_all_dbs.tsv';

    $dbs = getHeuristDatabases($config);
    $rectypes = [];

    foreach ($dbs as $db) {
        try {
            $pdo = getPdo($config, $db);
            $stmt = $pdo->query("SELECT rty_Name FROM defRecTypes WHERE 1");
            while ($row = $stmt->fetch()) {
                $rectypes[$row['rty_Name']] = true;
            }
        } catch (Throwable $e) {
            $res->addError("Error listing rectypes in $db: " . $e->getMessage());
        }
    }

    $names = array_keys($rectypes);
    sort($names, SORT_STRING);
    $rows = [];
    foreach ($names as $name) {
        $rows[] = [$name];
    }

    try {
        writeTsv($outPath, [], $rows);
        $res->addMessage("Wrote rectypes list to $outPath");
    } catch (Throwable $e) {
        $res->addError("Failed to write rectypes TSV: " . $e->getMessage());
    }

    $res->finish();
    return $res;
}

function task_listAllRectypesWithConceptIds(array $config): TaskResult
{
    $res = new TaskResult('list_all_rectypes_with_concept_IDs');

    $resultsDir = $config['resultsDir'];
    try {
        ensureDir($resultsDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure results directory: " . $e->Message());
        $res->finish();
        return $res;
    }

    $outPath = $resultsDir . '/list_of_rectypes_on_all_dbs_with_concept_IDs.tsv';

    $dbs = getHeuristDatabases($config);
    $seen = [];
    $rows = [];

    foreach ($dbs as $db) {
        try {
            $pdo = getPdo($config, $db);
            $stmt = $pdo->query("
                SELECT rty_Name, rty_OriginatingDBID, rty_IDInOriginatingDB
                  FROM defRecTypes
                 WHERE 1
            ");
            while ($row = $stmt->fetch()) {
                $key = $row['rty_Name'] . '|' . $row['rty_OriginatingDBID'] . '|' . $row['rty_IDInOriginatingDB'] . '|' . $db;
                if (isset($seen[$key])) {
                    continue;
                }
                $seen[$key] = true;
                $rows[] = [
                    $row['rty_Name'],
                    $row['rty_OriginatingDBID'],
                    $row['rty_IDInOriginatingDB'],
                    $db,
                ];
            }
        } catch (Throwable $e) {
            $res->addError("Error listing rectypes+concept IDs in $db: " . $e->getMessage());
        }
    }

    usort($rows, static function ($a, $b) {
        return strcmp(implode("\t", $a), implode("\t", $b));
    });

    try {
        writeTsv($outPath, ['rty_Name', 'rty_OriginatingDBID', 'rty_IDInOriginatingDB', 'db'], $rows);
        $res->addMessage("Wrote rectypes+concept IDs list to $outPath");
    } catch (Throwable $e) {
        $res->addError("Failed to write rectypes+concept IDs TSV: " . $e->getMessage());
    }

    $res->finish();
    return $res;
}

function task_listAllFields(array $config): TaskResult
{
    $res = new TaskResult('list_all_fields');

    $resultsDir = $config['resultsDir'];
    try {
        ensureDir($resultsDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure results directory: " . $e->getMessage());
        $res->finish();
        return $res;
    }

    $outPath = $resultsDir . '/list_of_fields_on_all_dbs.tsv';

    $dbs = getHeuristDatabases($config);
    $seen = [];
    $rows = [];

    foreach ($dbs as $db) {
        try {
            $pdo = getPdo($config, $db);
            $stmt = $pdo->query("
                SELECT rst_DisplayName, rst_DisplayHelpText
                  FROM defRecStructure
                 WHERE 1
            ");
            while ($row = $stmt->fetch()) {
                $key = $row['rst_DisplayName'] . '|' . $row['rst_DisplayHelpText'];
                if (isset($seen[$key])) {
                    continue;
                }
                $seen[$key] = true;
                $rows[] = [
                    $row['rst_DisplayName'],
                    $row['rst_DisplayHelpText'],
                ];
            }
        } catch (Throwable $e) {
            $res->addError("Error listing fields in $db: " . $e->getMessage());
        }
    }

    usort($rows, static function ($a, $b) {
        return strcmp((string)$a[0], (string)$b[0]);
    });

    try {
        writeTsv($outPath, ['rst_DisplayName', 'rst_DisplayHelpText'], $rows);
        $res->addMessage("Wrote fields list to $outPath");
    } catch (Throwable $e) {
        $res->addError("Failed to write fields TSV: " . $e->getMessage());
    }

    $res->finish();
    return $res;
}

function task_listAllUsersUnique(array $config): TaskResult
{
    $res = new TaskResult('list_all_users_unique');

    $resultsDir = $config['resultsDir'];
    try {
        ensureDir($resultsDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure results directory: " . $e->getMessage());
        $res->finish();
        return $res;
    }

    $cumulativePath = $resultsDir . '/cumulative_list_of_users_unique.tsv';

    $users = [];
    if (is_file($cumulativePath)) {
        $fh = fopen($cumulativePath, 'r');
        if ($fh) {
            while (($row = fgetcsv($fh, 0, "\t")) !== false) {
                if (!isset($row[0])) {
                    continue;
                }
                $email = trim($row[0]);
                if ($email === '' || $email[0] === '#') {
                    continue;
                }
                $users[$email] = [
                    $email,
                    $row[1] ?? '',
                    $row[2] ?? '',
                ];
            }
            fclose($fh);
        }
    }

    $dbs = getHeuristDatabases($config);
    foreach ($dbs as $db) {
        try {
            $pdo = getPdo($config, $db);
            $sql = "
                SELECT ugr_eMail, ugr_FirstName, ugr_LastName
                  FROM sysUGrps
                 WHERE ugr_Type = 'user'
                   AND ugr_eMail NOT IN (
                        'guest@null',
                        'info@heuristscholar.org',
                        'info@heuristnetwork.org'
                   )
            ";
            $stmt = $pdo->query($sql);
            while ($row = $stmt->fetch()) {
                $email = trim((string)$row['ugr_eMail']);
                if ($email === '') {
                    continue;
                }
                $users[$email] = [
                    $email,
                    (string)$row['ugr_FirstName'],
                    (string)$row['ugr_LastName'],
                ];
            }
        } catch (Throwable $e) {
            $res->addError("Error listing users (unique) in $db: " . $e->getMessage());
        }
    }

    ksort($users, SORT_STRING);
    $rows = array_values($users);

    try {
        writeTsv($cumulativePath, [], $rows);
        $res->addMessage("Wrote cumulative unique users to $cumulativePath");
    } catch (Throwable $e) {
        $res->addError("Failed to write cumulative users TSV: " . $e->getMessage());
    }

    $monthPrefix = date('Y-m');
    $zipPath = sprintf('%s/%s_archive_cumulative_list_of_users_unique.zip', $resultsDir, $monthPrefix);
    if (is_file($cumulativePath)) {
        $cmd = sprintf(
            'zip -j -q %s %s',
            escapeshellarg($zipPath),
            escapeshellarg($cumulativePath)
        );
        $exit = runShellCommand($cmd, $res);
        if ($exit === 0) {
            $res->addMessage("Created monthly zip archive $zipPath");
        }
    }

    $res->finish();
    return $res;
}

function task_listAllUsersWithDbs(array $config): TaskResult
{
    $res = new TaskResult('list_all_users_with_dbs');

    $resultsDir = $config['resultsDir'];
    try {
        ensureDir($resultsDir);
    } catch (Throwable $e) {
        $res->addError("Cannot ensure results directory: " . $e->getMessage());
        $res->finish();
        return $res;
    }

    $outPath = $resultsDir . '/list_of_users_on_all_dbs.tsv';

    $dbs = getHeuristDatabases($config);
    $rows = [];

    $rows[] = [
        'Email', 'FirstName', 'LastName', 'Database',
        'LastLoginTime', 'LoginCount', 'Organisation', 'Interests',
    ];

    foreach ($dbs as $db) {
        try {
            $pdo = getPdo($config, $db);
            $sql = "
                SELECT ugr_eMail, ugr_FirstName, ugr_LastName,
                       ugr_LastLoginTime, ugr_LoginCount,
                       ugr_organisation, ugr_interests
                  FROM sysUGrps
                 WHERE ugr_Type = 'user'
                   AND ugr_eMail NOT IN (
                        'guest@null',
                        'info@heuristscholar.org',
                        'info@heuristnetwork.org'
                   )
            ";
            $stmt = $pdo->query($sql);
            while ($row = $stmt->fetch()) {
                $rows[] = [
                    $row['ugr_eMail'],
                    $row['ugr_FirstName'],
                    $row['ugr_LastName'],
                    $db,
                    $row['ugr_LastLoginTime'],
                    $row['ugr_LoginCount'],
                    $row['ugr_organisation'],
                    $row['ugr_interests'],
                ];
            }
        } catch (Throwable $e) {
            $res->addError("Error listing users with DBs in $db: " . $e->getMessage());
        }
    }

    $header = array_shift($rows);
    usort($rows, static function ($a, $b) {
        $cmp = strcmp((string)$a[0], (string)$b[0]);
        if ($cmp !== 0) {
            return $cmp;
        }
        return strcmp((string)$a[3], (string)$b[3]);
    });
    array_unshift($rows, $header);

    try {
        writeTsv($outPath, [], $rows);
        $res->addMessage("Wrote users-with-dbs list to $outPath");
    } catch (Throwable $e) {
        $res->addError("Failed to write users-with-dbs TSV: " . $e->getMessage());
    }

    $res->finish();
    return $res;
}

function task_listAllHeuristServers(array $config): TaskResult
{
    $res = new TaskResult('list_all_heurist_servers');
    $res->addWarning("TODO: list_all_heurist_servers() not implemented – please add logic if required.");
    $res->finish();
    return $res;
}

// -----------------------------------------------------------------------------
// EMAIL SUMMARY
// -----------------------------------------------------------------------------

function overallStatus(array $taskResults): string
{
    $worst = 'OK';
    foreach ($taskResults as $r) {
        if ($r->status === 'ERROR') {
            return 'ERROR';
        }
        if ($r->status === 'WARNING') {
            $worst = 'WARNING';
        }
    }
    return $worst;
}

function sendSummaryEmail(array $config, array $taskResults): void
{
    $status = overallStatus($taskResults);
    $subject = sprintf(
        '%s - %s on %s',
        $status,
        $config['emailSubjectPrefix'],
        $config['serverName']
    );

    $to   = $config['emailTo'];
    $from = $config['emailFrom'];

    $bodyLines = [];
    $bodyLines[] = sprintf(
        "Nightly procedures on %s completed at %s.",
        $config['serverName'],
        date('Y-m-d H:i:s')
    );
    $bodyLines[] = '';
    $bodyLines[] = "Task summary:";
    foreach ($taskResults as $r) {
        $bodyLines[] = sprintf(
            "- %s: %s (%.1fs)",
            $r->name,
            $r->status,
            $r->durationSeconds()
        );
        foreach ($r->errors as $e) {
            $bodyLines[] = "    ERROR: " . $e;
        }
        foreach ($r->warnings as $w) {
            $bodyLines[] = "    WARNING: " . $w;
        }
    }
    $bodyLines[] = '';
    $bodyLines[] = "See attached TSV/HTML files in /srv/scripts/RESULTS for details.";
    $bodyLines[] = "This message was generated by nightly_procedures.php.";

    $textBody = implode("\r\n", $bodyLines);

    $attachments = [];
    $resultsDir = $config['resultsDir'];
    $maybeFiles = [
        $resultsDir . '/list_of_dbs.tsv',
        $resultsDir . '/list_of_users_on_all_dbs.tsv',
        $resultsDir . '/cumulative_list_of_users_unique.tsv',
        $resultsDir . '/list_of_rectypes_on_all_dbs.tsv',
        $resultsDir . '/list_of_fields_on_all_dbs.tsv',
        $resultsDir . '/list_of_websites_on_all_dbs.tsv',
        $resultsDir . '/filestore_sizes.txt',
        $resultsDir . '/required_tables_check.tsv',
    ];
    foreach ($maybeFiles as $path) {
        if (is_file($path)) {
            $attachments[] = $path;
        }
    }

    if (!$attachments) {
        $headers = "From: {$from}\r\n" .
                   "Content-Type: text/plain; charset=UTF-8\r\n";
        @mail($to, $subject, $textBody, $headers);
        return;
    }

    $boundary = '==MIXED_' . md5((string)microtime(true));

    $headers = [];
    $headers[] = "From: {$from}";
    $headers[] = "MIME-Version: 1.0";
    $headers[] = "Content-Type: multipart/mixed; boundary=\"{$boundary}\"";

    $message = '';
    $message .= "--{$boundary}\r\n";
    $message .= "Content-Type: text/plain; charset=\"UTF-8\"\r\n";
    $message .= "Content-Transfer-Encoding: 7bit\r\n\r\n";
    $message .= $textBody . "\r\n";

    foreach ($attachments as $path) {
        $filename = basename($path);
        $data = file_get_contents($path);
        if ($data === false) {
            continue;
        }
        $message .= "--{$boundary}\r\n";
        $message .= "Content-Type: text/plain; name=\"{$filename}\"\r\n";
        $message .= "Content-Transfer-Encoding: base64\r\n";
        $message .= "Content-Disposition: attachment; filename=\"{$filename}\"\r\n\r\n";
        $message .= chunk_split(base64_encode($data)) . "\r\n";
    }

    $message .= "--{$boundary}--\r\n";

    @mail($to, $subject, $message, implode("\r\n", $headers));
}

// -----------------------------------------------------------------------------
// MAIN
// -----------------------------------------------------------------------------

function main(array $config): void
{
    $start = microtime(true);

    try {
        ensureDir($config['resultsDir']);
    } catch (Throwable $e) {
        fwrite(STDERR, "Cannot ensure results directory: " . $e->getMessage() . "\n");
        exit(1);
    }

    $tasks = [
        // 1. Backups
        'task_backupAllDatabases',
        'task_archiveBzipDbs',
        'task_purgeArchive',

        // 2. Verifications
        'task_checkRequiredTables',

        // 3. Reporting
        'task_listAllDbs',
        'task_listFilestoreSizes',
        'task_listAllWebsites',
        'task_listAllHeuristServers',
        'task_listAllRectypes',
        'task_listAllRectypesWithConceptIds',
        'task_listAllFields',
        'task_listAllUsersUnique',
        'task_listAllUsersWithDbs',
    ];

    $results = [];

    foreach ($tasks as $taskFn) {
        if (!function_exists($taskFn)) {
            logLine($config, "Task function $taskFn is not defined – skipping.");
            continue;
        }
        logLine($config, "Starting task $taskFn ...");
        $res = $taskFn($config);
        $results[] = $res;
        logLine($config, sprintf(
            "Finished task %s: %s (%.1fs)",
            $res->name,
            $res->status,
            $res->durationSeconds()
        ));
    }

    $overall = overallStatus($results);
    logLine($config, sprintf(
        "Nightly procedures completed with status %s in %.1fs",
        $overall,
        microtime(true) - $start
    ));

    sendSummaryEmail($config, $results);
}

main($config);
