<?php
/*
* Licensed under the GNU License, Version 3.0 (the "License"); you may not use this file except in compliance
* with the License. You may obtain a copy of the License at https://www.gnu.org/licenses/gpl-3.0.txt
* Unless required by applicable law or agreed to in writing, software distributed under the License is
* distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied
* See the License for the specific language governing permissions and limitations under the License.
*/

/**
* exportRecordsXML.php - class to export records as XML
*
* Controller is records_output
*
* @package     Heurist academic knowledge management system
* @link        https://HeuristNetwork.org
* @copyright   (C) 2005-2023 University of Sydney, (C) 2024 onwards Heurist Network
* @author      Artem Osmakov   <osmakov@gmail.com>
* @author      Ian Johnson     <ian.johnson.heurist@gmail.com>
* @license     https://www.gnu.org/licenses/gpl-3.0.txt GNU License 3.0
* @version     4.0
*/

namespace hserv\records\export;
use hserv\records\export\ExportRecords;

/**
 * Class ExportRecordsXML
 *
 * Extends ExportRecords to provide functionality for exporting records in XML format.
 * This class is typically controlled by the 'records_output' controller.
 * It uses SimpleXMLElement to construct the XML structure.
 *
 * @package hserv\records\export
 */
class ExportRecordsXML extends ExportRecords {

    /**
     * Outputs the header for the XML export.
     *
     * Writes the standard XML declaration and the opening <heurist><records> tags.
     * XML_HEADER is expected to be '<?xml version="1.0" encoding="UTF-8"?>'.
     */
protected function _outputHeader(){

    fwrite($this->fd, XML_HEADER.'<heurist><records>');
}

    /**
     * Outputs a single record in XML format.
     *
     * Converts the provided record array into an XML structure using the
     * `_array_to_xml` helper method. The resulting XML for the record
     * (excluding the XML declaration generated by SimpleXMLElement)
     * is then written to the output stream.
     *
     * @param array $record The Heurist record array to process and output.
     * @return bool Always true to continue processing.
     */
protected function _outputRecord($record){

    $xml = new \SimpleXMLElement(XML_HEADER.'<record/>');
    self::_array_to_xml($record, $xml);
    fwrite($this->fd, substr($xml->asXML(),38));//remove header

    return true;

}

    /**
     * Outputs the footer for the XML export.
     *
     * Closes the main <records> tag. Then, retrieves database information
     * using `_getDatabaseInfo()`, converts this information to XML using
     * `_array_to_xml`, writes it to the stream, and finally closes the
     * root <heurist> tag.
     */
protected function _outputFooter(){

    fwrite($this->fd, '</records>');

    $database_info = $this->_getDatabaseInfo();

    $xml = new \SimpleXMLElement(XML_HEADER.'<database/>');
    self::_array_to_xml($database_info, $xml);
    fwrite($this->fd, substr($xml->asXML(),38));
    fwrite($this->fd, '</heurist>');
}

    /**
     * Recursively converts a PHP array to XML using SimpleXMLElement.
     *
     * Iterates through the input array. For each key-value pair:
     * - If the key is numeric, it's prefixed with "item" to create a valid XML tag name.
     * - If the value is an array, a new child element is created, and the function
     *   calls itself recursively to populate this subnode.
     * - If the value is scalar, a child element is created with the key as its name
     *   and the HTML-escaped value as its content.
     *
     * @param array $data The array to convert to XML.
     * @param \SimpleXMLElement $xml_data The SimpleXMLElement object to which new child elements will be added.
     */
private static function _array_to_xml( $data, &$xml_data ) {
    foreach( $data as $key => $value ) {
        if( is_numeric($key) ){
            $key = 'item'.$key; //dealing with <0/>..<n/> issues
        }
        if( is_array($value) ) {
            $subnode = $xml_data->addChild($key);
            self::_array_to_xml($value, $subnode);
        } else {
            $xml_data->addChild("$key",htmlspecialchars("$value"));
        }
     }
}

} //end class
?>