<?php
/**
* ExportRecordsIIIF.php - Class ExportRecordsIIIF.php 
*
* Extends `ExportRecords` for exporting records as IIIF manifest.
*
* @project     Heurist academic knowledge management system
* @package Records\Export
* @link        https://HeuristNetwork.org
* @copyright   (C) 2005-2023 University of Sydney, (C) 2024 onwards Heurist Network
* @license     https://www.gnu.org/licenses/gpl-3.0.txt GNU License 3.0
* @author      Artem Osmakov   <osmakov@gmail.com>
* @author      Ian Johnson     <ian.johnson.heurist@gmail.com>
* @since       6.0
*/
namespace hserv\records\export;

use hserv\records\export\ExportRecords;
use hserv\entity\DbIiifCanvas;
use hserv\entity\DbIiifManifest;
use hserv\iiif\IiifMediaHelper;
use hserv\iiif\IiifManifestJson;
use hserv\iiif\IiifPresentationService;

require_once dirname(__FILE__).'/../../entity/DbIiifCanvas.php';
require_once dirname(__FILE__).'/../../entity/DbIiifManifest.php';

/**
* Class ExportRecordsIIIF
*
* Extends ExportRecords to provide dynamic IIIF Presentation API v3 output for
* recordsets. IIIF Presentation API v2 output is intentionally no longer
* generated by Heurist; v2/hybrid Manifests remain supported on import and are
* re-published as v3 when managed by Heurist.
*/
class ExportRecordsIIIF extends ExportRecords {

    /**
     * @var string|null The obfuscated ID of a specific uploaded file to export.
     *                  If set, only this file will be processed into the manifest.
     */
    private $ulf_ObfuscatedFileID = null;

    /**
     * @var int Counter for the number of resources outputted.
     *          Used to limit the number of items per manifest.
     */
    private $cnt = 0;

    /** @var array Buffered IIIF v3 Canvas objects for generated media manifests. */
    private $v3_canvas_items = array();

    /** @var array Buffered IIIF v3 Manifest references for registered manifests in the recordset. */
    private $v3_manifest_items = array();

    /** @var string|null Current output URI, reused by v3 Manifest/Collection wrappers. */
    private $manifest_uri = null;

    /** @var array Obfuscated file IDs for registered IIIF manifests found in v3 recordset export. */
    private $v3_manifest_fileids = array();

    /** @var bool Whether generated Canvas objects should omit AnnotationPage links. */
    private $omit_annotation_pages = false;

    /** @var DbIiifCanvas|null */
    private $dbCanvas = null;

    /** @var DbIiifManifest|null */
    private $dbManifest = null;

    /**
     * Prepares for the export operation.
     *
     * @param array $data The data to be exported (typically records).
     * @param array $params Parameters for the export.
     * @return bool True if preparation was successful, false otherwise.
     */
    protected function _outputPrepare($data, $params){

        // IIIF Presentation API v2 output is deliberately retired.  Import from
        // v2/hybrid sources remains supported elsewhere and produces v3 output.
        if(@$params['version']==2 || @$params['v']==2){
            $this->system->addError(
                HEURIST_ACTION_BLOCKED,
                'IIIF Presentation API v2 output is no longer supported. Please use IIIF Presentation API v3.'
            );
            return false;
        }

        $params['depth'] = 0;

        $res = parent::_outputPrepare($data, $params);
        if($res){
            $this->omit_annotation_pages = !empty($params['omit_annotation_pages']) && intval($params['omit_annotation_pages']) === 1;
        }

        return $res;
    }

    /**
     * Prepares the fields required for the IIIF export.
     *
     * @param array $params Parameters for the export, may include 'iiif_image' for a specific file.
     */
    protected function _outputPrepareFields($params){

        $this->retrieve_detail_fields = array('file');
        $this->retrieve_header_fields = 'rec_ID,rec_RecTypeID,rec_Title';

        $this->ulf_ObfuscatedFileID = @$params['iiif_image'];
    }

    /**
     * Initialise v3 output buffers.  The top-level resource is buffered until
     * footer so we can decide whether it must be a Manifest or Collection.
     */
    protected function _outputHeader(){

        $this->manifest_uri = HEURIST_SERVER_URL.$_SERVER['REQUEST_URI'];
        $this->cnt = 0;
        $this->v3_canvas_items = array();
        $this->v3_manifest_items = array();
        $this->v3_manifest_fileids = array();
    }

    /**
     * Outputs a single record as one or more IIIF resources.
     *
     * @param array $record The Heurist record to process.
     * @return bool True to continue processing, false to stop.
     */
    protected function _outputRecord($record){

        foreach($this->fileInfosForRecord($record) as $fileinfo){
            if($this->isRegisteredIiifManifestFile($fileinfo)){
                $manifestRef = $this->dbManifest()->manifestReferenceForFile($fileinfo, $record);
                if($manifestRef){
                    $this->v3_manifest_items[] = $manifestRef;
                    if(!empty($fileinfo['ulf_ObfuscatedFileID'])){
                        $this->v3_manifest_fileids[] = (string)$fileinfo['ulf_ObfuscatedFileID'];
                    }
                    $this->cnt++;
                }
                continue;
            }

            if(!$this->isSupportedMediaFile($fileinfo)){
                continue;
            }

            $canvas = $this->dbCanvas()->canvasJsonForFileInfo($fileinfo, array(
                'label' => $this->recordLabel($record),
                'include_annotation_pages' => !$this->omit_annotation_pages
                    && self::hasLinkedIiifAnnotations($this->system, intval($fileinfo['ulf_ID'] ?? 0)),
                'omit_annotation_pages' => $this->omit_annotation_pages,
                'body_fullres' => true,
                'base_url' => HEURIST_BASE_URL_PRO
            ));
            if($canvas){
                $this->v3_canvas_items[] = $canvas;
                $this->cnt++;
            }
        }

        // Not more than 1000 resources per manifest, or the only image if a
        // specific file ID was requested.
        return !($this->cnt>1000 || $this->ulf_ObfuscatedFileID!=null);
    }

    /**
     * Outputs the final IIIF v3 Manifest or Collection.
     */
    protected function _outputFooter(){

        $label = array('en' => array('Heurist IIIF manifest'));
        $this->v3_manifest_fileids = array_values(array_unique($this->v3_manifest_fileids));

        if(count($this->v3_manifest_items) === 1 && empty($this->v3_canvas_items) && count($this->v3_manifest_fileids) === 1){
            // Preserve existing behaviour: a recordset containing exactly one registered
            // Manifest returns that Manifest, not a Collection with one Manifest reference.
            $manifest = $this->iiifService()->getResourceJson('manifest', $this->v3_manifest_fileids[0], array(
                'omit_annotation_pages' => $this->omit_annotation_pages
            ));
            if($manifest){
                fwrite($this->fd, $manifest);
                return;
            }
        }

        if(!empty($this->v3_manifest_items)){
            $items = $this->v3_manifest_items;

            if(!empty($this->v3_canvas_items)){
                $items[] = IiifManifestJson::composeManifest(
                    $this->manifest_uri.'#generated-media-manifest',
                    $label,
                    $this->v3_canvas_items
                );
            }

            $resource = IiifManifestJson::composeCollection(
                $this->manifest_uri,
                array('en' => array('Heurist IIIF collection')),
                $items
            );
        }else{
            $resource = IiifManifestJson::composeManifest(
                $this->manifest_uri,
                $label,
                $this->v3_canvas_items
            );
        }

        fwrite($this->fd, json_encode($resource, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
    }

    private function dbCanvas(): DbIiifCanvas
    {
        if($this->dbCanvas===null){
            $this->dbCanvas = new DbIiifCanvas($this->system);
        }
        return $this->dbCanvas;
    }

    private function dbManifest(): DbIiifManifest
    {
        if($this->dbManifest===null){
            $this->dbManifest = new DbIiifManifest($this->system);
        }
        return $this->dbManifest;
    }

    private function iiifService(): IiifPresentationService
    {
        return new IiifPresentationService($this->system);
    }

    private function recordLabel(array $record): string
    {
        $label = trim(strip_tags((string)($record['rec_Title'] ?? '')));
        return $label!=='' ? $label : 'Heurist IIIF canvas';
    }

    private function fileInfosForRecord(array $record): array
    {
        $files = array();
        if(!is_array($record['details'] ?? null)){
            return $files;
        }

        foreach($record['details'] as $fieldDetails){
            if(!is_array($fieldDetails)){
                continue;
            }
            foreach($fieldDetails as $file){
                if(!is_array($file) || empty($file['file']) || !is_array($file['file'])){
                    continue;
                }
                if($this->ulf_ObfuscatedFileID
                    && ($file['file']['ulf_ObfuscatedFileID'] ?? null)!=$this->ulf_ObfuscatedFileID){
                    continue;
                }
                $files[] = $file['file'];
            }
        }

        return $files;
    }

    private function isSupportedMediaFile(array $fileinfo): bool
    {
        $mimeType = strtolower((string)($fileinfo['fxm_MimeType'] ?? ''));
        if(strpos($mimeType, 'video/')===0){
            return strpos($mimeType, 'youtube')===false && strpos($mimeType, 'vimeo')===false;
        }
        if(strpos($mimeType, 'audio/')===0){
            return strpos($mimeType, 'soundcloud')===false;
        }
        return strpos($mimeType, 'image/')===0 || IiifMediaHelper::isIiifImageInfoFile($fileinfo);
    }

    /** Return true only for registered IIIF Presentation manifests, not IIIF Image API info.json resources. */
    private function isRegisteredIiifManifestFile(array $fileinfo): bool
    {
        $source = (string)($fileinfo['ulf_PreferredSource'] ?? '');
        if($source === 'iiif_image'){
            return false;
        }
        if($source === 'iiif'){
            return true;
        }
        return defined('ULF_IIIF')
            && strpos((string)($fileinfo['ulf_OrigFileName'] ?? ''), ULF_IIIF) === 0
            && (!defined('ULF_IIIF_IMAGE')
                || strpos((string)($fileinfo['ulf_OrigFileName'] ?? ''), ULF_IIIF_IMAGE) !== 0);
    }

    private static function getAnnotationRectypeIds($system): array
    {
        $rty_ids = array();

        if($system->defineConstant('RT_IIIF_ANNOTATION')){
            $rty_ids[] = RT_IIIF_ANNOTATION;
        }
        if($system->defineConstant('RT_ANNOTATION') && !in_array(RT_ANNOTATION, $rty_ids)){
            $rty_ids[] = RT_ANNOTATION;
        }

        return $rty_ids;
    }

    private static function hasLinkedIiifAnnotations($system, int $ulf_ID): bool
    {
        $rty_ids = self::getAnnotationRectypeIds($system);
        if(empty($rty_ids) || $ulf_ID < 1){
            return false;
        }

        $mysqli = $system->getMysqli();
        $query = 'SELECT 1 '
            .' FROM recDetails media, recLinks, Records anno '
            .' WHERE media.dtl_UploadedFileID='.intval($ulf_ID)
            .' AND rl_TargetID=media.dtl_RecID '
            .' AND anno.rec_ID=rl_SourceID '
            .' AND anno.rec_RecTypeID IN ('.implode(',', $rty_ids).') '
            .' LIMIT 1';

        return mysql__select_value($mysqli, $query) ? true : false;
    }

    /**
     * Compatibility wrapper for /api/{db}/iiif/{resource}/{id}.
     *
     * @param \hserv\System $system Initialised Heurist system object
     * @param string $resource Resource name: manifest, canvas, page, annotation, annotations
     * @param string $ulf_ObfuscatedFileID Registered file obfuscated ID, or managed Manifest record ID for resource=manifest
     * @return string|false JSON string or false on error
     */
    public static function getIiifApiResource($system, string $resource, string $ulf_ObfuscatedFileID, bool $omitAnnotationPages=false)
    {
        $service = new IiifPresentationService($system);
        return $service->getResourceJson($resource, $ulf_ObfuscatedFileID, array(
            'omit_annotation_pages' => $omitAnnotationPages
        ));
    }

} //end class
?>
