/**
 * lookupGN_postalCode.js - GeoNames Postal Code lookup service.
 *
 * @fileOverview
 * This file defines the `heurist.lookupGN_postalCode` jQuery UI widget.
 * It specializes `heurist.lookupGeonames` to provide search functionality
 * for postal codes using the GeoNames database (api.geonames.org/postalCodeLookupJSON).
 * This widget allows users to search by postal code and/or place name, optionally
 * filtered by country. It processes the JSON response from GeoNames and formats
 * the results for display, including a link to Google Maps.
 *
 * @package     Heurist academic knowledge management system
 * @subpackage  hclient\widgets\lookup
 * @link        https://HeuristNetwork.org
 * @copyright   (C) 2005-2023 University of Sydney, (C) 2024 onwards Heurist Network
 * @license     https://www.gnu.org/licenses/gpl-3.0.txt GNU License 3.0
 * @author      Artem Osmakov   <osmakov@gmail.com>
 * @author      Ian Johnson <ian.johnson.heurist@gmail.com>
 * @since       6.0
 */

/**
 * Widget for performing postal code searches against the GeoNames database.
 * It uses the `postalCodeLookupJSON` endpoint of the GeoNames API.
 *
 * @widget heurist.lookupGN_postalCode
 * @extends heurist.lookupGeonames
 */
$.widget("heurist.lookupGN_postalCode", $.heurist.lookupGeonames, {

    /**
     * The base URL for the GeoNames postal code lookup API.
     * Note: The protocol ('http') is explicitly constructed.
     * @memberof heurist.lookupGN_postalCode
     * @instance
     * @type {string}
     */
    baseURL: 'http'+'://api.geonames.org/postalCodeLookupJSON?',

    /**
     * The service name identifier. Although it targets a specific GeoNames endpoint,
     * it might share the general 'geonames' service type for proxy or configuration purposes.
     * @memberof heurist.lookupGN_postalCode
     * @instance
     * @type {string}
     */
    serviceName: 'geonames',

    /**
     * Initializes UI controls specific to the Postal Code lookup.
     * - Adjusts CSS for header elements within the search container.
     * - Positions the button container relative to the search container.
     * - Calls the parent widget's `_initControls` method for common setup.
     *
     * @memberof heurist.lookupGN_postalCode
     * @instance
     * @private
     * @override
     * @returns {void|*} The result of `this._super()`.
     */
    _initControls: function(){
        this.element.find('#search_container > div > div > .header').css({width:'80px','min-width':'80px', display: 'inline-block'});
        this.element.find('#btn_container').position({my: 'left center', at: 'right center', of: '#search_container'});
        return this._super();
    },

    /**
     * Renders a single record in the result list for GeoNames postal code search results.
     * This method overrides the parent's `_rendererResultList`.
     * It constructs a display string (`recTitle`) by concatenating 'postalcode', 'placeName',
     * 'adminName2' (county/secondary division), 'adminName1' (state/primary division), and 'countryCode'.
     * It does not include a direct GeoNames link but prepares for a Google Maps link in `_onSearchResult`.
     *
     * @memberof heurist.lookupGN_postalCode
     * @instance
     * @private
     * @override
     * @param {HRecordSet} recordset - The complete HRecordSet object.
     * @param {Array} record - The individual record (row) from the recordset.
     * @returns {string} The HTML string for the rendered record, generated by the parent's `_rendererResultList`.
     */
    _rendererResultList: function(recordset, record){
        
        /**
         * Inner helper function to format a field's value for display.
         * It HTML escapes the value and wraps it in a div with a specified width for truncation.
         * If `fldname` is 'googlemap_link', it creates an anchor tag for Google Maps.
         * @param {string} fldname - The name of the field.
         * @param {number} width - The display width for the field in 'ex' units.
         * @returns {string} HTML string for the formatted field.
         */
        function fld(fldname, width){
            let s = recordset.fld(record, fldname);
            s = window.hWin.HEURIST4.util.htmlEscape(s || '');
            let title = s;

            if(fldname == 'googlemap_link'){ // This field is added during _onSearchResult
                s = `<a href="${s}" target="_blank" rel="noopener"> google maps </a>`;
                title = 'View location via Google Maps';
            }
            return width > 0 ? `<div style="display:inline-block;width:${width}ex" class="truncate" title="${title}">${s}</div>` : s;
        }

        // Construct the composite title string for the record display
        let recTitle = fld('postalcode', 10) + fld('placeName', 40) + fld('adminName2', 30) + fld('adminName1', 30) + fld('countryCode', 6);
        recordset.setFld(record, 'rec_Title', recTitle); // Set the formatted title

        return this._super(recordset, record); // Call parent's renderer
    },

    /**
     * Constructs the parameters for the GeoNames postal code search and calls the parent's `_doSearch`.
     * This method overrides the parent `_doSearch`.
     *
     * - If both postal code (`#inpt_postalcode`) and place name (`#inpt_placename`) inputs are empty,
     *   it shows a flash message and returns.
     * - Otherwise, it constructs a `params` object with:
     *   - `postalcode`: Value from `#inpt_postalcode`.
     *   - `placename`: Value from `#inpt_placename`.
     *   - `country`: Standardized country code from `#inpt_country` via `_getCountryCode`.
     * - Calls `this._super(params)` to execute the search. The parent `lookupGeonames`
     *   will use `this.baseURL` (which points to the postalCodeLookupJSON endpoint) and these parameters.
     *
     * @memberof heurist.lookupGN_postalCode
     * @instance
     * @private
     * @override
     * @returns {void}
     */
    _doSearch: function(){
        
        if(this.element.find('#inpt_postalcode').val()=='' && this.element.find('#inpt_placename').val()==''){
            window.hWin.HEURIST4.msg.showMsgFlash('Please enter a place name or postal code to perform search', 1000);
            return;
        }

        // Pass parameters directly to parent _doSearch, which will use this.baseURL
        this._super({
            postalcode: this.element.find('#inpt_postalcode').val(),
            placename: this.element.find('#inpt_placename').val(),
            country: this._getCountryCode(this.element.find('#inpt_country').val())
        });
    },

    /**
     * Processes the JSON results from a GeoNames postal code search.
     * This method overrides the parent `_onSearchResult`.
     *
     * - Parses `json_data`. If invalid, calls `this._super(false)`.
     * - Prepares field mappings using `_prepareMappableFields('googlemap_link')` to include a Google Maps link.
     * - Normalizes the input data: if `json_data.postalcodes` doesn't exist, assumes `json_data` itself is the array/object.
     *   Ensures `data` (derived from `json_data.postalcodes`) is an array.
     * - Iterates through each `feature` in `data`:
     *   - Assigns a local `recID`.
     *   - Creates `values` array starting with `recID` and `this.options.mapping.rty_ID`.
     *   - For each field in `map_flds`:
     *     - Extracts value from `feature`.
     *     - If `fld_Name` is 'location', constructs WKT point string using `this.constructLocation(lng, lat)`.
     *     - Pushes value to `values`.
     *   - Adds a Google Maps search URL (e.g., `https://www.google.com/maps/search/?api=1&query=lat,lng`) to `values`.
     *   - Stores `values` in `res_records` and `recID` in `res_orders`.
     * - Constructs final result object or `false`.
     * - Calls `this._super(res)` to display results.
     *
     * @memberof heurist.lookupGN_postalCode
     * @instance
     * @private
     * @override
     * @param {Object|string} json_data - The JSON response from the GeoNames postal code lookup.
     * @returns {void}
     */
    _onSearchResult: function(json_data){

        json_data = window.hWin.HEURIST4.util.isJSON(json_data); // Ensure it's a JS object

        if(!json_data){ // If parsing failed or empty
            this._super(false); // Clear results
            return;
        }

        let res_records = {}, res_orders = [];
        let map_flds, fields;

        // Get fields to map, adding 'googlemap_link' for the custom link
        [map_flds, fields] = this._prepareMappableFields('googlemap_link');

        // Normalize data (postalCodeLookupJSON returns {postalcodes: [...]})
        if(!json_data.postalcodes) json_data.postalcodes = json_data; // Fallback if structure is unexpected

        let i = 1; // Local record ID counter
        let data = this.valueToArray(json_data.postalcodes); // Array of postal code features

        for(const idx in data){
            let feature = data[idx];
            let recID = i++;
            let values = [recID, this.options.mapping.rty_ID]; // Start with local ID and target rty_ID

            for(const fld_Name of map_flds){
                let val = feature[fld_Name];
                if(fld_Name == 'location'){ // Construct WKT for location
                    val = this.constructLocation(feature['lng'], feature['lat']);
                }
                values.push(val);    
            }

            // Add the Google Maps search link
            values.push(`https://www.google.com/maps/search/?api=1&query=${feature['lat']},${feature['lng']}`);

            res_orders.push(recID);
            res_records[recID] = values;
        }

        // Prepare final result object for the parent
        let res = res_orders.length > 0 ? {fields: fields, order: res_orders, records: res_records} : false;
        this._super(res); // Pass to parent to render
    }
});