/**
 * lookupNakalaAuthor.js - Search Nakala "Author" records.
 *
 * @fileOverview
 * This file defines the `heurist.lookupNakalaAuthor` jQuery UI widget.
 * This widget provides an interface for searching author records from the
 * Nakala API (specifically `api.nakala.fr/authors/search`). It allows users
 * to search for authors by name and displays results including the author's name,
 * Nakala author ID, and a link to their ORCID record if available.
 * Selected author data can then be mapped to Heurist fields.
 *
 * @project     Heurist academic knowledge management system
 *
 * @link        https://HeuristNetwork.org
 * @copyright   (C) 2005-2023 University of Sydney, (C) 2024 onwards Heurist Network
 * @license     https://www.gnu.org/licenses/gpl-3.0.txt GNU License 3.0
 * @author      Brandon McKay   <blmckay13@gmail.com>
 * @author      Ian Johnson <ian.johnson.heurist@gmail.com>
 * @since       6.0
 */

/**
 * Widget for searching author records from the Nakala service.
 * It allows users to search authors by name and select records for data mapping.
 *
 * @widget heurist.lookupNakalaAuthor
 * @augments heurist.lookupBase
 */
$.widget( "heurist.lookupNakalaAuthor", $.heurist.lookupBase, {

    /**
     * Default options for the Nakala Author lookup widget.
     * @memberof heurist.lookupNakalaAuthor
     * @instance
     * @property {Object} options
     * @property {number} [options.height=700] - The height of the dialog.
     * @property {number} [options.width=550] - The width of the dialog.
     * @property {string} [options.title="Search Nakala's author records"] - The title of the dialog.
     * @property {string} [options.htmlContent='lookupNakalaAuthor.html'] - The HTML content file for the dialog.
     */
    options: {

        height: 700,
        width:  550,

        title:  "Search Nakala's author records",

        htmlContent: 'lookupNakalaAuthor.html'
    },

    /**
     * Initializes UI controls for the Nakala Author lookup widget.
     * - Applies specific CSS styling to header and button container elements.
     * - Calls the parent widget's `_initControls` method.
     *
     * @memberof heurist.lookupNakalaAuthor
     * @instance
     * @private
     * @override
     * @returns {void|*} The result of `this._super()`.
     */
    _initControls: function(){

        // Extra field styling
        this._$('#search_container > div > div > .header.recommended').css({width:'55px', 'min-width':'55px', display: 'inline-block'});
        this._$('#btn_container').position({my: 'left bottom', at: 'right bottom', of: '#search_container'});

        return this._super();
    },

    /**
     * Renders a single record in the result list for Nakala author search results.
     * This method overrides the parent's `_rendererResultList`.
     * It constructs a display string (`recTitle`) by concatenating a composite 'name'
     * (surname, given name, fullName), 'authorId', and 'orcid' (as a link).
     *
     * @memberof heurist.lookupNakalaAuthor
     * @instance
     * @private
     * @override
     * @param {HRecordSet} recordset - The complete HRecordSet object.
     * @param {Array} record - The individual record (row) from the recordset.
     * @returns {string} The HTML string for the rendered record, generated by the parent's `_rendererResultList`.
     */
    _rendererResultList: function(recordset, record){

        let that = this;

        /**
         * Inner helper function to format a field's value for display.
         * - Handles empty values.
         * - For the 'name' field, it constructs a composite string: "surname, givenname (fullName)".
         * - Converts objects to string arrays, joins arrays.
         * - HTML escapes the value.
         * - If `fldname` is 'orcid' and not empty, formats it as an anchor tag to the ORCID record.
         * - Wraps the result in a div with a specified width for truncation.
         * @param {string} fldname - The name of the field.
         * @param {number} width - The display width for the field in 'ex' units. If 0, no div wrapper.
         * @returns {string} HTML string for the formatted field.
         */
        function fld(fldname, width){
            let s = recordset.fld(record, fldname);

            if(that.$H.isempty(s) && s !== ''){
                s = '';
            }

            // Construct composite name field
            if(fldname == 'name'){
                s = `${recordset.fld(record, 'surname') || ''}, ${recordset.fld(record, 'givenname') || ''}`;
                let fullName = recordset.fld(record, 'fullName');
                if(fullName && fullName.trim() !== ''){
                    s += ` (${fullName.trim()})`;
                }
                s = s.replace(/^, /,'').replace(/, $/,'').trim(); // Clean up if parts are missing
            }

            s = that.$H.isObject(s) ? Object.values(s) : s;
            s = Array.isArray(s) ? s.join('; ') : s;

            let title = that.$H.htmlEscape(s || '');

            if(fldname == 'orcid' && s && s.trim() !== ''){ // Special formatting for ORCID link
                s = `<a href="${s}" target="_blank" rel="noopener"> view ORCID record </a>`;
                title = 'View ORCID record';
            }
            
            if(width > 0){ // Apply truncation styling
                s = `<div style="display:inline-block;width:${width}ex" class="truncate" title="${title}">${s}</div>`;
            }
            return s;
        }

        // Construct the composite title string for the record display
        const recTitle = fld('name', 30) + fld('authorId', 40) + fld('orcid', 20);
        recordset.setFld(record, 'rec_Title', recTitle); // Set the formatted title

        return this._super(recordset, record); // Call parent's renderer
    },

    /**
     * Processes the user's selection from the Nakala author result list.
     * This method overrides the parent `doAction`.
     * It calls the parent's `doAction` method, passing 'orcid' as the field name
     * to be potentially extracted as `ext_url` in the response object.
     * Other field mapping is handled by the generic `prepareValues` in the base class.
     *
     * @memberof heurist.lookupNakalaAuthor
     * @instance
     * @override
     * @returns {void}
     */
    doAction: function(){
        this._super('orcid'); // Pass 'orcid' to be used as potential external link
    },

    /**
     * Constructs the search query for the Nakala Authors API and executes the search
     * via the Heurist proxy.
     *
     * - Base URL: `https://api.nakala.fr/authors/search?q=`
     * - Appends the query term from `#inpt_any`.
     * - If no query term is provided, a message prompts the user.
     * - Makes a HAPI call to `RecordMgr.lookupService` with the constructed URL
     *   and `serviceType: 'nakala_author'`.
     * - Calls `_onSearchResult` with the response.
     *
     * @memberof heurist.lookupNakalaAuthor
     * @instance
     * @private
     * @override
     * @returns {void}
     */
    _doSearch: function(){

        let that = this;

        // Construct base url for external request
        let sURL = 'https://api.nakala.fr/authors/search?q='; // base URL for Nakala request
        
        // Construct query portion of url
        // any field
        if(this._$('#inpt_any').val()!=''){
            sURL += encodeURIComponent(this._$('#inpt_any').val());
        }

        // Check that something has been entered
        if(this._$('#inpt_any').val()==''){
            this.$Hmsg.showMsgFlash('Please enter a name in the search field...', 1000);
            return;
        }

        this.$Hmsg.bringCoverallToFront(this._as_dialog.parent()); // show loading cover

        // for LookupController.php
        let request = {
            service: sURL, // request url
            serviceType: 'nakala_author' // requesting service, otherwise the request will result in an error
        };

        // calls /heurist/hserv/controller/LookupController.php
        this.HAPI.RecordMgr.lookupService(request, function(response){

            that.$Hmsg.sendCoverallToBack(); // hide loading cover

            response = that.$H.isJSON(response);

            if(!Array.isArray(response) && response?.status != window.hWin.ResponseStatus.OK){ // Error return
                that.$Hmsg.showMsgErr(response);
                return;
            }

            that._onSearchResult(response);
        });
    },

    /**
     * Processes the search results received from the Nakala Authors API.
     * The Nakala Authors API returns a direct array of author objects, not a complex object.
     * This method overrides the parent `_onSearchResult`.
     *
     * - Checks if `array_data` is an array and not empty. If not, calls `this._super(false or null)`.
     * - Prepares field list: 'rec_ID', 'rec_RecTypeID', and fields from `this.options.mapping.fields`.
     * - Iterates through `array_data`:
     *   - Uses the array index as the local `recID` for display purposes.
     *   - Creates a `values` array for each record, starting with local `recID` and target `rty_ID`.
     *   - Appends values for each mapped field from the Nakala author record.
     *   - Stores the `values` array in `res_records` and `recID` (index) in `res_orders`.
     * - If total results (`array_data.length`) exceed `maxRecords` (from UI), shows a warning dialog.
     * - Constructs the final result object or `false`.
     * - Calls `this._super(res)` to display results.
     *
     * @memberof heurist.lookupNakalaAuthor
     * @instance
     * @private
     * @override
     * @param {Array<Object>|Object} array_data - The JSON response from the Nakala Authors search.
     *                                          Expected to be an array of author objects.
     *                                          Can also be an error object from HAPI.
     * @returns {void}
     */
    _onSearchResult: function(array_data){

        let maxRecords = this._$('#rec_limit').val(); // Get max records from UI
        maxRecords = (!maxRecords || maxRecords <= 0) ? 20 : maxRecords; // Default to 20

        let is_array = Array.isArray(array_data);

        // Handle cases with no or invalid data (API returns array directly, or error object)
        if(!is_array || array_data.length == 0){
            this._super(is_array && array_data.length == 0 ? null : false); // Pass null for empty array, false for non-array/error
            return;
        }

        let res_records = {}, res_orders = [];

        // Prepare fields for HRecordSet: base fields + mapped fields
        let fields = ['rec_ID', 'rec_RecTypeID'];
        let map_flds = Object.keys(this.options.mapping.fields); // Source fields from Nakala Author record
        fields = fields.concat(map_flds); // All fields for the HRecordSet

        // Parse Nakala author records into HRecordSet structure
        for(const recID_idx in array_data){ // Iterate using index as recID for display
            let record = array_data[recID_idx];
            let values = [Number.parseInt(recID_idx), this.options.mapping.rty_ID]; // Use array index as local rec_ID

            for(const fld_Name of map_flds){ // Populate values based on defined mapping
                values.push(record[fld_Name]);
            }

            res_orders.push(Number.parseInt(recID_idx));
            res_records[Number.parseInt(recID_idx)] = values;
        }

        // Warn if more results are available than shown
        if(array_data.length > maxRecords){
            this.$Hmsg.showMsgDlg(
                `There are ${array_data.length} records satisfying these criteria, only the first ${maxRecords} are shown.<br>Please narrow your search.`
            );
            // Note: The current implementation shows all results received, this message might be slightly misleading
            // if the API itself limits results before this point. The actual display limit is handled by resultList options.
        }

        let res = res_orders.length > 0 ? {fields: fields, order: res_orders, records: res_records} : false;
        this._super(res); // Pass to parent for display
    }
});