/**
 * lookupGN.js - GeoNames general search lookup service.
 *
 * @fileOverview
 * This file defines the `heurist.lookupGN` jQuery UI widget.
 * It specializes `heurist.lookupGeonames` to provide a general search
 * capability against the GeoNames database (api.geonames.org).
 * This widget allows users to search by place name, optionally filtered by country,
 * or directly by a GeoNames ID. It handles both JSON (for search) and XML
 * (for ID lookup, proxied via Heurist) responses from GeoNames.
 *
 * @project     Heurist academic knowledge management system
 *
 * @link        https://HeuristNetwork.org
 * @copyright   (C) 2005-2023 University of Sydney, (C) 2024 onwards Heurist Network
 * @license     https://www.gnu.org/licenses/gpl-3.0.txt GNU License 3.0
 * @author      Artem Osmakov   <osmakov@gmail.com>
 * @author      Ian Johnson <ian.johnson.heurist@gmail.com>
 * @since       6.0
 */

 /**
 * Widget for performing general searches against the GeoNames database.
 * It supports searching by place name (with optional country filter) which returns JSON,
 * and looking up a specific GeoNames ID which returns XML (and is proxied by Heurist).
 *
 * @widget heurist.lookupGN
 * @augments heurist.lookupGeonames
 */
$.widget("heurist.lookupGN", $.heurist.lookupGeonames, {

    /**
     * The base URL for the GeoNames API.
     * Note: The protocol ('http') is explicitly constructed to avoid mixed content issues
     * if the main Heurist page is HTTPS but GeoNames API is HTTP. This might need review
     * for current best practices (e.g., preferring HTTPS for API calls).
     * @memberof heurist.lookupGN
     * @instance
     * @type {string}
     */
    baseURL: 'http'+'://api.geonames.org/',

    /**
     * The service name identifier for this lookup type.
     * @memberof heurist.lookupGN
     * @instance
     * @type {string}
     */
    serviceName: 'geonames',

    /**
     * Renders a single record in the result list for GeoNames search results.
     * This method overrides the parent's `_rendererResultList` to provide custom formatting.
     * It constructs a display string (`recTitle`) by concatenating several fields from the record,
     * each formatted by the inner `fld` helper function. Fields include 'name', 'adminName1' (primary administrative division),
     * 'countryCode', 'fcodeName' (feature code name), 'fclName' (feature class name), and a link to the GeoNames record.
     *
     * @memberof heurist.lookupGN
     * @instance
     * @private
     * @override
     * @param {HRecordSet} recordset - The complete HRecordSet object containing the result data.
     * @param {Array} record - The individual record (row) from the recordset to be rendered.
     * @returns {string} The HTML string for the rendered record, generated by the parent's `_rendererResultList`.
     */
    _rendererResultList: function(recordset, record){
        
        let that = this;

        /**
         * Inner helper function to format a field's value for display.
         * It HTML escapes the value and wraps it in a div with a specified width for truncation.
         * If the field name is 'geoname_link', it formats the value as an anchor tag.
         * @param {string} fldname - The name of the field to retrieve from the record.
         * @param {number} width - The display width for the field in 'ex' units.
         * @returns {string} HTML string for the formatted field.
         */
        function fld(fldname, width){
            let s = recordset.fld(record, fldname);
            s = that.$H.htmlEscape(s || '');
            let title = s;

            if(fldname == 'geoname_link'){
                s = `<a href="${s}" target="_blank" rel="noopener"> view here </a>`;
                title = 'View geoname record';
            }
            return width > 0 ? `<div style="display:inline-block;width:${width}ex" class="truncate" title="${title}">${s}</div>` : s;
        }

        // Construct the composite title string for the record display
        let recTitle = fld('name', 40) + fld('adminName1', 20) + fld('countryCode', 6) + fld('fcodeName', 40) + fld('fclName', 20) + fld('geoname_link', 12);
        recordset.setFld(record, 'rec_Title', recTitle); // Set the formatted title back into the recordset

        return this._super(recordset, record); // Call parent's renderer
    },

    /**
     * Constructs the search query and initiates the search against the GeoNames API.
     * This method overrides the parent `_doSearch`.
     *
     * It determines whether to perform an ID lookup (returns XML, proxied by Heurist)
     * or a general search (returns JSON).
     *
     * - If both query input and ID input are empty, it shows a flash message and returns.
     * - If an ID is provided (`#inpt_id`), it constructs a URL for the GeoNames 'get' endpoint
     *   (e.g., `http://api.geonames.org/get?geonameId=...`) and sets `base_request['is_XML'] = true`
     *   to indicate that the Heurist proxy should expect XML.
     * - Otherwise (general search):
     *   - Constructs a URL for the GeoNames 'searchJSON' endpoint.
     *   - Adds `q` (query term from `#inpt_query`) and `country` (from `#inpt_country`, processed by `_getCountryCode`)
     *     as parameters.
     * - Sets `this.baseURL` to the constructed URL (though this might be slightly misleading as `_super` uses it differently).
     * - Calls `this._super(params, base_request)` to execute the search via the parent widget's mechanism,
     *   which will use `this.baseURL` (if not overridden by params.service) and `serviceName`.
     *   The `base_request` object allows passing specific options to the HAPI call like `is_XML`.
     *
     * @memberof heurist.lookupGN
     * @instance
     * @private
     * @override
     * @returns {void}
     */
    _doSearch: function(){
        
        if(this._$('#inpt_query').val()=='' && this._$('#inpt_id').val()==''){
            this.$Hmsg.showMsgFlash('Please enter a geoname id or a search term to perform a search', 1000);
            return;
        }

        let URL = 'http'+'://api.geonames.org/'; // Base GeoNames API URL
        let is_id_lookup = !this.$H.isempty(this._$('#inpt_id').val());
        let params = {}; // Parameters for the GeoNames API call
        let base_request = {}; // Parameters for the Heurist HAPI proxy call (_super)

        if(is_id_lookup){ // If GeoNames ID is provided
            URL += 'get?'; // Use the 'get' endpoint (returns XML)
            params['geonameId'] = this._$('#inpt_id').val();
            base_request['is_XML'] = true; // Signal to Heurist proxy that response is XML
        }else{ // General search
            URL += 'searchJSON?'; // Use the 'searchJSON' endpoint
            params['q'] = this._$('#inpt_query').val();
            params['country'] = this._getCountryCode(this._$('#inpt_country').val()); // Get standardized country code
        }

        this.baseURL = URL; // Set the specific endpoint URL (parent might use this or it might be overridden)

        // Call parent's _doSearch, passing API params and HAPI proxy options
        this._super(params, base_request);
    },

    /**
     * Processes the search results received from GeoNames (via Heurist proxy if XML, or directly if JSON).
     * This method overrides the parent `_onSearchResult`.
     *
     * - Parses `json_data` (which might be actual JSON or a JSON string representation of XML-derived data).
     * - If parsing fails or data is invalid, calls `this._super(false)` to clear results.
     * - Prepares field mappings using `_prepareMappableFields('geoname_link')` to include a link to the GeoNames page.
     * - Normalizes the input data: if `json_data.geonames` doesn't exist (common for single XML record results proxied as JSON),
     *   it assumes `json_data` itself is the record or array of records. Ensures `data` is an array.
     * - Iterates through each `feature` in the `data`:
     *   - Assigns a local `recID`.
     *   - Creates an array `values` starting with `recID` and `this.options.mapping.rty_ID`.
     *   - For each field in `map_flds` (from `_prepareMappableFields`):
     *     - Extracts the value from `feature`.
     *     - If `fld_Name` is 'location', constructs a WKT point string using `this.constructLocation(lng, lat)`.
     *     - Pushes the value to the `values` array.
     *   - Adds a direct link to the GeoNames page for the feature (`https://www.geonames.org/GEONAMEID/`).
     *   - Stores the `values` array in `res_records` keyed by `recID` and adds `recID` to `res_orders`.
     * - Constructs the final result object `{fields, order, records}` or `false` if no results.
     * - Calls `this._super(res)` to pass the processed data to the base lookup widget for display.
     *
     * @memberof heurist.lookupGN
     * @instance
     * @private
     * @override
     * @param {Object|string} json_data - The search response data. This can be a JSON object if the API returned JSON,
     *                                  or a JSON string/object derived from an XML response if proxied by Heurist.
     * @returns {void}
     */
    _onSearchResult: function(json_data){

        json_data = this.$H.isJSON(json_data); // Ensure json_data is a JS object

        if(!json_data){ // If parsing failed or data is empty
            this._super(false); // Clear results via parent
            return;
        }

        let res_records = {}, res_orders = [];
        let map_flds, fields;

        // Get the list of fields to map from the service definition, adding 'geoname_link'
        [map_flds, fields] = this._prepareMappableFields('geoname_link');

        // Normalize data structure (searchJSON returns {geonames: [...]}, single XML record might be the object itself)
        if(!json_data.geonames) json_data.geonames = json_data;
        
        let i = 1; // Counter for local record IDs
        let data = this.valueToArray(json_data.geonames); // The array of GeoNames features

        for(const idx in data){
            let feature = data[idx];
            let recID = i++;
            let values = [recID, this.options.mapping.rty_ID]; // Start with local ID and target Heurist rty_ID

            for(const fld_Name of map_flds){
                let val = feature[fld_Name];
                if(fld_Name == 'location'){ // Construct WKT point for location
                    val = this.constructLocation(feature['lng'], feature['lat']);
                }
                values.push(val);    
            }

            // Add the direct link to the GeoNames record page
            values.push(`https://www.geonames.org/${feature['geonameId']}/`);

            res_orders.push(recID);
            res_records[recID] = values;
        }

        // Prepare final result object for the parent's display mechanism
        let res = res_orders.length > 0 ? {fields: fields, order: res_orders, records: res_records} : false;
        this._super(res); // Pass to parent to render in resultList
    }
});