#!/bin/sh
echo ""
echo ""
echo "----------------------------------------------------------------------------------------"
echo ""
echo "Running script: diff_Structure_with_H3CoreDefinitions"
echo "usage: diff_Structure_with_H3CoreDefinitions dbname    (dbname excludes hdb_ prefix)"
if [ "$1" == "" ]; then
   echo "";echo "*** NO DATABASE NAME PROVIDED ***"; echo"";
   exit
fi
echo ""
echo "Dumping diff file $1.diff between H3CoreDefinitions and $1"
echo "Also writes H3CoreDefinitions.sql and $1.sql in temp directory in current location"
echo "These files can be used with a difference viewer such as TortoiseMerge"
echo ""
echo "Will create temp directory if it does not exist"
mkdir temp
echo ""
echo ""
mysqldump -u root -psmith18 -d hdb_H3CoreDefinitions > temp/H3CoreDefinitions.sql
mysqldump -u root -psmith18 -d hdb_$1 > temp/$1.sql
diff -b -w -B -a -u -d temp/H3CoreDefinitions.sql temp/$1.sql | grep -v AUTO_INCREMENT > temp/$1.diff
# auto-increment lines will vary jsut by the increment values between databases
echo ""
echo "done, look in temp directory for files"
echo ""
echo "--------------------------------------"
echo ""


