/*
* Copyright (C) 2005-2013 University of Sydney
*
* Licensed under the GNU License, Version 3.0 (the "License"); you may not use this file except
* in compliance with the License. You may obtain a copy of the License at
*
* http://www.gnu.org/licenses/gpl-3.0.txt
*
* Unless required by applicable law or agreed to in writing, software distributed under the License
* is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
* or implied. See the License for the specific language governing permissions and limitations under
* the License.
*/

/**
* brief description of file
*
* @author      Tom Murtagh
* @author      Kim Jackson
* @author      Ian Johnson   <ian.johnson@sydney.edu.au>
* @author      Stephen White   <stephen.white@sydney.edu.au>
* @author      Artem Osmakov   <artem.osmakov@sydney.edu.au>
* @copyright   (C) 2005-2013 University of Sydney
* @link        http://Sydney.edu.au/Heurist
* @version     3.1.0
* @license     http://www.gnu.org/licenses/gpl-3.0.txt GNU License 3.0
* @package     Heurist academic knowledge management system
* @subpackage  !!!subpackagename for file such as Administration, Search, Edit, Application, Library
*/

var testInputs = [	// 0 - test String descriptive title   1- test string
					["phrase date with comma","5th of January, 1965"],
					["slash separator d/m/y","25/8/2001"],
					["BCE  y","2000 BCE"],
					["neg year  ymd"," -145 March 14th"],
					["Spacing mdy"," Jun  30 865 "],
					["neg year with dash","-265-8-9"],
					["dash separator m-d-y","8-25-1890"],
					["dash separator d-m-y","25-8-1890"],
					["dash separator ambiguous day ?-?-y","5-8-1890"],
					["Full month dmy order with time","5 January 1788  5:00pm"],
					["Full month dmy order with time and timezone offset","5 January 1788  5:00pm +10"],
					["Full month dmy order","21 September 1964"],
					["Abrv.CAP month dmy order","22 SEPT 1965"],
					["Abrv.CAP month dmy order","23 OCT 1986"],
					["Abrv. month dmy order","11 Apr 1854"],
					["Abrv. month dmy order","22 Sept 1965"],
					["Abrv. w stop month dmy order","27 Dec. 2010"],
					["Contr and odd abrv month dmy order","5 Jany 1788"],
					["Contr and odd abrv month dmy order","7 Feby 1810"],
					["Contr and odd abrv month dmy order","19 Augt 1942"],
					["Contr and odd abrv month dmy order","21 Sepr 1964"],
					["Contr and odd abrv month dmy order","22 Septr 1965"],
					["Contr and odd abrv month dmy order","23 Octr 1986"],
					["Contr and odd abrv month dmy order","25 Novr 2008"],
					["Contr and odd abrv month dmy order","27 Decr 2010"],
					["Contr and odd abrv month dmy order","5 Jan'y 1788"],
					["Contr and odd abrv month dmy order","7 Feb'y 1810"],
					["Contr and odd abrv month dmy order","19 Aug't 1942"],
					["Contr and odd abrv month dmy order","21 Sep'r 1964"],
					["Contr and odd abrv month dmy order","22 Sept'r 1965"],
					["Contr and odd abrv month dmy order","23 Oct'r 1986"],
					["Contr and odd abrv month dmy order","25 Nov'r 2008"],
					["Contr and odd abrv month dmy order","27 Dec'r 2010"],
					["Full month mdy order","November 25 2008"],
					["Abrv.CAP month mdy order","JAN 5 1788"],
					["Abrv. month mdy order","Jun 15 1898"],
					["Abrv. month mdy order","Sept 22 1965"],
					["Abrv. w/ stop month mdy order","Feb. 7 1810"],
					["Abrv. w/ stop month mdy order","Mar. 9 1832"],
					["Abrv. w/ stop month mdy order","Apr. 11 1854"],
					["Contr and odd abrv month mdy order","Jany 5 1788"],
					["Contr and odd abrv month mdy order","Feby 7 1810"],
					["Contr and odd abrv month mdy order","Augt 19 1942"],
					["Contr and odd abrv month mdy order","Sepr 21 1964"],
					["Contr and odd abrv month mdy order","Septr 22 1965"],
					["Contr and odd abrv month mdy order","Octr 23 1986"],
					["Contr and odd abrv month mdy order","Novr 25 2008"],
					["Contr and odd abrv month mdy order","Decr 27 2010"],
					["Contr and odd abrv month mdy order","Jan'y 5 1788"],
					["Contr and odd abrv month mdy order","Feb'y 7 1810"],
					["Contr and odd abrv month mdy order","Aug't 19 1942"],
					["Contr and odd abrv month mdy order","Sep'r 21 1964"],
					["Contr and odd abrv month mdy order","Sept'r 22 1965"],
					["Contr and odd abrv month mdy order","Oct'r 23 1986"],
					["Contr and odd abrv month mdy order","Nov'r 25 2008"],
					["Contr and odd abrv month mdy order","Dec'r 27 2010"],
					["Ordinal day full month dmy order","1st January 1788"],
					["Ordinal day full month dmy order","2nd February 1810"],
					["Ordinal day full month dmy order","3rd March 1832"],
					["Ordinal day full month dmy order","11th April 1854"],
					["Ordinal day full month dmy order","21st September 1964"],
					["Ordinal day full month dmy order","22nd September 1965"],
					["Ordinal day full month dmy order","23rd October 1986"],
					["Ordinal day full month dmy order","25th November 2008"],
					["Ordinal day abrv. CAP month dmy order","1st JAN 1788"],
					["Ordinal day abrv. CAP month dmy order","2nd FEB 1810"],
					["Ordinal day abrv. CAP month dmy order","3rd MAR 1832"],
					["Ordinal day abrv. CAP month dmy order","11th APR 1854"],
					["Ordinal day abrv. CAP month dmy order","21st SEP 1964"],
					["Ordinal day abrv. CAP month dmy order","22nd SEPT 1965"],
					["Ordinal day abrv. CAP month dmy order","23rd OCT 1986"],
					["Ordinal day abrv. month dmy order","1st Jan 1788"],
					["Ordinal day abrv. month dmy order","2nd Feb 1810"],
					["Ordinal day abrv. month dmy order","3rd Mar 1832"],
					["Ordinal day abrv. month dmy order","11th Apr 1854"],
					["Ordinal day abrv. month dmy order","21st Sep 1964"],
					["Ordinal day abrv. month dmy order","22nd Sept 1965"],
					["Ordinal day abrv. month dmy order","23rd Oct 1986"],
					["Ordinal day abrv. w/ stop month dmy order","1st Jan. 1788"],
					["Ordinal day abrv. w/ stop month dmy order","2nd Feb. 1810"],
					["Ordinal day abrv. w/ stop month dmy order","3rd Mar. 1832"],
					["Ordinal day abrv. w/ stop month dmy order","11th Apr. 1854"],
					["Ordinal day abrv. w/ stop month dmy order","21st Sep. 1964"],
					["Ordinal day abrv. w/ stop month dmy order","22nd Sept. 1965"],
					["Ordinal day abrv. w/ stop month dmy order","23rd Oct. 1986"],
					["Ordinal day full month mdy order","January 1st 1788"],
					["Ordinal day full month mdy order","February 2nd 1810"],
					["Ordinal day full month mdy order","March 3rd 1832"],
					["Ordinal day full month mdy order","August 19th 1942"],
					["Ordinal day full month mdy order","September 21st 1964"],
					["Ordinal day full month mdy order","September 22nd 1965"],
					["Ordinal day full month mdy order","October 23rd 1986"],
					["Ordinal day abrv. w/ stop month mdy order","Jan. 1st 1788"],
					["Ordinal day abrv. w/ stop month mdy order","Feb. 2nd 1810"],
					["Ordinal day abrv. w/ stop month mdy order","Mar. 3rd 1832"],
					["Ordinal day abrv. w/ stop month mdy order","Jun. 15th 1898"],
					["Ordinal day abrv. w/ stop month mdy order","Sep. 21st 1964"],
					["Ordinal day abrv. w/ stop month mdy order","Sept. 22nd 1965"],
					["Ordinal day abrv. w/ stop month mdy order","Oct. 23rd 1986"],
					["Ordinal day abrv. w/ stop month mdy order","Dec. 27th 2010"],
					["Ordinal day w/ sp full month dmy order","1 st January 1788"],
					["Ordinal day w/ sp full month dmy order","2 nd February 1810"],
					["Ordinal day w/ sp full month dmy order","3 rd March 1832"],
					["Ordinal day w/ sp full month dmy order","19 th August 1942"],
					["Ordinal day w/ sp full month dmy order","21 st September 1964"],
					["Ordinal day w/ sp full month dmy order","22 nd September 1965"],
					["Ordinal day w/ sp full month dmy order","23 rd October 1986"],
					["Ordinal day w/ sp full month dmy order","25 th November 2008"],
					["Ordinal day w/ sp ABRV month dmy order","1 st JAN 1788"],
					["Ordinal day w/ sp ABRV month dmy order","2 nd FEB 1810"],
					["Ordinal day w/ sp ABRV month dmy order","3 rd MAR 1832"],
					["Ordinal day w/ sp ABRV month dmy order","21 st SEP 1964"],
					["Ordinal day w/ sp ABRV month dmy order","22 nd SEPT 1965"],
					["Ordinal day w/ sp ABRV month dmy order","23 rd OCT 1986"],
					["Ordinal day w/ sp ABRV month dmy order","25 th NOV 2008"],
					["Ordinal day w/ sp Abrv month dmy order","1 st Jan 1788"],
					["Ordinal day w/ sp Abrv month dmy order","2 nd Feb 1810"],
					["Ordinal day w/ sp Abrv month dmy order","3 rd Mar 1832"],
					["Ordinal day w/ sp Abrv month dmy order","15 th Jun 1898"],
					["Ordinal day w/ sp Abrv month dmy order","19 th Aug 1942"],
					["Ordinal day w/ sp Abrv month dmy order","21 st Sep 1964"],
					["Ordinal day w/ sp Abrv month dmy order","22 nd Sept 1965"],
					["Ordinal day w/ sp Abrv month dmy order","23 rd Oct 1986"],
					["Ordinal day w/ sp Abrv. month dmy order","1 st Jan. 1788"],
					["Ordinal day w/ sp Abrv. month dmy order","2 nd Feb. 1810"],
					["Ordinal day w/ sp Abrv. month dmy order","3 rd Mar. 1832"],
					["Ordinal day w/ sp Abrv. month dmy order","19 th Aug. 1942"],
					["Ordinal day w/ sp Abrv. month dmy order","21 st Sep. 1964"],
					["Ordinal day w/ sp Abrv. month dmy order","22 nd Sept. 1965"],
					["Ordinal day w/ sp Abrv. month dmy order","23 rd Oct. 1986"],
					["Ordinal day w/ sp Abrv. month dmy order","27 th Dec. 2010"],
					["Ordinal day w/ sp full month mdy order","January 1 st 1788"],
					["Ordinal day w/ sp full month mdy order","February 2 nd 1810"],
					["Ordinal day w/ sp full month mdy order","March 3 rd 1832"],
					["Ordinal day w/ sp full month mdy order","July 17 th 1920"],
					["Ordinal day w/ sp full month mdy order","September 21 st 1964"],
					["Ordinal day w/ sp full month mdy order","September 22 nd 1965"],
					["Ordinal day w/ sp full month mdy order","October 23 rd 1986"],
					["Ordinal day w/ sp Abrv. month mdy order","Jan. 1 st 1788"],
					["Ordinal day w/ sp Abrv. month mdy order","Feb. 2 nd 1810"],
					["Ordinal day w/ sp Abrv. month mdy order","Mar. 3 rd 1832"],
					["Ordinal day w/ sp Abrv. month mdy order","May. 13 th 1876"],
					["Ordinal day w/ sp Abrv. month mdy order","Aug. 19 th 1942"],
					["Ordinal day w/ sp Abrv. month mdy order","Sep. 21 st 1964"],
					["Ordinal day w/ sp Abrv. month mdy order","Sept. 22 nd 1965"],
					["Ordinal day w/ sp Abrv. month mdy order","Dec. 27 th 2010"],
					["Roman month dmy order","5 I 1788"],
					["Roman month dmy order","7 II 1810"],
					["Roman month dmy order","9 III 1832"],
					["Roman month dmy order","11 IV 1854"],
					["Roman month dmy order","13 V 1876"],
					["Roman month dmy order","15 VI 1898"],
					["Roman month dmy order","17 VII 1920"],
					["Roman month dmy order","19 VIII 1942"],
					["Roman month dmy order","21 VIIII 1964"],
					["Roman month dmy order","22 IX 1965"],
					["Roman month dmy order","23 X 1986"],
					["Roman month dmy order","25 XI 2008"],
					["Roman month dmy order","27 XII 2010"],
					["Roman month d-m-y order","5-I-1788"],
					["Roman month d-m-y order","7-II-1810"],
					["Roman month d-m-y order","9-III-1832"],
					["Roman month d-m-y order","11-IV-1854"],
					["Roman month d-m-y order","13-V-1876"],
					["Roman month d-m-y order","15-VI-1898"],
					["Roman month d-m-y order","17-VII-1920"],
					["Roman month d-m-y order","19-VIII-1942"],
					["Roman month d-m-y order","21-VIIII-1964"],
					["Roman month d-m-y order","22-IX-1965"],
					["Roman month d-m-y order","23-X-1986"],
					["Roman month d-m-y order","25-XI-2008"],
					["Roman month d-m-y order","27-XII-2010"]
				];
