<?php
// Be sure to use this quote  `  not the upright quote, or you will jsut get field names in place of data
$flds = "  `dty_ID`, `dty_Name`, `dty_Documentation`,
            `dty_Type`, `dty_HelpText`, `dty_ExtendedDescription`, `dty_EntryMask`,  `dty_Status`,
            `dty_OriginatingDBID`, `dty_NameInOriginatingDB`, `dty_IDInOriginatingDB`,
            `dty_DetailTypeGroupID`, `dty_OrderInGroup`,
            `dty_JsonTermIDTree`, `dty_TermIDTreeNonSelectableIDs`, `dty_PtrTargetRectypeIDs`,
            `dty_FieldSetRecTypeID`, `dty_ShowInLists`, `dty_NonOwnerVisibility` ,`dty_LocallyModified`,
            `dty_SemanticReferenceURL` ";
                        
            // Note: You must also add any new fields to the print format statement
            

?>
