<?php
// Be sure to use this quote  `  not the upright quote, or you will jsut get field names in place of data
$flds = "`rcs_ID`,`rcs_SourceRectypeID`,`rcs_TargetRectypeID`,`rcs_Description`,
            `rcs_RelationshipsLimit`,`rcs_Status`,
            `rcs_OriginatingDBID`,`rcs_IDInOriginatingDB`,
            `rcs_TermID`,`rcs_TermLimit` ,`rcs_LocallyModified` ";
                        
            // Note: You must also add any new fields to the print format statement
            

?>
