<?php
// Be sure to use this quote  `  not the upright quote, or you will jsut get field names in place of data
$flds = "`rty_ID`, `rty_Name`, `rty_OrderInGroup`, `rty_Description`, `rty_TitleMask`, `rty_CanonicalTitleMask`, `rty_Plural`,
`rty_Status`, `rty_OriginatingDBID`, `rty_NameInOriginatingDB`, `rty_IDInOriginatingDB`, `rty_NonOwnerVisibility`,
`rty_ShowInLists`, `rty_RecTypeGroupID`, `rty_RecTypeModelIDs`, `rty_FlagAsFieldset`, `rty_ReferenceURL`, `rty_AlternativeRecEditor`,
`rty_Type` , `rty_ShowURLOnEditForm`, `rty_ShowDescriptionOnEditForm`, `rty_LocallyModified` ";
            
            // Note: You must also add any new fields to the print format statement
            

?>
