<?php
// Be sure to use this quote  `  not the upright quote, or you will jsut get field names in place of data
$flds = "`rst_ID`, `rst_RecTypeID`,
            `rst_DetailTypeID`, `rst_DisplayName`, `rst_DisplayHelpText`,
            `rst_DisplayExtendedDescription`, `rst_DisplayOrder`, `rst_DisplayWidth`, `rst_DisplayHeight`,
            `rst_DefaultValue`, `rst_RecordMatchOrder`, `rst_CalcFunctionID`, `rst_CalcFieldMask`,
            `rst_RequirementType`, `rst_NonOwnerVisibility`, `rst_Status`, `rst_MayModify`,
            `rst_OriginatingDBID`, `rst_IDInOriginatingDB`,
            `rst_MaxValues`, `rst_MinValues`, `rst_InitialRepeats`, `rst_DisplayDetailTypeGroupID`,
            `rst_FilteredJsonTermIDTree`, `rst_PtrFilteredIDs`, `rst_CreateChildIfRecPtr`,
            `rst_PointerMode`, `rst_PointerBrowseFilter`,
            `rst_OrderForThumbnailGeneration`, `rst_TermIDTreeNonSelectableIDs`, 
            `rst_ShowDetailCertainty`, `rst_ShowDetailAnnotation`, `rst_NumericLargestValueUsed`, `rst_EntryMask`,
            `rst_LocallyModified` ";
                        
            // Note: You must also add any new fields to the print format statement
            

?>
